project:
  type: book
  output-dir: docs

book:
  title: "podcast-book"
  author: "Norah Jones"
  date: "10/9/2024"
  chapters:
    - index.qmd
    - podcast001.qmd
    - podcast002.qmd
    - podcast003.qmd
    - podcast004.qmd
    - podcast005.qmd
    - podcast006.qmd
    - podcast007.qmd
    - podcast008.qmd
    - podcast009.qmd
    - podcast010.qmd
    - podcast011.qmd
    - podcast012.qmd
    - podcast013.qmd
    - podcast014.qmd
    - podcast015.qmd
    - podcast016.qmd
    - podcast017.qmd
    - podcast018.qmd
    - podcast019.qmd
    - podcast020.qmd
    - podcast021.qmd
    - podcast023.qmd
    - podcast024.qmd
    - podcast025.qmd
    - podcast026.qmd
    - podcast027.qmd
    - podcast028.qmd
    - podcast029.qmd
    - podcast030.qmd
    - podcast031.qmd
    - podcast032.qmd
    - podcast033.qmd
    - podcast034.qmd
    - podcast035.qmd
    - podcast036.qmd
    - podcast037.qmd
    - podcast038.qmd
    - podcast039.qmd
    - podcast040.qmd
    - podcast041.qmd
    - podcast042.qmd
    - podcast043.qmd
    - podcast044.qmd
    - podcast045.qmd
    - podcast046.qmd
    - podcast047.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
