project:
  type: book
  output-dir: docs

book:
  title: "podcast-book"
  author: "Norah Jones"
  date: "10/9/2024"
  chapters:
    - index.qmd
    - podcast001.qmd
    - podcast002.qmd
    - podcast003.qmd
    - podcast004.qmd
    - podcast005.qmd
    - podcast006.qmd
    - podcast007.qmd
    - podcast008.qmd
    - podcast009.qmd
    - podcast010.qmd
    - podcast011.qmd
    - podcast012.qmd
    - podcast013.qmd
    - podcast014.qmd
    - podcast015.qmd
    - podcast016.qmd
    - podcast017.qmd
    - podcast018.qmd
    - podcast019.qmd
    - podcast020.qmd
    - podcast021.qmd
    - podcast023.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
