---
title: "任天堂的前生今世(下)"
editor: visual
---

2016-06-23

上一期我们提到，任天堂于明治维新后的1889年建立，经过了两代社长60年的经营，到1949年传到了山内溥的手中。山内溥上任后，经过严苛的革新，任天堂达到了前所未有的辉煌，成为了日本扑克业的老大。然而，在日本东京奥运会后，任天堂却经历了断崖式的下滑，股价从600日元暴跌至60日元，山内溥不得不再次进行改革。

此前，山内溥曾前往美国进行考察，发现美国最大的扑克公司也不过是一家中小型企业。而此时任天堂在日本的市场占有率已经超过了60%，再想进一步发展已十分困难。毕竟，市场占有率已达60%，再翻番就成了不切实际的120%。因此，公司面临的选择只有两条：多元化或国际化。

国际化在当时日本是非常困难的，因为当时的日本产品名声不佳，被视为山寨品，质量低劣。例如，1962年索尼公司国际化，在曼哈顿第五大道开设旗舰店时，虽然日本人对索尼挂出日本国旗感到激动，但像日立、东芝等更大的公司却不喜欢在美国挂日本旗，因为一挂日本旗销量就会下降。索尼公司的盛田昭夫后来回忆说，他们最初去美国时，日本产品给人的印象是便宜且质量差。如果不拿出好的产品，就无法在美国立足。索尼为了让美国人认为索尼不是日本货也是煞费苦心，比如将产品改名，把“日本制造”的标识印得非常小，以至于海关都看不清，还要求他们印得大一些。

同样，当时只会造纸牌的任天堂也面临困境。如果去美国造纸牌，恐怕凶多吉少。因此，任天堂选择了多元化。在1963到1968年间，任天堂开始了令人眼花缭乱的多元化尝试。尽管日本在很多方面比中国开明得多，但在男女关系方面却有着奇特的习俗。不过这些习俗在19世纪末期被禁止了，但当时仍在未婚女子和寡妇中较为普遍。再加上日本打仗需要慰安妇，以及美国占领日本后的宽松环境，使得那几年美国婴儿潮爆发。因此，任天堂大张旗鼓转型的一个业务就是提供钟点房，开了一家名为Love Hotel的连锁酒店。

当然，任天堂在开拓新业务的同时，也没有忘记老本行——纸牌的生产。在纸牌业务上，任天堂也是花样百出，比如印刷成人纸牌，上面全是裸女照片，包括当时风靡全球的玛丽莲·梦露的照片。

这样说起来，曾经的任天堂还是非常开放的，不知道后来为何变得如此保守，连游戏里有点暴力都受不了。真是三日不见，当刮目相看啊！

接下来，我们说说山内溥上任后的改革措施。他先是清除了家族成员，再是清除了工作了20年以上的老员工，同时高薪招聘年轻人才。其中就招到了一个名叫横井军平的小伙子。他被招聘进来是负责维修花札生产设备的技术修理工。横井军平在同志社大学学习期间就因兴趣爱好广泛而在同学中广有人气，后来凭借着亲手制作的诸多充满奇思妙想的小玩意儿在工学部博得了天才发明家的口碑。毕业后，他选择了当时名不见经传的京都小企业任天堂，原因是任天堂离家很近，可以骑自行车上班。

横井军平工作很努力，他利用工作间隙的边角料来发明创造。有一天，山内溥发现了他的小发明——一个可以弹出的机械手臂，就把他叫到办公室商量把这个玩具变成真正的商品推向市场。随后，任天堂组建了新的部门对横井军平的业余发明进行了改造，并通过电视广告的反复宣传，这个售价800日元的小玩具一年卖出了140万套。山内溥慧眼识珠，对这个销售量非常满意，随后将这个临时组建的部门重新改组为任天堂第一开发部，并让横井军平担任技术负责人。

在1960年代后半期，任天堂的超级怪手是公司非常畅销的产品，随后又推出了超级棒球、超级潜望镜等儿童玩具。就靠这些超级怪手类的玩具，任天堂每年从家长的口袋里赚了不少钱。

此后，横井军平招兵买马，他的好友上村雅之随后加入，此人后来成为任天堂第二开发部负责人；再后来又来了竹田玄洋，此人后来成为了任天堂第三开发部的负责人。到了1970年左右，任天堂的这三个技术核心逐渐成型。

在1975年，电视游戏厂商推出了一款家用游戏机——HOME-PONG，这是一个网球游戏，内容非常简单。虽然以现在的眼光来看这款游戏很简陋，但当时能用自己操纵电视画面中的东西，还能跟朋友对打，已经是很先进的玩意了。因此，好几个厂商开始开发各种类似的网球游戏以及打方块的游戏。其中就包括雅达利公司，他们曾经招聘过一个年轻人和他的朋友开发打砖块的游戏，这两个年轻人后来成立了一家公司叫苹果公司，这两个年轻人就是乔布斯和沃兹。

当时的任天堂正在考虑山寨雅达利的游戏机。那时候版权意识没有现在这么强，包括后来出品了哆啦A梦电子游戏的Epoch公司、现在还在卖高达玩具的万代公司以及现在卖各种玩具的Tomy公司都山寨过雅达利。所以任天堂这么干也不用觉得太不好意思。恰好当时日本的三菱公司正在搞微创新，想把雅达利的游戏做成彩色的。于是他们联系到任天堂，一拍即合，两个公司联合起来开始抄袭雅达利。当时的游戏机市场上价格都在2万到3万日元之间，山内溥考察了一下市场后，把上村雅之喊过来，说造一个1万日元的出来。当时三菱公司对此表示怀疑，但上村雅之也不是等闲之辈，从中斡旋之下，竟然真的造出来了一个1万日元的机器。

然而，当时市场上已经有包括万代、Epoch、Tomy等众多公司在山寨雅达利了，总共有40到50种同类型的机器，竞争非常激烈。这时候就显示出山内溥的老道了。他把这个游戏机分成两种型号：一种是TV-Game 6，内置了6种游戏；一种是TV-Game 15，内置了15种游戏。虽然这些游戏在本质上并没有太大区别，比如里面内置的《网球》、《排球》、《曲棍球》、《乒乓球》等游戏，除了名字不同外，玩法都一样。但山内溥先以成本价9800日元卖TV-Game 6这个产品，低价倾销以迅速占领市场，然后再以15000日元卖TV-Game 15这个游戏机。结果销量非常好，后来这两款产品总共卖了100万台以上，其中一半左右是TV-Game 15这个产品，每台利润5000日元。任天堂通过和三菱合作的方式，算是最终踏入了游戏业的大门。

这只是万里长征的第一步。任天堂需要另一员大将才能在游戏界呼风唤雨。这个人现在还失业在家，是山内溥的侄子。这个年轻落寞的年轻人大学读了五年才毕业，毕业后又失业了一年。经过父亲的关系才想到了可以去任天堂打工。后面的电台，我将讲述山内溥的大侄子——宫本茂的故事。虽然现在他还默默无闻，但谁又能知道将来此人会名满天下呢？他后来被称为“马里奥之父”。

好的，这一期就到这里。等我把宫本茂的材料整理完，再来讲他的故事。
