---
title: "第13期. 手握爪机向天问——抵制洋货有何难"
editor: visual
---

在1900年6月21日，一身沉重的慈禧终于走完了开战前的最后一步，她拿出了一道由军机章京连文冲起草的诏书，诏告天下，要向11个国家宣战。诏书发布以后，北京城门大开，义和团名正言顺地进入北京，开始了和清政府的短暂联合。慈禧给义和团管吃管住，还发薪水，并且规定，如果杀掉一个男性洋人，就赏银五十两；如果杀掉一个女性洋人，赏银四十两；如果杀掉一个儿童洋人，赏银二十两；如果能够进攻外国人的使馆，赏银更是高达十万两。

义和团是依靠抵制洋人、抵制洋货起家的，还号称刀枪不入。从义和团开始，抵制洋货的运动越演越烈，后来还成立了中华国货维持会。该组织成为领导全国的机构，宣称只使用国货。该组织一直运行到抗日战争爆发前夕，后来屡次爆发各种抵制洋货的运动，一直到今天，这种抵制运动依然此起彼伏。

我无意评价抵抗运动的是与非。在这里，我只想看一看，在IT界以电子产品——手机为例，看一看抵制洋货到底有多难。

按照电子业的规矩，我们把手机分成两个部分：一部分是软件，另一部分是硬件。

先来说说软件。这里的软件主要是指操作系统。目前手机操作系统主要有三种：一个是谷歌出的安卓系统，一个是苹果出的iOS系统，最后一个是微软出的Windows系统。国内那些号称国产系统的，比如说小米的MIUI系统、锤子手机的Smartisan OS系统，还有华为手机的EMUI系统，本质上都是安卓的修改版。这些系统有一个共同的“父亲”，就是谷歌的安卓系统。这些中国的公司对安卓系统进行了深入的定制，删除了一些功能，添加了一些功能，让手机系统更适合中国用户。但是追根溯源，如果没有安卓，这些系统将不复存在。如果真的抵制洋货，中国的手机用户可能面临没有系统可用的境地。

再说硬件。在2011年3月11日，日本发生了9.0级的超级大地震，造成了40多米高的海啸，是日本有史以来观测到的最强的地震。此次地震引发了火灾、水灾以及核泄漏事件，对日本东北部地区造成了毁灭性的打击。伴随着日本地震的消息，电子元件的价格应声上涨，电子产品大量短缺。包括日本、韩国以及台湾地区的半导体公司纷纷陷入困境，无法接受新的订单。郭台铭的公司——富士康也全线告急，中国的工人几乎陷入没有材料生产的境地。这次地震让全世界都感觉到了“日本感冒，全世界吃药”的威力。

我们分别来看一下手机里的硬件有多少“洋货”。先来说CPU，每个手机都需要有一个CPU。目前安卓手机最常用的CPU是高通的CPU。当然，国内的魅族一直使用三星的CPU，小米则使用高通的CPU。如果支持国货的话，可以使用华为的手机，华为的CPU是基于ARM架构自己研发的——海思CPU。说实在的，我非常佩服华为公司踏踏实实的精神。新闻上说，华为已经开始研发自己的操作系统了。再多说一句，关于华为，我是非常敬佩的。我的第一份工作是在一家和华为竞争的外企，做路由器的。我们都是一到五点就下班了，但华为的员工还在机房里干活。等到第二天我们去机房的时候，因为机房一般是要锁门的，然后你就会发现，很多华为的员工已经在机房里加班加了一晚上。所以我觉得，华为如果要成为世界一流的公司，需要的只是时间。

在日本，还有一家叫做信越化学的公司，也被地震所波及。这个公司是做晶圆的，是芯片生产的重要原料。如果没有这种原材料，CPU和显存都无法生产。因此，生产手机闪存的东芝公司在这次地震中虽然受到的波及并不大，但是信越化学受到的波及非常厉害，它没有办法提供晶圆了，因此导致东芝公司也没有办法再生产，闪存也就没有办法发货，所以还是导致了东芝公司很大的困境。

说完了CPU，我们再来说一下电路板。我们都知道智能手机里都有一个电路板，就是那块承载所有元器件的电路板。它的学名叫PCB，叫做印刷电路板。我第二份工作曾经和广东一家叫建滔的公司打交道，这家公司就有PCB产品。我还曾经去过那个公司，但是这个公司当时的PCB是没有办法在手机等精密仪器里使用的。当时用在电视机上是可以的，因为用在手机里的PCB要精细一些，是一种叫做BT树脂的东西。这种树脂目前90%的产能在日本，被日本的日立化成和住友化学所垄断。这次地震直接导致这两家公司无法生产，因此导致手机没有PCB可用的境地。

说完了PCB的电路板，我们再来说一下电池。现在手机里的电池基本上都是锂电池，它的全称叫锂离子聚合物电池。中国的锂资源是非常丰富的，按目前的用量来说，中国好几百年也用不完。比如说光江西的一个矿就可以用100年。但是之所以叫锂离子聚合物电池，里面还有一种叫聚合物，是一种特殊的化学物质。它的学名叫聚偏二氟乙烯，70%以上的这种东西是日本一家叫做吴羽化工的公司生产的。很不幸，这家公司在地震的时候，工厂离震中心非常近，遭受到了极其严重的破坏。地震之后，这个工厂直接就关闭了。日本这一地震让整个电子行业重新认识了日本。一些看似打不着杆子的公司，在地震以后才发现，原来它对电子产品的影响如此之大。比如这家叫做吴羽化工的公司，直接让手机的电池无法生产了，因为全球70%的聚合物都是他家生产的。

这样说起来，我们再来说一下手机的硬件组成。在一些机构研究了苹果手机的组成后，发现一台iPhone手机硬件成本大概是180多美元，其中34%来源于日本，17%来源于德国，13%来源于韩国，剩下的那30%左右就是其他的地方，其中中国大概是3.5%。因此，《华尔街日报》还专门写文章来贬低中国，说严重高估了中国的作用，扭曲了中美贸易。再多说一句，这里所说的iPhone的硬件成本是180多美元，这个180美元里是没有包括研发费用的。人家美国总部那边还得设计，还有软件开发的费用也没有包括进去。毕竟软件开发是非常耗费资金的，不可能说这个硬件成本多好，然后再卖给你。就好像是微软的话，光盘的硬件成本肯定不到一块钱，毕竟就一张光盘，批量生产的话肯定远远不到一块钱。最主要的价格其实是微软研发的费用。

再来说一下日本地震对手机界的影响。日本这次地震让国内的手机厂商也非常的震惊。原来都是用日本的小零件，比如说这个手机的镜头里面有一个马达来变焦的。本来以为日本生产的也就那样，结果日本地震以后根本没有办法在短时间内供货，只好用韩国或者是台湾产的那种小马达。后来用了以后才发现手机的返修率一下子就上了不少。因为韩国和台湾的电子产业，比起日本的产品质量还是有不少差距的。

所以，就算是我们每天都要使用的这个手机，如果细算的话，真的搞不清楚这个里面到底有多少“洋货”。虽然我们用的手机品牌可能是中国的华为，也可能是中国的联想或者是小米，但是在这个扁平的地球上，早就形成了你中有我、我中有你的生态链，早就分不清到底是哪家生产的了。还有就是中国在整个手机或者电子产品生产链上是处于一个组装的角色。整个电子产品的组装大部分都是在中国大陆上，由中国大陆的员工完成的。比如说像富士康这样的公司，富士康在大陆大概共用了80万到100万工人。因此，富士康的老板郭台铭被称为“富士康市市长”。想想也是，大概是一个100万人的城市，有100万中国的年轻人在富士康的流水线上组装着运往世界各地的电子产品，有可能是手机，也有可能是游戏机。

当我们拿到手的手机，不管是苹果还是小米，都有可能是我们某个未曾谋面的中国小姑娘亲手将这台手机组装完成的。在2008年，一个叫做“iPhone女孩”的富士康打工小妹在一部iPhone手机里留下了自己的照片，通过网络就传遍了全球。虽然后来传闻说这是一次炒作的事件，但是我们都应该记住，我们每一部手机都是全球无数我们未曾谋面的人努力的工作，最后才完成了这样一部手机摆在我们的面前。所以还是希望大家能珍惜它，不要让你的手机成为伤害别人的东西。

最后我们再来总结一下：在现在全球一体化的浪潮中，必须要有开放的心态。只要是能为我所用，又何必管是哪国生产的呢？相比于抵制洋货，我们更需要的是抵制蠢货。比如说我们中国的政府就做出了很好的表率，像很多武警开的都是日本的丰田车，保卫的却是咱们中国人。
