---
title: "Linux传奇：Linus上大学"
editor: visual
---

Linus在中学毕业以后就去了赫尔辛基大学上两年。我说到芬兰教育的时候，有好心的朋友提醒我，芬兰的大学，包括赫尔辛基大学在内的一些学校，已经准备开始对非欧盟的学生收取学费了，免费的午餐，对中国的学生可能要结束了。在读大学期间，Linus做出了Linux操作系统。做一个操作系统，需要什么东西呢？第一，需要一台电脑。第二，需要足够的时间。这两点，Linus都具备。第一，他花了3000多美元买了一台电脑。第二，他在赫尔辛基大学里待了八年，反正在芬兰读大学是免费的。

我们来仔细说一说，这两点当然肯定不止这两点，还有第三点、第四点、第五点。比如Linux很聪明啊，非常有耐心啊，但是这些说起来都没有什么意思。所以只说前两点。在进入话题之前，我先说点题外话。我说这个故事都是来自Linus的自传，叫《只为了好玩》。如果大家喜欢看故事的话，就买一本书回来看看，肯定远远比听我在这里叨叨逼逼地说要强了很多。所以非常建议大家去购买这本书，名字叫做《只是为了好玩》。

上一期文章中我也说过了，我讲这个故事的目的是借Linux操作系统试图还原一下当时的历史场景。通过这个操作系统的故事来深入地谈编程语言和操作系统的进化，也就是我自己的一家之言。通过Linux这个故事，假在识货来讲一下编程语言和操作系统的历史。如果有人只是对Linux这个人感兴趣，对操作系统和编程语言根本一点兴趣都没有，那就直接买书。我这里故事都讲的比较简单，对操作系统和编程语言，还有当时的硬件讲的会比较详细一些。

我们现在先来谈一个问题，截止到今天，2016年8月13日，Linux的稳定版本可能是4.7版。大家猜一下这个稳定版的核心有多少行代码？我还是先公布答案吧，因为说起来这个数字非常吓人，是1700多万行代码。在Linux发布1.0版本的时候，代码行数是15万行左右。如果大家对1700万行没有什么概念的话，我们应该知道《红楼梦》这本书吧。这本书呢，总共有多少个汉字？是60万个汉字左右。也就是说呢，每一个《红楼梦》上的字就对应于30行代码。如果把字印的小一点的话，30行代码可以挤在一页A4纸上。如果要把Linux4.7版本的核心代码全部打印出来的话，大概需要25万张打印纸，也就正反面都印的话，也就是说得需要500多包打印纸。那么多，也就是500多包的话，搞不好一个五菱之光那种面包车，一车还拉不了。所以说呢，对大部分人来说，当然也包括我，这么多的代码公开了和不公开，其实没有什么区别，反正也看不懂。

这打印在纸上，一面包车都拉不完的代码，积累了前辈几十年的经验和一系列的理论成果。也就是智商一般的人呢，根本就是老虎吃天，无从下口。所以我这个公众号就试图从Linux最初买回电脑来慢慢的分析，主要是满足我自己的好奇心啊。其实这些事情我断断续续的做了好多年，从本科的时候，我一直就想知道，然后一直到研究生，后来一直在FreeBSD上做开发，我就买了一本书，叫《**Linux Core Kernel Commentary**》。这本书呢，我断断续续的读了好多年，从本科一直到研究生，一直到工作，一直没有舍得丢的书之一，也慢慢的积累了一点小的心得。

希望在以后的故事里，借助Linux发明Linux操作系统的故事，把操作系统是如何运转起来的，给讲清楚。大家可能会说我这个课堂上，在大学里我就学过操作系统啊，感觉也不怎么难。其实这句话是错了。如果你没有接触过操作系统的代码，就算看好几本教科书，也只是考试的时候可以用，但是它的原理都是对的。为什么这么说呢？就教科书上讲的内容省略了操作的细节。实际情况呢，当你就算你把0.01版、0.02版的Linux源代码拿出来的时候，还是不停的卡住。为什么这么说呢？因为教科书上都把那些东西都省略掉了，以至于省略到你只能了解最核心的部分，然后其他的代码你什么都不懂，然后就被不停的卡住，能卡到让我们怀疑人生。

我以后的故事呢，主要是参考这两本书，一个是Linux的自传《只是为了好玩》。另一本书就是这个我上面提到的这本书，叫《**Linux Core Kernel Commentary**》。如果微信公众号的话，可以看看这本书，我就把这本书的封面当了这一期节目的封面。更多的参考资料，也许就不一一列出更多的东西了。可能就是上学的时候为了考试，考完了试，然后经过了好多年，没有忘掉。

另外，因为我的工作曾经有一段时间，就是很大一部分程度，就是基于FreeBSD这个代码开发，增加或者删除一些功能，让这些代码跑在某种硬件上。主要是路由器，也算是开发一种操作系统，还是有很大的关系。虽然这个操作系统是没有桌面的，因为路由器嘛，不需要桌面。

现在让我们来看看当年的Linux在大学里买了台什么样的电脑。高中的时候，Linux有一台用了三年的电脑，呃，名字叫做Synn Clay。这台电脑呢，使用的是32位的CPU，运行的频率是八兆，内存是128K，不是128兆，是128K。现在128K只能存一张分辨率不怎么高的照片，就是非常小。操作系统呢，叫QDOS。当然了，这个QDOS和微软买的那个QDOS只是名字一样，实际其他的什么都不一样。当年这个QDOS比微软当年购买的那个QDOS要先进一些。这个QDOS呢，支持多任务处理程序。但是呢，这个操作系统安在这台电脑上是只读的，不能够对这个操作系统进行改变。也就是说，如果你当年有个病毒的话，即使有电脑病毒，也没有办法感染一个只读的操作系统。所以在这台系统上你是没有办法开发操作系统的，因为操作系统只读，你没有办法去替换它，又没有一个硬盘什么的。但是Linux还是通过这台电脑学会了很多的东西。比如说，他在他的自传里说，他给这台电脑的软盘驱动器写了一个驱动程序，因为他电脑自己的那个驱动程序有个bug。通过这台电脑，他还精通了汇编语言和反编译程序。

通过这些信息呢，我们可以大体的总结一下，Linux在高中的时候，一部分当前的市场上，一部分电脑已经开始进入了32位。各种各样的电脑都有，并不是只有IBM的PC。操作系统更是五花八门，也没有一个操作系统能像今天一样占有绝对的优势。像我们现在随便一开机，就是微软，或者很小部分是苹果，更小部分是Linux。当年的情况有点像史记中所说的，叫秦师齐路，天下共逐之的感觉，就是群雄并起，逐鹿中原。越是这种时候呢，就越容易出奇迹。等到你整个市场都稳定了，社会都稳定了，再想做出非常大的成就也就非常难了。比如说，如果时间不太合适的话，像朱元璋那种一代枭雄也只能去种个田呀，去养个猪什么的。

Linus的这台Synn Clay电脑呢，也就一直陪伴着他。刚开始的时候他还是比较讨厌IBM的个人电脑的。如果大家听过我说的指令集之争那一节的话就知道，因为英特尔在很长一段时间都不如摩托罗拉的芯片做得好。但是随着英特尔不停的进步，尤其是386出现以后，PC的魅力也就慢慢的出来了。

在前几期里有一期的名字叫《指令级之争》，就是讲英特尔的故事，希望大家去网易云音乐去找一找，听一听。我个人觉得很有趣，但是看收听量来说，可能大部分人觉得挺有趣的。

那个时候呢，Linux手头就比较紧，但是他一直想买一台有386处理器的电脑，然后他上面装一个Unix来玩玩。因为在下学期，当时还在大一，等到大二的时候，他下学期就会有操作系统这门课。因此，在大一到大二那个假期里，Linux就把一本719页的书《操作系统设计与实现》读了好几遍。他早就迫不及待的想学习传闻已久的Unix操作系统。在这里再宣传一下我的微信公众号“软件那些事”。我在这个公众号里连续做了五期Unix操作系统的故事。当然了，不出意外的就是阅读量和收听量也就越做越下滑，我就赶紧的把它收尾了。

Linux在他的自传里说，他最迫不及待的一门课叫C语言和Unix。当年的Linux也是Unix新手，但是他一碰到Unix就爱上了它，而且至今也没有改变，而且越来越喜欢了。我再重复一下我前五期的故事，讲Unix的故事的内容就有点多余。但是我还是简约的说一下，Unix为什么好呢？就当时来说，Unix有进程和管道的概念，后来他创造的Linux也完全支持进程和管道的概念。而且Unix设计非常的简单，完全有6个叫系统调用的操作来构建整个操作系统。因为这6个系统调用真的是非常的重要，我就再重复一下这6个概念。

毕竟听过我那五期Unix故事的人应该是非常的少。第一个叫做创建子进程，就是fork。第2个就是执行，就是刚创建的那个进程再执行另一个进程。另外就是关于4个文件操作的，分别是打开、关闭、读取和写入。这6个操作，构成了Unix的主体结构。如果再仔细讲的话，可能还有很多其他的系统调用。比如说，Unix第一个版本里就有23个系统调用，但是呢，我在这里就不展开了，属于抓大放小，抓住最主要的这6个系统调用就能明白Unix或者Linux。

如果你在Unix或者Linux创建更复杂的任务，不需要再调用更复杂的接口，只需要配合进程以及管道就能创建非常复杂的任务。关于管道这个概念，还有系统调用概念，我在之前做的那五期Unix故事里已经有比较详细的介绍了，这里就不多说了，否则一是重复，二是时间也不够用。

Linux呢，还是在继续攒钱购买386CPU的电脑。终于，在他21岁生日的时候，他就凑够了1000来美元。为什么在21岁生日的时候呢？我们知道，首先过年的时候他能赚一些钱，而且他的生日也非常的靠近过年。因此，这段时间他是比较有钱的，能拿两份钱。但是，他也只有1000来美金，而当时购买一台386，需要的钱大概是3500美金。幸好呢，那家店里是可以分期付款的，因此他就先付了1/3的钱，赊账就是2/3，而且那2/3要在三年内还清就行了。后来，其实他没有用他的钱还清，是大家集资给他把这个电脑钱给还了。

当时，Linux就选了一台白色的兼容机，CPU是33兆赫兹，内存选了四兆。选好整个配置以后，店主说三天后你可以去取货。Linux就觉得那个三天就像是一个星期，那么漫长。等到三天一到，他就喊上他老爸开车把那个大家伙取回来。

大家还记得他老爸吗？其实那个狂热的共产主义者，苏联人，家里还经常挂镰刀斧头的党旗。我就觉得他的老爸跟老妈真的是有点不合群。但在西方社会，他们也离婚了，每个家里还挂着一个党旗，都是共产党员，在画面上非常不和谐。

这台电脑呢，还附送了一个微软的DOS操作系统，但是Linux当时就购买了另一个操作系统，叫Minix。后来他和Minix操作系统的作者在网上吵了一架，再说这个故事。那个169美元的操作系统不算太贵，但是呢，你要花一个月的时间从国外寄过来，买这个操作系统当时也算是海淘，搞得Linux非常不爽。

首先呢，价格非常的贵，169美元。其次呢，快递非常的慢，要30天才到。在这个漫长的30天里，Linux就在DOS下玩那个“波斯王子”的游戏，要不就看那本操作系统的书。

他就在一个周五的下午，Minix操作系统终于到货了，整整16张软盘，他就装上了Minix。玩了一段时间以后，他觉得这个操作系统玩得还是挺不爽的，不如学校的Unix玩得过瘾。他当时就想写一个终端仿真程序，也就是我们现在常用的Terminal，或者是Windows下常用的Putty，能用SSH或者Telnet的一个程序。

他想用这个终端仿真程序连接到学校的Unix上用学校的Unix机器来玩。因为他现在这台电脑上，他倒是还不喜欢Minix，也不喜欢DOS。而且，Linux当时想不借助任何操作系统，直接就写一个仿真程序，也就是在软盘上，你一启动起来就是这个仿真程序，然后连到学校机器上，就在硬件上直接启动这台电脑。

如果有朋友看到这里还没有退出的话，我还是希望大家考虑一个问题，就是给了你一些硬件，但是没有操作系统，你如何把这个电脑启动起来？这个事情以前我也做过一期节目，叫《电脑开机开了啥》，里面详细介绍了电脑启动的流程。如果有好奇宝宝的话，可以去找那个文章来看看。我里面就是详细讲了，你这个电源一开机之后，一直到操作系统加载，都是做了些什么事情。

但在下一期呢，我就想讲一讲如何让一台电脑连操作系统都没有的情况下，亲手做一个系统，让电脑运行起来。有同学可能会问，哎，为什么你讲着Linux的故事，讲着讲着就成编程了？上一期我已经说了，我这个就是借助Linux的故事，抒发自己的一家之言。

我们可以考虑，呃，听这个文章或者看这个文章，就相当于是玩一个RPG游戏，就是角色扮演游戏。我们现在就是扮演那个21岁的Linus，所掌握的知识有：高中三年玩一台叫“森可莱”的电脑，熟练地掌握了汇编语言。现在呢，贷款买了一台电脑，386的处理器，主频是33兆，内存是四兆，电脑还有个软驱。作为Linux的我们，现在已经受够了电脑自己带的DOS，也不喜欢我花了169美金买回来的Minix系统。我现在就想插上软盘，然后启动一个终端仿真程序，连到学校里去，爽一爽。我们应该怎么做？

因此，在下一篇文章里，我们将和大家一起讨论如何让一台什么都没装的裸机运行起来。嗯，可能，我讲的和当年21岁的Linux写的不一样，但是呢，当年他肯定也要用到类似的代码。因为从这个BIOS里面启动电脑没有什么技巧的，也没有什么机密，都得这么写。不管你是Linux还是微软，还是我们，还是当年的Linux，都得这么写，你就是要遵从BIOS的规定。

如果有人对电脑启动有疑问的话，可以真的去找我以前看的一篇阅读量依然很低的文章，叫《钻牛角尖：电脑启动启动了啥？》。里面我就讲了这个BIOS的整个启动的流程应该是什么。

其实，让一台电脑启动起来只干一点点事情的话，比如说我只是让屏幕上显示一行“Hello World”，真的非常简单。因为下次要讲操作系统的一些原理，希望像Unix的话，我每多做一期Unix的节目，整个的阅读量就下降13%。希望我这个下降个5%或者10%就好。

另外呢，大家也真的不用对技术原理感到难堪。我觉得吧，我们这个系列的文章就是我们试图扮演Linux这个角色，游戏嘛，这顶多讲到Unix最基础的6个系统调用为止。

我读书的时候实现过一个玩具类的操作系统，根本就不需要多少代码就可以实现一个有操作系统概念的东西。你可以实现那六种调用、进程之间的通讯，都可以实现，没有多少代码，只是不健壮。呃，我还是个人非常喜欢有人能够陪伴我们把这个RPG游戏给玩下去嘛。

根据Linux的自传，一边我们看他做了什么，一边试图还原他开发一个操作系统的过程。当年我读书的时候，折腾过不少关于操作系统的东西。现在呢，我在FreeBSD系统上工作了好多年，自己的工作呢，也算是和操作系统开发有不少关系吧。只是我参与开发的这个操作系统是运行在路由器上，但也算是操作系统。路由器的操作系统就是没有桌面环境，我觉得应该能讲清楚这本自传里的技术。

参考的书呢，就是上面我说的那本书，也是微信公众号的那个封面那本书，叫《Linux内核设计与实现》。就这本书啊，毕竟我们是实现一个玩具类的操作系统，而不是那个1700万行的操作系统。那个我估计没法讲。

另外呢，再回答好奇宝宝在公众号的那个微信里面就问我啊，你收到多少赞赏钱了？其实我就通知一下吧。截止8月13日晚上21:15，总共收到了62.2元。嗯，这个公众号呢，我其实总共写了36篇文章。如果你这样粗略算一下的话，就平均每篇文章的收入是一块七毛三嘛。今天收入是最多的一天，所以我就恭喜一下自己。13块钱分别是藏码饭、没有雄心和exd这三位朋友赞赏的，非常感谢你们。

当然了，我感谢所有收听的，不管是捧人场还是捧钱场的。但最后我还是希望大家给我一点反馈，我真的很希望微信公众号的文章，不光有赞还要有钱。这样呢，我就知道我这个文章到底有几个人喜欢、几个人不喜欢。这样，我也能把握住整个的难易程度。

最后呢，欢迎大家留言。下次就到这里，在我们讲操作系统的时候再见。
