---
title: "Linux传奇：书呆子的中学生涯"
editor: visual
---

在上个世纪八十年代，对我来说意味着非常多的东西。在生命中最重要的两件事情都是发生在上个世纪八十年代。第一件事情就是我老婆出生了，第二件事情就是我也出生了。

除了这两件事情以外，在IT行业也发生了非常多的事情。简单来说，在八十年代，电脑逐渐地从高不可攀的大型机，慢慢地向个人电脑的方向发展。而且这个趋势至今也没有改变，今天电脑已经装进了每个人的口袋里，就是我们的手机。

举几个简单的例子，在1980年的十月，IBM公司决定推出基于英特尔8086芯片的个人电脑。也就是在同一年，比尔·盖茨——微软的比尔·盖茨敏锐地嗅到了个人电脑的商机，出资2.5万美元购买了SCP公司的QDOS操作系统，并将这个操作系统授权给IBM使用。次年，微软耗资五到七万美元，就把QDOS完全地买断，并且雇佣了QDOS的作者Tim Patterson。QDOS在1981年7月27日正式改名为MS-DOS。当时SCP公司以为就这么个破软件，竟然赚了10万美金。他们都以为盖茨是个人傻钱多的大款，个人电脑的普及浪潮势不可挡。

我们可以稍微提一下中国当年的情况。当年改革开放刚刚开始，个人电脑的普及肯定是没有的，反倒是持续了二十五年的知识青年下乡的运动被终结，大量的知识青年陆续地还乡，还乡以后就马上失业，失业以后就非常容易造成治安事件。在八十年代的初期，很多地方的女青年夜晚都不敢出门。为了保障广大劳动人民群众的利益，伟大光荣正确的党在1983年7月19日开始严打，这场严打持续了三年多，这是人民民主专政的一段纪念碑式的历史。

现在我们都知道，如果你判一个人死刑的话，审核权是属于最高人民法院。当年的死刑是属于县法院，也就是说，县长以及同级别的党委同志就可以决定一个人的生死。结果在一九八四年一年就执行了24000多个死刑。其中有一个小伙亲了一口姑娘，就以流氓罪判死刑。那一年，一年就劳改了100多万人。这100多万中有不少是非法同居的人，属于没有驾照乱开车、无证驾驶的典型，因此得严打破坏风俗，一抓也就抓俩，极大地维护了人民群众的利益。

说实在的，要是以一九八四年的标准严格执法，现在的大学生能毕业的顶多有1/5，其中3/5得去劳教，还剩下1/5，拉出去就得枪毙。所以说呢，以现在的眼光来看，单身狗如果生活在一九八四年的大学校园里，应该是当年优胜劣汰的幸存者，非常安全，肯定能毕业。

在中国当时那种情况下，个人电脑的普及并没有那么急迫。所以呢，在八十年代的中国，普及个人电脑并不是什么大事。所以呢，中国当年没有出现Linux、比尔·盖茨这种人也算是情有可原。而同年代的Linus则开始上中学了，是在赫尔辛基最好的一所中学读书，这所中学的名字叫诺森高中。我在网上搜到了这所中学的网址，就放在我的微信公众号“软件那些事儿”里面，这个网址非常长。另外呢，我还用谷歌街景浏览了一下这个学校，放了一张这个学校的照片，非常漂亮，才是真正的北欧风格的学校。

据Linus在他自传里的描述，他自己本人就是个书呆子。满分数10分的话，他的数学、物理、生物等大多数科目都能拿到9分或者10分。体育呢，也就是个及格分6分或者7分，木工课呢是6分。他说别人木工课都制作了精美的凳子、桌子什么的，结果他唯一得到的就是至今还留在他大拇指里的几根木刺。另外他还特别的强调，他院子里的那个精致的秋千是他岳父做的，和他没什么关系。只要上体育课的时候，有一个小时的休息时间，他就去咖啡馆里泡着消磨时间。

看到这个消息以后，我就赶紧打开了谷歌街景服务，试图找出他说的那个小咖啡馆。结果呢，那个小咖啡馆是允许学生赊账的，结果我找来找去也没有找到，看来这个谷歌的街景服务还是有很多的死角。

Linus说呢，当时他就非常的注意饮食的健康，去了就点一模一样的东西，健康饮食，一杯可乐，外加一个甜甜圈。而且在那本自传里，Linus还说，当时有好几个女孩喜欢去他家，主动让他辅导数学课程。Linus本人还嫌比较麻烦，因为芬兰有个不用证明就肯定正确的定理，就是鼻子大的男人某些部位也比较大，而且这些找他辅导数学的女孩子还经常不务正业，除了数学还想聊点别的，甚至有个别的女生更过分，对Linus动手动脚的。所有的这些事呢，让Linus本人非常的讨厌，本来就是辅导数学，又不是辅导体育，别动手动脚的，好不好？

在书里呢，Linus不无遗憾地说，除了是个书呆子，我还非常的腼腆。你说我这样的人是不是很多余，所以我还是宁愿坐在电脑前面，只有这样，我才能感到无比的快乐。

我在写这个公众号的时候，基本上想到什么就写什么，属于意识流，因为关注的人实在是太少。我就再多扯一点。

在很多年以后的二零一三年，也就是大前年，在当时——在二零一三年的时候，Linux早就已经功成名就。这个时候呢，内核开发虽然是男性居多，但是也有几个女性。比如说英特尔的一个开发者名字叫做Sara Sharp。这个名字呢和Linus的妹妹是重名，翻译成中文都叫莎拉。这个女孩长得还行吧，我就在一公众号里放一张她的照片，大家给心里打个分，我觉得还行，是个金发女。

这个内核开发者呢，觉得邮件列表里的脏话太多了，就提议说少说点脏话，结果就把Linus给惹怒了，连这个女开发者也给骂了。最后Sara Sharp这个女孩就退出了内核开发组，就是属于Linus把人给骂跑了。网上就开始有人指责Linus不对，也有人说Linus做的非常的好。

如果我们看看Linus年轻的时候，在辅导数学功课的时候，还嫌人家女生对他动手动脚的，也就能理解这件事情了。所以呢，对于这种牛人，我一般认为他们首先是牛，其次才是人。

关于Linux的中学时代的故事就讲到这里。总结来说，Linux中学时代就是一个不折不扣的，甚至有点不解风情的书呆子。在计算机和通信行业，书呆子经常能够做出巨大的成绩。比如说本文的主角Linus，还有《历史普》的作者约翰·麦卡锡，还有诺伯特·维纳等等。这些人呢，每一个人都是不折不扣的书呆子。有时候我就想，在计算机行业被人称之为书呆子，起码应该算是个中性词吧。如果不算褒义词的话，在本文的最后我再谈一下我对我这个公众号的定位。

因为我每周都会公布上一周的数据统计，我这个公众号的关注者非常的少，阅读量也非常的低。已经都让我不好意思跟朋友说，我还在做写公众号的文章。这两天好说歹说让知道我公众号的几个人都一一地退订了，有死活不肯退订的几个已经被我拉到黑名单了。这样一来呢，我就开始完全按照我自己的兴趣来写文章。我打算这次以写Linux操作系统的故事为主线，深入的分析一下整个编程语言和操作系统的进化，以及在当时整个计算机行业大环境应该是什么样子。

我本人非常相信中国的一句古话叫“时势造英雄”。如果时间不对，比如说没有赶上计算机由大型机转向个人电脑的趋势，那Linux很可能会成为一个数学系教授，像他的外公一样。如果时间都正确了，但是周围的环境又不对，比如说本文我前面所说的，虽然出现在正确的时间，恰好赶上中国的严打，当时社会中又没有计算机，一个技术天才很有可能因为流氓罪被劳改了。

我打算呢，把整个系列的文章由单纯的讲述一个故事，变成这种单纯记录故事的风格。我本人并不喜欢，有点像《汉书》一样。《汉书》是集体创作，是以班固为首的统治领导集体创作小组，歌颂汉朝的英明领导，因为很容易就造成崇拜某些天降伟人的皇帝，而且故事本身也非常多的漏洞。班固在《汉书·叙传》里也说了，这本书主要是为了让后世知道汉朝是多么的英明。书里的原话是“扬名于后世，冠德于百王”，《汉书》也算是后世官方记录的鼻祖。后来每个朝代都基本上都会出一本断代史，反正萝卜白菜各有所爱嘛。

如果有人喜欢看《汉书》风格的话，可以去找最新最近出版的党史来读一下，一样的配方，一样的味道，已经流传了2000多年。我本人非常喜欢读的历史书是《史记》。可能我们整个的教学有一点小小的误导，《史记》并不是大部分人认为的是历史书，如果按照历史书该如何客观记录历史的标准来评价，《史记》就有点强人所难。《史记》本身就是司马迁个人的记录。在《太史公自序》这一章里，司马迁也说了，司马迁是借历史为手段，抒发一家之言。

所以我这一系列的长文也打算学习司马迁，借IT界发生的故事，抒发我自己的一家之言，主要是打算给自己留个纪念吧。如果运气好的话，我两个小孩长大以后，很多年以后，可以听听他老爸当年年轻时候的想法。

我这个公众号里主要是为自由去呐喊。在IT界，虽然每天都会有各种各样的恶心事情发生，比如说有些人就专注于让其他人怎么不能好好的上网。但是呢，我相信自由的力量终究会战胜不自由的力量，开放的力量终究会战胜封闭的力量，就像是开放的Linux，终究会战胜一些闭源的力量一样。

最后呢，我再回答一个问题，有热心的朋友问我，为什么你一天写一篇出来？其实呢，这都是我记录的最近十年中的日记中挑出来的素材。我从上高中开始就每天写几句话的日记，借助我写的这些日记中的素材，很快就能弄完一篇。

最后呢，我附上一张我最近五年日记本的照片作为纪念。
