---
title: "转给安卓手机用户，自有土地上开出的罪恶之花"
editor: visual
---

谷歌斥资收购安卓团队以后，安卓团队成了谷歌公司的异类，就像是香港回归中国以后，中国实行的一国两制。从某种意义上来说，安卓团队成了谷歌的法外之地，忠诚和背叛、赞美和诋毁、自由和专制并存。随着安卓在谷歌里成长，最终安卓这个谷歌里的异类成长为一朵娇艳的罪恶之花。

故事回到2007年，那个时候，诺基亚如日中天，黑莓手机蓬勃发展，微软的Windows Mobile手机也占有一席之地。没有人在乎苹果公司，更没有人注意到安卓团队。安卓和苹果就像是站在人群中的刘邦和项羽，而诺基亚正如威风八面的秦始皇。刘邦看到秦始皇以后，说“大丈夫当如是”；项羽看到秦始皇以后，说“我可以取而代之”。太史公在《史记》中写道：“天下已定，始皇之心，自以为关中之固，金城千里，子孙帝王万世之业也。”也许当年的诺基亚就是这个感觉。

可是，谁想到，空前强大的秦国，被西楚霸王在巨鹿之战中一战灭国。苹果就是项羽，用一款手机斩木为兵，揭竿而起，在天下智能手机的云集响应下灭掉了诺基亚。苹果是项羽，但安卓就是刘邦，与之神勇，千古无二，善用天下之士。这就是刘邦、苹果和安卓之间的盖下之战，到底谁赢谁输呢？这个我们只能等未来来给我们答案了。

在2006年的六月，微软和谷歌为了一个人剑拔弩张，不惜诉诸法庭。这个人就是当年三十七岁的甘多特拉。他整个职业生涯都在为微软工作，是比尔·盖茨和鲍尔默的得力干将。在微软的时候，甘多特拉多次提议微软进入手机领域，但是他三番五次的建议都被束之高阁。于是他心灰意冷，准备离开。为了阻止他离开，微软对他发起了诉讼，说会执行为期一年的竞业禁止协议。谷歌并不在乎，给甘多特拉支付了一年的薪水，让他满世界的去游山玩水，一年之后再来谷歌上班。

到了2007年的六月，甘多特拉来到了谷歌。甘多特拉行事高调，性格刚强，演讲极富攻击性和煽动性。在微软工作期间，凭借他出色的煽动力，微软和开发者建立了良好的关系。只是现在他要为谷歌工作了。他的到来让一贯自由散漫、极富创新的谷歌的员工感受到了巨大的压力。他如龙卷风一样狂暴且肆虐，他要求所有的手机项目都必须有商业计划，如果没有盈利的前景，项目马上取消。这让一贯先推广产品再谈盈利的谷歌员工有些无所适从。

他制定了谷歌的手机计划，就是和所有的厂商都保持良好的关系，不管这款手机是诺基亚、是黑莓还是微软，甚至是弱小的iPhone，都能很好地运行谷歌的服务。只要影响到合作伙伴，任何的障碍都必须铲除。如同伟大的巴顿将军，在诺曼底登陆以后，为了能全速推进，他不惜偷窃其他美国军队的汽油。为了达到目的，疯狂的英雄是不分敌我的。这里的甘多特拉和巴顿将军是一样的人物，为了达到目标，谷歌内部的障碍他也从不手下留情。

由于他要和所有的厂商都搞好关系，谷歌内部有自己的安卓团队，成了他自己的眼中钉、肉中刺。因为其他的手机厂商绝对不想谷歌有个手机系统和自己的去竞争。这个人在公司的第一目标，就是亲手把安卓团队给拆散，让这个手机项目停止。

在2005年安卓被收购以后，安卓整个团队行事低调。在其他开放的谷歌人眼里，安卓团队就像瘟疫一样，早晚会毁掉谷歌自由的文化。因为谷歌其他的源代码都是可以随意被访问的，但是安卓在这里是一个例外。除了神秘的安卓团队，没有人知道他们在干什么。被收购以后的安卓就像是谷歌公司金屋藏娇的情妇，谷歌给了他无数的钱、无数的礼物，但是永远都要保持神神秘秘。

安卓项目的负责人仍然是安迪·鲁宾，另一个强人，甚至有些变态的控制狂，他控制了整个安卓的团队。该团队不和其他的谷歌人打交道，他们有自己的办公室，他们也不和其他团队的人互动，也不和其他团队的人用餐。安卓完全是单打独斗，当有人，甚至是谷歌的高层，想要查看安卓的进度时，安迪·鲁宾也是一口拒绝。他是谷歌公司最坏的那个人，安卓团队在谷歌里是没有朋友，只有敌人。

当甘多特拉试图要取消安卓项目的时候，我们可以想象到安迪·鲁宾是如何的气愤，他是誓死捍卫安卓团队的那个人。当项目有延迟的时候，安迪·鲁宾也会勃然大怒，他会把整个团队喊过来骂：“如果项目到期了，你们还他妈的做不完，就全都滚蛋！我会雇佣一个能干的人来代替你们这些废物！”安迪·鲁宾的愤怒击退了甘多特拉试图解散安卓的企图，但是这让其他谷歌员工对安卓团队更加的敌视。

虽然说安卓团队万事不求人，但是到了具体功能的时候，他们也需要其他团队的协助。安卓早期的员工萨德沃尔回忆说，当安卓系统需要email团队的支持，说他们要在安卓手机上运行Gmail邮件时，他就找到Gmail团队寻求帮助。但Gmail团队的人告诉他：“我们Gmail团队已经制定了一个为期两年的软件开发计划，在两年之内，安卓都不在考虑之内，所以不好意思，两年之后再来找我们吧。”同样的事情也发生在GTalk团队、谷歌地图团队、谷歌日历团队，没有人去帮助安卓团队，这是当初冷漠的代价，这也是他们这些团队热情的拒绝。

媒体都在猜，谷歌就要出操作系统了。因为当时世界上最顶级的手机系统开发者之一安迪·鲁宾在谷歌工作，如果他不是在开发手机操作系统，难道他会在谷歌当门卫吗？铺天盖地的猜疑，谷歌发言人外交部一样的官方拒绝让谷歌其他团队对安卓更加讨厌。因为谷歌以透明自由著称，他们怎么能够忍受在谷歌内部有一个黑箱团队的存在？

甘多特拉的工作之一就是和苹果打交道，几乎所有时候苹果公司获得谷歌的支持，都比安卓团队获得的多。毕竟甘多特拉和安迪·鲁宾之间有深深的裂痕，这个裂痕一直要等到安卓系统大获全胜，一直要到安迪·鲁宾离开了谷歌，才能被渐渐地弥补。

在2007年11月5日，安卓系统终于揭开了它神秘的面纱。安迪·鲁宾的事迹也登上了各大媒体的首页。终于，安卓和苹果的裂痕公开化，谷歌也不再矢口否认自己在开发手机操作系统，两个公司的战争也开始逐渐升级。

安卓就是这样在谷歌这个自由、多元、透明的公司里，凭借安迪·鲁宾强大的意志力，在谷歌里建立了一个专制、单一、暗箱操作的团队。安卓团队就是谷歌的一国两制，安卓团队几乎打破了谷歌公司任何的规则，他们不和人合作，他们也不公开。他们的老板是个暴君，最后安卓还是开出了一朵娇艳的罪恶之花。如今，这个曾经被谷歌人视为罪恶的花朵已经开遍了全球。
