---
title: "自由引导自由软件"
editor: visual
---

Linux和自由软件取得的巨大成功已经无需多言，我们的生活中已经完全离不开自由软件了。毫不夸张地说，有电子设备的地方，就会有自由软件。

作为我个人的兴趣爱好，我特别喜欢研究历史。这个系列呢，我写了十几篇关于Unix和Linux的历史，这只是我历史业余爱好中的一部分。因为我是程序员，自然也就对科技的历史和电脑的历史多关注了几眼，分享这些年来看历史的一些我个人的观点。

先说一下结论，我再去论证我的结论。就是说，人类历史的进步，是一批天生聪明、精力旺盛、热衷于折腾的精英分子来推动的。这些人带动人类从奴役走向自由，这批精英分子中，当然也包括了Linux的作者。Linux操作系统是个人的胜利，更是自由的胜利。在将来，这种个人的自由的胜利将会越来越多。

我觉得中国有个词非常的好，就是“学生”，包括中学生、小学生或者大学生。里面这个“学”和“生”这两个字实在是太有内涵了。“学”自然就是学习的意思，“生”呢，自然也就是生活、生存。学生，学着生存下去，而不是学死。生活下去，很多人学着学着就自杀了，或者是碰到个小挫折，然后跳楼了。比如说我们总是在网上看到有的人失恋了，就跳楼自杀了。但我个人来说，我至今为止最瞧不起的人就是因为失恋而自杀，或者和导师闹了矛盾而自杀的。你说你上个学大不了退学，根本就犯不上跳楼自杀。所有的这些呢，我都认为他是一个不合格的学生，这属于“学死了”，而不是“学生”。

为什么我喜欢看历史呢？难道仅仅是为了喝酒以后在酒桌上炫耀一下吗？当然，这个炫耀也是非常重要的一部分。但是更重要的是从中学到一点东西。为什么这么说呢？比如说当我们在学习秦始皇，你说有没有用处？我们如果知道秦始皇是不是吕不韦的儿子，这种事情的用处其实是并不大的。或者说就在我写的这十几篇Unix或者Linux系列中，如果我们仅仅是知道Unix创始人哪一年去参加了哪个大学的哪个会议，实际上是没有什么用处的。

如果仅仅知道这些，即使你知道了真相也用处不大。比如说今天我们如果挖到了秦始皇的骨头，也挖到了吕不韦的骨头，而且上面还有真的DNA。我们给他做一个亲子鉴定，然后就可以得出完全准确的答案，也不用猜。我们就知道这个秦始皇的老爸是不是吕不韦。但是这种事情呢，也只适合在酒桌上去谈一下，这种故事本身是没有什么用处的。

那为什么我还会费劲巴拉地去写了这40多篇IT历史的故事呢？来讲这种八卦，况且还没有几个人来听，也没有几个人来看。因为我觉得这可以帮助我思考，这最重要的一点，比如说我可能永远都没有机会去开一个公司，或者说写一个像Linux那么成功的操作系统。我想这个世界上其实绝大部分的程序员都没有机会写出一个如此成功的操作系统。

但是通过历史故事，我们可以想象一下，如果碰到这种情况，我们该怎么办？如果我们是Linux的作者，又该怎么做？就像玩一个RPG游戏，通过故事也能够来完善自我。不只是这个故事，其实在任何可能的时候，我都会设身处地地考虑一下，如果我碰到了这种情况，应该怎么做？因为有些情况我们可能永远没有机会会碰到，或者是你碰到这种情况，代价又太大。

比如说当我看到有车祸的新闻，我就点进去看一看，而不是仅仅为了好奇，而是想体验一下。如果当时我在开车应该怎么处理。比如说前几年汶川地震的时候，有一个叫范美中的老师就吓跑了，而且他也没有通知学生，就这样自己跑了。我肯定是没有去网上骂他。我当时就想，如果我碰到这种情况，我会不会吓跑。后来我还是思考了很久。我觉得我当时会有两种可能，一个就是和他一样，撒腿就跑；第二种情况就是可能就是真是吓傻了，因为砖块什么的不停地掉下来，可能已经无法逃跑了。

所以有时候我们仅仅是评论别人的是是非非是很简单的，但是自己做事情是非常难的。如果你要把一件事情又做成功了，那就更是难上加难。有的时候代价实在是太大。比如说碰到地震，我们才知道自己到底是个大英雄，还是个卑鄙小人，这种代价实在是太大了。希望大家都不要有机会来考验自己，考验人性。而且这个人性这东西，大部分人都是经不住考验的。

我在写这些IT故事的时候，也是这个目的，就是想一下，如果我们在当时就处在那个位置上，我们应该会怎么做？所以呢，接下来我们还是谈谈历史吧。人类呢，是从猿猴进化来的。如果进化论是正确的话，为了生存下去呢，人类首先记住的其实并不是善良啊，而是仇恨。

就在前几年，大概是十年前左右吧，在一个叫巴布亚新几内亚的岛上，发现了一群还处在石器时代的这些人。这些石器时代的人呢，会有很多个部落，和我们今天都差不多的样子。嗯，他们人长得跟我们今天的人差不多的样子，区别就是这个岛与世隔绝。巴布亚新几内亚岛上有很多岛，都是与世隔绝的。有兴趣的话可以大家搜搜这样一篇文章，叫《最后的石器时代》，还是我忘了。BBC还是国家地理，也有一个纪录片，就是讲这个事。看模样呢，跟我们是一模一样的。

但是这些人就是几千年来都是没有任何进化，还是用石头、木头，还有钻木取火这种东西。而且婴儿死亡率极高，人活到30岁左右也就去世了，而且也没有什么抗生素。你只要受感染了，很可能就死了。穿的衣服也相当于没怎么穿衣服。而且这个东西跟我们史记中记录的也差不多，就食盐这种的。我们吃的食盐是一种重要的战略物资，而且他们还有独特的提取食盐的方法。反正不是从海里晒，是通过烧一种植物，然后再把那种植物泡水，最后做出食盐来，是一种非常重要的战略物资。

其实到今天，包括现在我们今天食盐还是重要的敛财的一种工具。何况这个石器时代的这个部落呢，部落和部落之间也会为了争夺食盐去打仗。而且他们人还都是处于石器时代嘛，还都是比较野蛮。就是一打输了的话呢，就把人的头割下来，有的人就是可能就烤着吃了。很可能在我们石器时代的祖先也是这个样子，我觉得非常有可能。因为这些人30来岁就死掉了，基本上你也记不住什么东西。但他们也不学习，就是靠口口相传。

最记住最重要的东西就是仇恨，就是对其他部落的一些仇恨。如果你生下小孩来，因为小孩死亡率非常的高。如果你生下来，他们都是半年以上，或者是一年才会给他起一个名字。因为小孩很可能就在这段时间就去世了。即使小孩侥幸生存下来的话呢，他们就会每天告诉他哪个部落杀了咱们多少人，抢了多少食盐啊。然后这些孩子长大了呢，就是去打架，赢了呢，你就来割人家的头，输了就是头被人家割下来。就是靠仇恨，然后聚集了一个又一个的部落。所以仇恨才是凝聚力。

所以，包括我们已经进化了2000年或者几千年的现代人来说，对很多国家至今还是这样。为了有这个凝聚力，其实跟这些部落差不多，就是仇恨教育。所以呢，有时候我就认为仇恨是本能，报仇也是本能。反而你这个爱和宽容是另一个更高层次的东西。所以有时候我就觉得《三字经》应该改一改，应该改成人之初性本恶。

在石器时代的时候呢，如果你想活下去，肯定就只能抱团取暖。因为你一旦离开了某个圈子，尤其离开你的部落，非常的危险。一旦出了你的部落，到了其他的一个部落，就基本上没有活命的机会。非常有可能的是，在这个石器时代的人，因为你到处都是仇恨嘛，跟哪个人除了自己部落里，其他的部落都是仇恨。

这个国家为什么几千年来没有变化呢？因为它是远离大陆的，在太平洋中间，在亚洲和澳大利亚之间的一个国家。整个国家有350万人，但是有特别多的山，而且特别多的岛，非常原生态。所以现代包括今天，我们就不去打扰那些部落的，就是原住民嘛。他们现在还是这样生活的，就靠石器时代的方式在这样生活，没有人去打扰他们。

我之所以这样讲一个好像八竿子打不着的故事呢，就是为了说古代的时候，其实是没有什么个人自由的。在没有自由的情况下，你还活不到30岁。如果有自由的话，真是有可能三岁都活不到。因为你到处乱跑的话，三岁都活不到。所以说呢，在石器时代的时候，人类也就没有这个自由和个人的概念。因为你一想自由，一想到个人，哎，然后不小心跑出去，然后到了其他部落，你就被人有可能就当烧烤烤着吃了，是吗？

再后来，就是在2000年前的时候吧，我就只想谈谈西方，谈谈Linux。因为毕竟是西方出来的，包括很多的开源软件、自由软件都是西方出来的。而且不可否认的是，近几百年来几乎所有的好东西，就我们今天日常用的电脑、电话，什么都是西方造出来的。所以呢，我只是说一说西方啊，这个故事只讲西方不讲东方。东方的故事有很多讲的嘛，比如说你可以去看新闻联播，天天讲东方的故事。

在这里呢，我也只是说我的一家之言，也就是我自己的一个偏见。我说西方也只是说个人和自由的发展以及自由化、多元化，对创新是多么的重要。

在2000年前吧，就出了一个非常厉害的人，他开办了一个公司，至今这个公司也还没有倒闭，而且做得越来越红火。这家公司的创始人呢，就叫耶稣，公司的名字呢，叫基督教。这家公司在2000年至今还没有上市，已经存在了2000年了。主要是呢，没有哪个交易所敢搞这个IPO嘛。

如果有人听说自己是基督徒的话，也不用紧张，也不要和我争论。首先呢，我对黑基督教也没有资本是吧？我也没有能力去黑基督教。我想表达的意思是，基督教其实是人类的一次伟大的进步，就是让人类从群体走向个体，其中非常重要的一环，发挥了非常大的正面作用。

接下来我就来论证一下我这个观点。在基督教之前呢，我们前面也说了，在人类的宗教上，其实在基督教之前是有一个其他的教，名字叫希伯来教。那希伯来教之前是什么教呢？肯定也是有的，有各种各样的教，也许是什么观音菩萨、齐天大圣或者玉皇大帝、弼马温上，这个我们就不细讲了。但是希伯来教肯定不是第一个。

如果有人像我一样，不是基督徒，但是出于好奇也去读圣经的话，你就会发现一个问题。但虔诚的基督徒是回避这个问题的，只有不虔诚的基督徒你才能不停地提问题。就是圣经呢，它分为新约和旧约。简单来说，新约和旧约的关系其实是敌我矛盾之间的关系。旧约说的是希伯来教，新约说的是基督教。

刚刚我也说了，基督教之前就是希伯来教，它曾经很红火。希伯来教的创始人叫摩西。如果你看美剧或者电影，应该听说过“摩西十诫”这个词吧，就是十条戒律。如果没有听说过“摩西十诫”这个词的话，肯定是听说过猪八戒，八戒也是八条戒律，然后八戒比十诫肯定是少两戒，但它是“摩西十诫”，不是“摩西十界”。咱们中国这边有个很出名的人物叫猪八戒，意思其实差不多，就是十条你必须要遵守的规则，必须要遵守。和我们伟大的红军当年的“三大纪律八项注意”差不多。

在摩西的世界里呢，最重要的就是第一条：你不能信其他的神，你必须只能信我。就是说，如果你们信其他的神，就最好是赶紧把你们信的那些观音菩萨、玉皇大帝、齐天大圣或者天蓬元帅什么的都扔掉。赶紧信我这个，这个人就是非常的……你也可以说就是执行力非常强或者心狠手辣。如果他发现有人信其他的神了，就把整个部落杀掉。教徒嘛，不杀留着也没什么用。最后，他就建立了一个一神教，就一种思想，所有的部落都只能围绕在以摩西为核心的中央周围。

后来，这个希伯来教也就成大事了，也就是说，它覆盖了非常大的一片人群。希伯来教大概存在了1000多年到2000年的样子，还是非常厉害的。

我们如果再仔细考虑一下的话，就是说，如果你不信教的话，你就会觉得希伯来教好像不太好。但是呢，我觉得它还是要远远比石器时代好很多。我们前面讲的那个石器时代的故事，如果你出个远门的话，就可能被人烤着吃了。在希伯来教下，你起码出远门不会有什么生命危险。因为你信一个教，也不用怕走远了就被人撒上籽，然后给烤着吃了。因为大家都信一个教，那些不信希伯来教的人，摩西同志已经帮你处理掉了。

就在这个比较之下呢，还是比那种部落的情况下自由度大了很多。这个自由度肯定还不是特别自由，但是比石器时代的时候要自由很多，你可以到处走了嘛。

希伯来教主要的忽悠对象就是希伯来人。摩西也说了，你只要信我，别着急，你只要信好了，让上帝高兴了，就把咱们所有人接到天上去，就是天堂。其他那些不信的人呢，或者是信其他教的人呢，天使也不管他们，上帝也不管，他们就通通下地狱。

一方面呢，我觉得真有人相信这个，就是大家只要好好地跟着摩西或者信这个希伯来教，就是早晚去天堂。所以大家也就这样凑在一起好好地信。另一方面，我觉得信一个教也并不是很差，也比以前的时候要好很多。如果你有很多的宗教之间互相残杀的话，还不如信一个。你信一个的话，起码能安安稳稳地过日子，总比要互相残杀强。

所以呢，这个希伯来教还是兴盛了1000到2000年。

嗯，再说一下我这个公众号。主要内容就是写历史，尤其是写IT的历史。就是我在考虑这个Linux为什么会兴盛的时候呢，而且大量的好东西，尤其是软件都出现在西方，这肯定不是巧合。如果你只有一两个出现在西方，其他的出现在东方，也许不会，这个我们可以说是巧合。但是呢，显然这个不是巧合，因为大量的软件都是西方开发的。我觉得西方比东方更早地开化，尤其在自由这一方面。

Linux以及大量的自由软件是在个人主义、自由思想，还有这个多元文化的土壤上才能发展起来。如果你没有这个，可能会比较麻烦。我就这样写着写着，分析着分析着，想着想着就写多了。索性也就写多吧。

主要是第一，我这个提炼观点的能力不行，写着写着总是写多。我本来只想写Linux，但是想着想着，哎，你这个从文化上去分析，为什么Linux和众多的自由软件都在西方的话。如果你要从西方写起呢，你难免要以我的这种个性或者这种臭毛病，难免要追溯一下历史。比如说Linux的历史，你要承接Unix的历史吧，Unix的历史，你有可能讲着讲着就承接电子管的历史，电子管的历史，你又承接电的历史，电的历史，你又慢慢地又追溯到什么蒸汽时代，这样一直追上去。

我觉得还是从2000年开始写吧，但我也不知道写几期，就这样写着。

这期的内容就是说，希伯来教相比于石器时代呢，肯定是一个非常伟大的进步，就是把人从一个小小的部落中解放出来。虽然你这个思想还是受到束缚，但是起码不用怕。就是说你为了争夺食盐，哎，被人给砍头了。人类的自由和个体，也算是在希伯来教的带领下，算是一次很伟大的解放。

在下一期的时候，我这就再讲讲耶稣创办的这个基督教。他在希伯来教的基础上，又一下子解放了一下人类。说实在的，基督教这家公司至今2000年了，光教堂这个资产，你如果算算，他每个教堂都是在非常好的地方，并不是差的地方。全球的上市公司，如果他把这个教堂都卖了的话，全球的上市公司有一家算一家，包括微软、谷歌，包括什么各种的公司，MBM这种加起来，如果基督教把全球的地产这样卖掉以后，把这些上市公司全部私有化，一点问题都没有。

下一次呢，我们就讲一讲这个基督教是怎么在希伯来教的基础上，哎，又一下子打破了希伯来教的这个束缚，又把人这样解放了一下。好，再见。
