---
title: "危险的Facebook"
editor: visual
---

欢迎收听《软件那些事儿》第11期：危险的Facebook

在1994年6月22日，美国世界杯上，作为东道主的美国首轮就逼平了瑞士队，次轮又以2:1的比分击败了当时世界排名第四的哥伦比亚足球队。然而，在这场比赛中，哥伦比亚的后卫埃斯科巴，当时被称为南美洲最好的后卫之一，却打进了一粒乌龙球。他不顾队友的劝阻，坚决回国。结果在1994年7月2日凌晨三点，在一家酒吧被数名枪手乱枪射死。这就是发生在哥伦比亚，一个经历了50多年内战、分崩离析的国家的事情。

在哥伦比亚，有一个成立于1964年的武装组织，原属于哥伦比亚共产党下属，名字叫做哥伦比亚革命武装力量人民军（简称FARC，注意，这与我们通常理解的“fuck”完全不同）。冷战以后，该组织失去了苏联以及其他共产主义国家的支持，开始从事恐怖袭击，被美国称之为西半球最危险的恐怖组织。它涉足了60%以上的毒品交易，该组织有一首对歌，翻译成中文后，其中有两句的意思是：“穷苦人民团结起来，团结起来战斗，穷苦人民万岁。”

FARC扎根在哥伦比亚东南部的丛林以及安第斯山脚下的平原地区，以打游击的方式和政府军对抗，参与了哥伦比亚至少1/3的恐怖袭击。据我了解，FARC是西半球唯一强制女性堕胎的组织。所有的女兵如果意外怀孕，只能选择堕胎，没有其他的选择。有FARC的女兵在接受采访时说，她怀孕5个月以后想把孩子生下来，结果一个男医生发现了，就在她的午饭里下了蒙汗药或者安眠药。等她醒来，孩子已经被取出，还被分成了一块一块的。这是我看的一个纪录片中的内容，纪录片的名字叫《哥伦比亚：和平进程中FARC女兵将何去何从？》。大家可以在网上搜索，有中文字幕，虽然语言是西班牙语，但不影响理解。

在2002年，哥伦比亚有一名叫做罗哈斯的女性，在被FARC劫持以后生下了一名健康的男孩，从此就杳无音信，生死未知。这个男孩的名字叫埃曼尼尔，是FARC的700名人质之一。当时中国人民的老朋友、委内瑞拉总统查韦斯（现已去世，死于癌症）一直可以与FARC取得联系，并多次被指责资助FARC组织以提高自己在南美的影响力。但委内瑞拉的外交部多次否认这一指控。查韦斯当时负责和FARC谈判来营救一些人质，其中就包括罗哈斯和她的孩子埃曼尼尔。然而，当查韦斯的直升飞机飞出哥伦比亚后，人们注意到埃曼尼尔并没有被释放。哥伦比亚全国上下一片哗然。

随着时间的推移，这个事件在发酵。在新年到来的当天，哥伦比亚政府就宣布埃曼尼尔已经获救。原因是埃曼尼尔是在他母亲被劫持的时候出生的，出生后就没有办法再堕胎了。FARC组织觉得带着一个孩子麻烦，在丛林里就随手将这个小孩丢给了一位农民抚养。FARC组织也不知道这个小孩的下落，明明就丢了嘛，也不知道他死活。政府组织了一系列的DNA测试，终于找到了这个可怜的小孩。整个哥伦比亚都为FARC草菅人命的行为感到震撼。

当时一个叫莫拉莱斯的软件工程师也感觉到如梗在喉，不吐不快。他就登录了当时一家叫做Facebook的网站上，想吐槽一下这个组织。结果他在搜索之后发现整个Facebook上没有任何关于FARC的信息。他当时就感觉到了深深的震撼和失望。于是他花了一整天的时间来思考，最后冒着生命危险在Facebook上建立了第一个反对FARC的群组。当时真的是冒着生命危险，因为FARC组织是个恐怖组织，如果让他们知道了，估计又会拿枪来突突人。就像是刚刚我们说的那个哥伦比亚的球员一样。

这个软件工程师表达了自己的愤怒之后，就制作了一个图标，上面有哥伦比亚的国旗，还有几行标语。标语上写着：“反对绑架，反对谎言，反对杀戮，反对FARC。”然后他将这个群组在Facebook上就公开了，群组的名字叫“反对FARC的100万个声音”。当时他觉得他能收集100万个就已经很多了。然后他就将这个群组转发给他Facebook上的100多个好友。等到第二天醒来的时候，群组里已经有超过了1500个人，这比他想象的要多得多。等到第二天他下班回来，群组的人数已经突破了4000人；等到第三天的时候就突破了8000人。于是他在朋友的建议下，决定组织一次全国的大游行来反对FARC，时间定在2月4日，也就是这个群组成立的一个月之后。

结果这个消息就在Facebook上被大量的转发，全国就开始响应，包括哥伦比亚的首都波哥大以及其他的主要城市。消息很快就传播到世界各地，世界各地也都响应了这个号召。全国的大游行就变成了全球的游行，包括美国的迈阿密和洛杉矶、阿根廷的布宜诺斯艾利斯、西班牙的马德里、法国的巴黎等地。最终，Facebook上一个小小的提议演化成了一场全球的游行。

在2月4日的当天，哥伦比亚有超过1/5的人参加了游行，人数超过1000万（因为哥伦比亚的人口不到5000万）。在世界其他地方也超过了200万人举行了游行。在游行的当天，这个群组的人数就突破了35万人。在经历了50多年的惊吓和压迫之后的哥伦比亚人终于突破了自己的恐惧，让哥伦比亚的年轻人勇敢的表达了自己对恐怖和压迫的不满。

FARC组织当时也知道了即将到来的游行示威，他们也被迫做出了一些人道主义的姿态，说他们马上会在游行之前释放一些人质。但后来在一次拯救行动中，获救了一个很出名的议员叫贝当古。他说在2月4日游行的那一天，恐怖分子是能听收音机的，收音机里的人就一遍一遍的喊：“反对FARC，我们要自由！反对FARC，我们要自由！”他作为一个人质，深深的被感动了。就在那一瞬间，他忘掉了恐惧，流下了泪水。而他根据他的形容说，恐怖分子听到这个之后就很难以忍受，关上了收音机。

就这样，Facebook第一次大规模的出现在了人们的眼前。在此之前，Facebook的形象一直是作为一个泡妞或者晒幸福的网站。在此次事件之后，Facebook的创始人小扎说，哥伦比亚这次事件是政府管理方式的风向标，这件事情真正影响到了每个人民主自由的诉求，这也是政府需要努力达到的目标。

随后的一年，在2009年，Facebook又极大的影响了当时的伊朗大选。一个年轻的女孩在抗议集权政府的时候被枪杀了。这段视频在被广泛的在Facebook上传播，在中国也传播的挺多，包括腾讯网等都还做过专题，因此也就激起了世界范围的抗议。当时陷入被动的伊朗政府多次试图封杀Facebook这个网站，但都没有成功。当时中国人民的老朋友，伊朗总理内贾德几次都把Facebook封杀成功，但是他的竞选对手穆萨维还是很厉害。穆萨维的整个竞选团队会用代理软件去翻墙，所以你封杀了，相当于给人家送了口实，所以封杀不好。不久之后，Facebook又被解禁，后来又反复的封杀了好几次。

前一段时间，我看新闻说伊朗的Facebook又不能用了，好像今年伊朗又要大选了。现在呢，FARC组织仍然是活跃的西半球恐怖主义的最前线，稳坐西半球的恐怖主义的第一把交椅。但是他们现在吃一堑长一智，已经不允许上网了，连手机都不能使用。我看纪录片的时候，如果你要去采访的话，先把手机电池扣了，都不允许使用。他们怕透露了消息，导弹也许就过去了。现在连收音机都限制了，毕竟Facebook太危险了。

好了，这一期就讲到这里。
