---
title: "Linux已经进产房了"
editor: visual
---

Linux 已经进“产房”了。上一次说到 Linus 吭哧吭哧地搞了很久，10个多月，没日没夜地编程，终于把它的终端仿真器做得功能越来越强大，越来越像一个操作系统了。这个终端仿真器的功能已经远远超过了一个单纯的仿真器。

在一九九一年七月三日十点零五十秒，Linus 在 Linux 新闻组里发了一个帖子，询问有没有人可以提供一个最新版本的 POSIX 标准，这是能够在网上找到的，最早的有关 Linux 在搞操作系统的证据。

为什么这么说呢？我们来说一下这个 POSIX 规定。如果大家想详细了解 POSIX 的话，可以通过这本书《UNIX 高级环境编程》的第二章来学习。这本书非常的好，所有有志于学习网络编程的人，这本书基本上你是绕不过去的。这个作者呢，已经去世了，他的名字叫 Richard Stevens。这个作者是一九九九年去世的，他是个写书的作者，在计算机界写书的作者那么多，可以说是多如牛毛，但是从来没有一个作者能够达到他这样的高度。这本书的第二版的序言是 C 语言的发明者 Dennis Ritchie 写的。这个人呢，每年都会有人在他的忌日的时候纪念他。在黑客、白客，还有灰客中，他获得了出奇一致的评价，那就是备受赞扬。

如果说一个搞 UNIX 或者 Linux 网络的，没有读过这个作者的书，那我是不信的。TCP/IP 那三本，还有 UNIX 网络编程的那几本，肯定都要读。如果你搞这个又说没读过，基本上呢，我就认为你是在说你小学的时候没有加入过少先队员一样，那肯定就是在说谎。我们都曾经是少先队员，好不好？谁也别说谁吹牛逼，我们都吹过牛，我们都说自己要当社会主义接班人。结果到后来呢，结果反正我是没有见过几个能够有资格接班。

但是呢，先不要忙着去网上下单去买这本书。因为第二章，这本书的第二章叫“UNIX 标准化及实现”。即使你把这一章读完的话，光那些缩写的字母，比如说 ANSI 呀，IEEE 啊、FIPS、OPEN 这些字母，都是一些组织。你要把这些组织慢慢搞清楚的话，至少你得查两天维基百科。所以呢，还是来听我讲一下这个故事。

在我们中学的时候，学中国的历史。其实呢，通过学历史是一个非常好的洗脑的方法。每个国家其实都是一样，我们所有人呢，都是其实被洗的都差不多。我们一毕业呢，脑子其实都不怎么好使，一个是偏激，第2个是糊涂。第3个呢，就是很多观点，我们都是一样出奇的一致。比如说一说到秦始皇呢，我们的脑子里就蹦出来几句话来，都是相同的：它统一了度量衡，统一了文字，统一了货币，统一了中国。当然了，这绝对是一个丰功伟绩。因为在相同的标准下，办起事来还是要方便一些。比如说你北方写这个字，南方写那个字，秦始皇那时候要下个诏书，出了首都咸阳走不远，哎，他这个字就已经没人认识了，确实也非常的不方便。这个时候呢，确实需要一个强人，把文字给统一起来。

当时有很多国家，比如说有齐国、秦国、燕国、赵国、魏国，文字都是不一样的。秦始皇就下令把它统一了，这样文字就相同了。当然这都是历史书上教我们的，实际情况可能有很大的出入。我们姑且认为这是真的，我这个公众号呢，也不打算讨论历史的真假。如果有人仔细追究的话啊，至少有五成是假的。不过呢，历史上这么叫，我们就信以为真。

在当年 UNIX 混战的时候，也是出了相同的问题，就是 UNIX 版本实在太多了。贝尔实验室有，SCO 公司有，惠普公司有，IBM 公司也有，甚至微软公司也有自己的 UNIX 版本，叫做 XENIX。所以说呢，别以为微软多么敌视这个 UNIX，都是脚踩两只船的人。如果微软出的这个 UNIX 跨行版 XENIX 卖得非常好的话，我觉得他肯定会继续卖这个，而以后 Windows 都不出了。所以呢，谁也别说谁，每个 UNIX 版本呢，都有自己非常独特的地方。

现在我们不是经常说叫差异化竞争嘛。当年呢，这几个 UNIX 版本差异化竞争的非常厉害，每个版本都不同。如果你买个软件呢，在这个上面能运行，在那个上面就不能运行了。但是我们想想，那个年代最大的客户是谁？是美国政府。美国政府买了这个软件呢，买了某个软件，结果呢，只能跑到 IBM 的 UNIX 上。到时候你换一个惠普公司的 UNIX，哎，它就跑不动了。虽然这个山姆大叔呢，虽然非常有钱，但是人家可不傻。山姆大叔就下了一道圣旨，就是说呢，以后想要我买你们的操作系统是可以的，但是前提是你们所有的操作系统都能运行我买的这个软件。具体怎么办呢？我也不懂，你们这些厂商自己去商量，商量不好，那我就不买，反正也是做生意嘛。

这些厂商也不傻，有钱不赚，专门跟山姆大叔对着干，那也不合理，不符合场景。因此呢，他们就马上就组织人嘛，开始标准化 UNIX。UNIX 标准化了，结果就出了几个版本的 POSIX。可能出了几个版本的 POSIX 之间呢，技术上是有差别的，但是呢，这个伺候好山姆大叔的心是一点差别都没有的。

制定 POSIX 标准的组织叫做 IEEE，其目标呢，就是实现 UNIX 的可移植性。最终的目标呢，还是让美国政府买我们这个 UNIX。对程序员来说呢，我们编写应用程序的时候，并不是直接调用系统调用来编程的，而是使用应用编程接口，就是我们经常说的 API 来编写应用软件。这些 API 呢，可能是调用了系统调用的，有的 API 是调用了一组系统调用，但是对程序员来说都不关心它调用了哪些。但是这些 API 都是要有一样的。IEEE 呢，就规定好了，有这么多 API，每个操作系统呢，你都要实现一份。如果你想让山姆大叔高兴呢，或者想卖这个软件给美国政府，你就要必须遵守这个 POSIX。然后呢，这些 UNIX 厂商也就因为为了卖软件嘛，就支持这个 POSIX。另外呢，微软公司的 Windows 实际上也是支持这个 POSIX 标准的。也就是说呢，如果你给 UNIX 开发一个完全支持 POSIX 标准的软件，从原理上来说，是可以不用修改源代码，重新编译一下就能拿到 Windows 上来跑。这个标准呢，叫做 Services for UNIX。后来呢，又改名叫做 Subsystem for UNIX-based Application。然后呢，其实这并没有什么用，没人用。等到 Windows 8.1 的时候，这个东西就从 Windows 中彻底消失了。现在 Windows 10 有和 WSL（Windows Subsystem for Linux）合作直接运行 Linux 软件的功能，但我还没有试过，因为我有一台真正的 Linux 放在家里，我就有可能是不再去启动 Windows 了，更麻烦了嘛。

对 UNIX 来说呢，支持 POSIX 一下子就像是秦始皇统一了度量衡一样，UNIX 软件的一致性就大大提高了。

讲了这么多呢，我们来想一下，Linux 为什么要支持这个 POSIX 标准，而且还在网上发帖子需要这个标准呢？因为当时 UNIX 是 Linux 的前辈嘛，在1990年的时候，那时候已经有大量的 UNIX 软件都支持这个 POSIX 标准，就大量的软件已经存在了。Linux 呢，如果想让它的这个系统支持 POSIX 标准，那些软件就直接可以运行在它这上面。因为我这个系统也支持，所以说呢，Linux 当时就做了一个最聪明的选择。如果你这个写的操作系统不支持这个 POSIX，那所有的软件都得你 Linux 自己一个人去写，包括 shell 啊，包括我们现在经常用的 bash，那个 shell 都是由你自己全都要自己写。肯定是那时候他还不出名，没有人会乐意给一个不支持 POSIX 的新操作系统写软件的。但是你这个操作系统一旦支持了 POSIX，就天然拥有了海量软件，大量的软件都可以编译一下，就在你这上面运行。

所以呢，这个时候还有一个另外一个软件界的巨头，它的名字叫理查德·斯托曼。每当谈起这个 Linux 呢，他就生气，因为 Linux 其实只是一个支持 POSIX 的内核，其他的很多软件都是在他的努力下建立起来的，包括 GCC、GDB 等等。这个理查德·斯托曼同志呢，就是他经常痛心疾首，也是非常有道理的。他真正的做到了万事俱备，只欠一个内核。他的内核呢，在 Linux 之前呢，其实就已经在开发中了，这个内核的名字叫 Hurd（GNU Hurd）。但是呢，至今，也就是今天，2016年8月10日，我录这个音频的时候，都已经过去二十六年了。Hurd 呢，还是没有开发成功，到现在还在开发这个内核。最初的名字叫 Alex，是斯托曼同志二十六年前的女朋友的名字。现在已经二十六年过去了，那个女朋友早已经飘散在天涯，还可能成了几个孩子的妈妈。但是我们这个斯托曼同志呢，至今还是单身。这个已经开发了二十六年，可能再过二十六年也不一定能开发成功的内核呢，早就名字已经不叫 Alex 了。这其实说起来是个有点悲伤的故事啊。

所以呢，每当斯托曼同志讲到 Linux 的时候，他总是要把他的 Hurd 放在前面，他都叫做 GNU/Linux 或者叫 Hurd/Linux。如果有人胆敢在他的前面，就是说只说 Linux，而不说这个 Hurd 呢，他马上就跟你大声地纠正。你要是不修改，那你就惨了。这个今年已经63岁的前辈呢，经历永远处于18岁，至今没有人能辨认过他。我们经常现在我们还经常使用的 GCC 啊、GDB 啊、Emacs 编辑器啊，都是出自这位前辈之手。

所以呢，有时候我就说，如果这个世界上只有一个人符合一个标准，什么标准呢？就是他是一个高尚的人、一个纯粹的人、一个有道德的人、一个脱离了低级趣味的人、一个有益于人民的人。在我的心目中呢，如果只有一个的话，这个人就是理查德·斯托曼。如果有两个的话，我就认为是理查德·斯托曼和林纳斯·托瓦兹（Linus Torvalds）。

希望我把POSIX有多么重要讲清楚了。

能完美支持POSIX的新的操作系统，在当时就像一台缺了一个发动机的超级跑车，比如兰博基尼的超级跑车。而Linus就是这个幸运儿，它造出了这台发动机，万事俱备，东风也来。

在我前面说过，Linux发了一个帖子，求这个POSIX标准，希望有人能给他发一份。但当年他也是一个人微言轻的小伙子，根本就没人理他，于是他就实施了他的B计划。他从学校的图书馆里找来了一本上海翻译的UNIX手册，开始了反向编译。这个系统调用真的很厉害，他看着手册就反向编译，还从其他的一些书上把系统调用研究得差不多了。但后来他还是设法搞到了一本厚厚的POSIX标准的材料。

在这里，我们中国有句话，叫“行家一出手，就知有没有”。Linux一发帖子就有个高手马上意识到了一个问题，这个家伙是在写一个操作系统。这个高手就是赫尔辛基理工大学的助教，他的名字叫阿里·莱姆克。他就在这个帖子下面回复了一句：“你是在做操作系统吧？我已经在我的FTP上给你创建了一个文件夹，等你把操作系统做好了，记得传上来。”

如果我们在学UNIX网络编程，我们会学什么？我们普通人就是学API，根本就用不着学POSIX。如果你现在看到有个人正拿着一本大概十几斤重的书，总共有七本还是八本，这么厚的书在学习POSIX标准，只有两种情况：第一个，他是想做操作系统；第二个，是他拿错书了。

希望通过这篇小小的文章，让大家知道了POSIX的重要。

讲到这里，就是Linux这10个多月吧，Linux就要出生了。所以下一个故事就是讲Linux出生的故事。

好了，这期就到这里，再见。
