---
title: "Linux传奇：Linus如何在裸机上写软件"
editor: visual
---

前文提到，21岁的Linus买回来了一台电脑，对上面自带的MS-DOS操作系统不满意。后来又花了169美元买了一个叫Minix的操作系统，在用了16张软盘装上以后，用了一下还是不满意。然后呢，他就决定自己做一个终端，连到学校的Unix上用Unix的机器。

我前面所说的这段话有非常重要的信息。我们从中可以看出Linus的机智，他觉得MS-DOS不好用，也觉得Minix操作系统不好用。他有没有去抱怨呀？比如说发个邮件给微软或者是发给Minix的开发者就开始抱怨。那个Minix的开发者名字不叫安卓，真的很搞笑，大家别误会了。他也没有抱怨，也没有到网上去骂，而是自己卷起袖子就开始干了，这就是实干家的作风。

再多举几个例子，我比较佩服的几个实干家。比如说朱元璋，他看到元朝非常的腐败，他有没有去上访啊？有没有找哪个县官提意见，说你这个当官要为民做主，或者去元大都去找元顺帝反映情况，说你元顺帝是个好皇帝，可是下面的官不行？没有，他什么都没有做，因为这是无用功嘛。当17岁的朱元璋的亲人一个一个饿死，他就和他的二哥用门板抬着亲人的尸体。在元朝的时候，房价也非常的贵，墓地也非常的贵，他买不起墓地，就这样抬着尸体到处走。天下虽然很大，到处都是土地，但是没有一块是朱元璋的。后来朱元璋当了皇帝，想起这件事情来就哭了。他其实后来一直不知道他的父母葬在哪里。后来凤阳建了一个祖坟，其实里面并没有他父母的尸骨。

我们再举个例子，比如说我们敬爱的毛润之老先生，年轻的时候有没有写信给国民党政府说你很腐败？没有，都是卷起袖子自己干，枪杆子里出政权。所以这些牛人都是实干家的，他们也不批评，也不抱怨，Linus也是。所以有时候我觉得我们要向这些老前辈学习，别做那些无用功，试图用骂人或者装可怜来让别人改进，用处其实很小。觉得用的不爽，就自己搞，自己写个软件。

我们来看一下Linus干了什么东西，他在自传里头写了。首先呢，他要研究这台电脑的BIOS，如何从软盘中启动起来。然后启动以后呢，要让电脑从实模式转换到保护模式。接下来呢，在研究CPU的工作原理，比如说你要了解中断，如何把输出的结果显示在屏幕上，如何用调制解调器上网等等。再接下来呢，他还需要写两个独立的进程。一个进程是读调制解调器的数据来上网，并且从网络上下载的数据再显示在显示器上。另一个进程则是读键盘中的输入，并将键盘中读到的数据都写到调制解调器上再传到网上。比如说要发帖子，你要先下载下来，然后再从键盘读了数据，再贴上。为了这个功能，Linus没日没夜地干了一个多月的时间。

这里的读者都非常年轻，不知道调制解调器是什么东西。在我那个年代，在我上学的时候，那个年代就是2000年左右的时候吧，再早一点，上网是通过电话线的，就是咱们真的打电话的那个线上网。我们知道上网使用的是数字信号，那个电话线里那个铜线里面传的是什么信号？是模拟信号。所以这个调制解调器最主要的用途就是将模拟信号和数字信号之间来回的转换。

在做完了这个东西以后，Linus如果想去上网看新闻的话，就把这个软盘放在软驱里重启电脑。这个电脑就从这个软盘中启动起来，这个软盘中的系统就开始运行，他就用这个系统来上网。如果他想改进一下这个仿真软件，就再重启一下电脑，就进入他花了169美金海淘回来的那个Minix操作系统，用那个系统来编程。那个时候呢，他的电脑里已经没有MS-DOS了，就是他用来玩游戏的那个系统已经没有了。

故事先讲到这里，我们就开始仔细的分析一下这段故事中透露出来的信息。要知道Linus为了这个小玩意已经干了一个多月，就是没日没夜地写软件，就一个多月。我在这里呢，试图通过15分钟或者20分钟讲清楚，已经是非常非常偷懒了。如果好奇心非常强的同学，可以真的买那本Linus的自传，随便买一本比较老的，越老的越好，因为新的源代码还看不懂，就越老的那种Linux源代码。然后自己来看一下，上面都有讲。比如说我上一期所说的这本书叫《Linux Cocoon Commentary》。这本书我慢慢地磨了好几年，最后还是有一部分看不懂，但是大部分我觉得都是能懂的。

我们通过这个信息来分析一下。首先呢，他要研究BIOS，然后设置BIOS，让电脑从软盘中启动起来。这个过程呢，我以前在这个公众号“软件那些事”里写过，就是写电脑一按电源之后，BIOS的整个技术细节，名字叫做“钻牛角尖：电脑启动都启动了啥？”如果有人好奇的话，并且没听过，可以翻一翻看看，里面讲的比这里清楚。这里我就简单的说一下，就是电脑启动以后呢，会启动一个扇区。如果发现这个扇区里有特定的字符，就知道这个东西是可以启动的。这个字符就告诉他，它就从这里启动。引导扇区只有512个字节，这512个字节非常的小，而且现在超过512个字节怎么办呢？要解决这个问题，你必须得有解决方案。并且这个如果你只是想在电脑上显示一个“Hello World”，在裸机上你就写一个启动扇区就可以，20行代码就可以。在这里我也没法讲，代码非常简单，但是其他事情都不做，就是一下启动起来就显示一个“Hello World”，就不是操作系统，就是一个启动扇区就能做这件事情。

上面我还提到了Minix，Linus付了个首付，付了1000多美金，买回来一台有386处理器的电脑。问题就出在这里，但这都是他的自传里写的。我们就分析为什么他要写这个东西？因为从80386开始，英特尔开始让CPU进入32位的时代，就整个个人电脑正好要进入32位，以前都是16位。32位是什么意思呢？我们可以想它有32根地址线，大家可以近似的认为CPU和内存之间插了32根电线，你就可以这样认为。很大一捆电线，32根总共它访问的内存地址可以是多少呢？我们知道是2的32次方，就是4G内存。如果当年你很有钱，是个土豪，比如说你花了几十万给电脑装了8G内存，可能是没有，当年没有8G。如果你特别有钱，装了8G也没有用，因为电脑只能用4G，你装上了8G，至少有4G是浪费了。因为其他的超过这个4G的就没法用。当时Linus没有买那么多，他就买了个4M。

如果大家对CPU感兴趣的话，可以再看看我微信公众号的以前的内容。我也讲过指令集，指令集就是讲英特尔这段历史。因为我们不停地在讲技术的话，这些技术并不是凭空产生的，都是碰到了问题才想解决方法。电脑好像也是这样，并不是哪个牛人在哪个地方说画了一个圈就搞定了，那都是骗人的，除非那个人是孙悟空，画个圈可以挡住妖魔鬼怪。

因为英特尔刚开始的时候，CPU是8086，是16位的CPU。16位的CPU有16位寄存器，16位数据总线。然后下面这个数字就开始变了，它的地址总线并不是16根，而是20个。这个大学里考试，如果大家是大学生的话，你可以知道大学里考试经常有的题就这样坑你一下。大家认为前面都是16，后面也应该是16，其实不是。英特尔8086这个16位的CPU，地址总线是20个。在学校里考试的时候，还经常有一个知识点，就是怎么算物理地址。其实很简单，你稍微看一下书也就明白了，我这里讲也确实没什么意思。再说了，你不用看公式的话，也有点讲不明白，那个公式也非常简单，三年级就可以知道什么意思。

大家只需要知道一点，16位的时候呢，要做内存寻址还是可以的。但是一旦进入32位的时代，从寻址的方面来说，光有16位寄存器就不够了。因为Linus当时正处于个人电脑从16位转向32位这个历史时刻。所以说Linus的运气非常的好，一方面呢，它是16位转32位刚刚开始。另一个方面呢，这两年Unix正在打官司，因为版权的官司嘛，打了三年，就为了3个文件打官司，打了三年。这三年Unix根本没更新，就让Linus抓住了这个机会。如果稍早一点或者稍晚一点，或者Unix没有打官司，32位的Unix就马上推出。而Linus本身就喜欢用Unix，所以他也不会再去模仿Unix，再写一个新的操作系统。

当然了，历史也不能假设，我这里只是一家之言嘛。接下来就开始引入实模式和保护模式的区别。首先我得声明一下，实模式转到保护模式下的好处非常非常多，课本上都讲了很多条，不只是内存寻址。但这里我这个也不是教科书，只讲一点，讲多了也没事。电脑刚刚开机的时候呢，是实模式，就是我们这样一开机，那个电脑就开始进入实模式。

我前面铺垫一下，实模式是有问题的，就是没有办法使用更多的内存。这个时候呢，因为内存多了嘛，你必须要做某些机制做出改变。你插了那么多内存，如果用不到，是不是很崩溃？这个时候呢，就想了一个解决方法，就是说在某个时刻电脑启动的某个时刻，就执行一个叫“模式切换”操作。一旦这个模式切换执行，就相当于是整个国家发生了变革，电脑这个操作一下子就换了新的统治者。

这里面当然讲优点非常多，我们可以这样类比一下。比如说，新中国成立以后，刚开始就是在摸索中运作，包括要进入共产主义啊或者什么。但是伴随着一大堆报纸上说的举世瞩目的成就，比如说大连钢铁呀、什么文革之类的，慢慢的人民就有了更多的需求，就满足不了了嘛，怎么办呀？就改革开放。也就是说呢，在某个时刻，新中国在改革开放的那一刹那，实现了这个转变操作，以前的规则就不算数了。现在是在邓小平的领导下，继续取得举世瞩目的成绩。以前的成绩当然也是举世瞩目，现在的成绩也举世瞩目，但是呢，以前是实模式，现在是保护模式，希望大家对这个实模式和保护模式有一个感性的认识。

其实我很想讲技术细节，想想还是算了，讲起来很久也就不讲了，能讲起来还是有点麻烦。你如果不看书不画图的话，是讲不清楚的。上次我们也分析了linux买的电脑是什么配置，相当于它当时的内存是非常多的，当时非常多，高达四兆。如果linux没有追求的话，很多人没有追求的话，它其实只可以用实模式就可以了。其实大家可以算算看，实模式下，你只能使用一兆内存。它本来就花了那么多钱，而且本来还很穷，还贷款买的电脑，买了个四兆的。你在实模式下最多只能使用一兆内存，就相当于浪费了三兆。所以呢，你为了能用上所有的内存，所以他花了一个月时间来调试各种代码。

再说一句的话，就是实模式下，这个一兆非常小。

就是32位保护模式下呢，你可以使用2的32次方，就是可以使用4G内存。当然现在我们这今天的话，电脑就非常容易超过4G内存。像我一台电脑，我工作的电脑远超过4G，我用了32G内存。如果现在有很多人电脑就是配置一个16G的内存，然后他让人家给他装了一个32位的Windows XP。这个时候呢，你最好是不要告诉他他至少浪费了12G内存，因为这种人都一般都比较有钱。如果你再告诉他内存寻址什么这种话的话，只能不是显得他特别笨，而是显得我们特别穷。所以这个时候呢，我们还是保持沉默就好。

另外再说一下“保护”这两个字，为什么叫保护模式呢？这个“保护”这两个字从什么地方来？保护模式就是说你这个内存一旦你超过了某个范围，你就不能访问了，这就是保护的意思。你的软件并不能说我想写一个软件，想访问哪里就访问哪里。那这病毒不是正经软件，所以呢才有保护模式这一说。就有些内存地址你是不能访问的。但是这里面还有不少很有趣的技术细节，比如说GDT啊、LDT啊，就是描述符表等等，这种也很重要。但我这个公众号也不能讲这个，本来听众一个时候，你在讲这个就崩溃了。当然还是看书比较好，我这里也就不多说了，再讲它字段里最后一个细节吧。

linux在当时，他当时就写了两个进程，一个呢是往屏幕上写aaa，就是一串a；另一个呢，往屏幕上不停地在写bbbbb，就非常兴奋。为什么很兴奋了？你可能会想，哎，进程不就是一块或大或小的代码块嘛，应该也不难。你到了某一个时间，你让他去执行就行了呢。其实呢，这句话就差一点就对了。其说的差一点是什么意思呢？比如说我可以说我当年差一点就考上北京大学了，因为当年北京大学录取分数是715分。我差了一点，就是差考了，我考了71.5分，也是差一点嘛。其实非常难，进程难就难在这个进程的调度上。

如果linux当时想写这个任务，因为是两个任务嘛，但他的电脑上只有一个CPU。最简单的方法是什么？当然是两个CPU，一个任务运行在一个CPU上，这样一点都不冲突。但实际上不行，因为它只有一个CPU，你要牵扯到这个进程的调度。进程调度也是计算机课操作系统课中非常重要的一个内容。

在完成了多进程这个工作以后，linux本人也非常高兴，因为这个工作太重要了，他就自传了一些内容。我顿时感到特别自豪，对于这次成就，他甚至喊他的妹妹Sara过来看看，要知道他们两个关系一直不怎么好。结果他妹妹就看到屏幕上一会儿显示a，一会儿显示b，然后就很期待嘛。最后看了一会儿，就不停地这样。他说大概过了5秒，就说了一句：“挺好。”转身就走了。随后呢，linux在自传里还是继续很自豪地写，有些东西呢，表面看起来是没有什么东西，但是呢背后却包含了大量复杂的工作。就好像你刚刚把一段铺好的公路指给别人看，指望这样能让别人明白你耗费了多少人力物力，那根本不可能。

所以呢，这一期内容也就讲到这里，也没有办法再继续深入的技术细节。呃，我们可以回忆一下，首先我们先讲了BIOS的启动，就讲了如何突破512个字节的启动限制，还讲了实模式和保护模式之间的关系，就是保护模式更好。最后呢，我们讲了进程，就是你要有进程调度啊，非常难。所以我们大概也就是用了那么十几分钟，回顾了一下linux一个多月的工作，其实是远远不够的。如果有非常好奇的人的话，非常希望大家能买本书来看看。如果有志于当程序员的话，比如说我一直推荐的这本《Linux Concurrency and Communication》或者其他类似的书。其实光听我讲故事，最后听来听去，只能在饭桌上吹吹牛，也没有什么太大的用处。linux的自传只是为了好玩。第55页仍然是说我当时穷得叮当响。我一向认为做人非常重要的一点就是不应该向别人开口要钱或者讨钱。他每个月呢，都还要为了还贷款操心，因为当年他真的是穷得叮当响。后来呢，一些linux的用户知道了以后呢，就凑钱把他的电脑的贷款给还了，但是他还是很开心嘛。
