---
title: "Linux传奇：吵架史上的一段佳话"
editor: visual
---

在写的 Linux，其实已经搞了个 156 期了，结果才写到 Linux 刚刚发布。我估计按照我这个风格这样写下去，要写完整个 Linux 的故事，非常非常有可能比 Linux 那本自传还要多。

所以有热心的听众就给我提了一个意见嘛，就是说我应该向谁谁谁学习啊，向哪个公众号学习。就是一本书呢，你浓缩成 1000 个字或者 5 分钟的音频，顶多顶多你就是写一期或者两期，两期就不好了。在微信公众号里，就是顶多写一期介绍一本书，就是把整本书的精华提炼出来。这样呢，你这个读者节约时间嘛，而且还觉得我看过这本书，这样才有前途。否则的话，像我这样逮住一本自传书，经常是书里写了一句话，我就给它扩充成一篇公众号的文章。这种玩法呢，迟早要完蛋。

我思考了一下，这个是非常有道理的。不过呢，我想想，还是不打算采纳这个建议，为什么呢？比如说这篇文章里，书上就写了两个人吵架了。如果浓缩的话，整本书中这个吵架的事情什么都不算，肯定就是说我在浓缩的时候肯定就删去了。但是我认为这个吵架是最有意思的。你只是说那种大方面的事情是没什么意思的。而且书中就只有两篇帖子，而且还非常不过瘾的两篇帖子，也不算是真正的吵架的两篇帖子。而且这个吵架牵扯的人非常多，当年这个围观的吃瓜群众也非常多，都是看热闹不嫌事大，就是非常非常多。更多参与这场吵架的人都是有好多的牛人，包括 Unix 的创始人之一肯·汤姆森（Ken Thompson）。当然了，他没有吵架，他只是发表了自己的观点。还有日后 Linux 内核的二号人物，或者几号，我认为他是二号，叫大卫·米勒（David Miller）也在这场大战中参战了，属于参战国之一。

我个人认为，扩充这个故事比删掉这个故事有可能更有趣。毕竟吵架这种东西我还是很喜欢看的。

不过呢，我还是非常感谢这位热心的网友，因为我觉得我这个公众号连人家可能 1/万的订阅者都不到。我也觉得把一本书你浓缩成 1000 字或者是 3 分钟的音频，肯定比我说人家的，人家文章就写了那么一点点，你给他扩充一本都要抢。毕竟这个结果摆在那里，人家首先很有名，并且有数百万的订阅者，像我这个就是一点点，几百人不到。所以这个扩充故事的方法肯定是反潮流了。就是说你有可能像我这样，就是把整个的故事搞得比原著还要多。

但是呢，我个人觉得这个故事真的是还是蛮有趣的。还写到这里的时候，我就突然想到了另外一个故事。这个故事大家小时候一定听过，确切地说，它是个成语小故事。那个成语叫做“张良纳履”，就是说张良呢，在街上散步，碰见了个老头，老头就刁难他嘛，就把鞋子一下扔到了桥底下，让张良去捡。张良就看这个老头很年迈了，就下去捡了，并且还跪着给他穿上了。然后这个老头又刁难了他几次，包括半夜到哪里去碰头啊，并且还连续三天晚上，是隔了几天，连续去了三次。最后呢，这个张良看着就是很善良嘛，就给了他一本兵书。张良就靠这本兵书呢，帮汉高祖刘邦就完成了统一大业的故事。

这个故事呢，当时我们小学生就说反映了要尊重老人，什么中华民族的优良传统，要尊老爱幼、吃苦耐劳等等，什么磨练、挫折呀什么的。这就是我们小时候把这个故事给浓缩了，浓缩成这样一个小故事。大家也觉得哎，听了之后很心灵鸡汤。实际情况呢，我还是扩充一下大家听听我这个扩充的版本。

这个故事呢，其实最初是记录在司马迁的《史记·留侯世家》那一篇文中。同学们，你们想一想，这个司马迁老先生花了那么大的笔墨，绝对不是说让大家学会中华民族的优良传统，什么尊老爱幼、吃苦耐劳、挫折教育等等。司马迁再说了，他又不是写心灵鸡汤的。写本《史记》让我们从中找出正能量，有了活下去的勇气，不可能的。虽然这个《史记》你仔细读的话，里面正能量还是有点，但肯定不是说为了弘扬正能量和让你心灵鸡汤来写这本《史记》的。

所以我还是说一下这个故事。故事的前情提要就是张良是个官二代嘛，也是富二代，金钱和这个社会地位肯定不低于现在今天的王思聪。你想想他的爷爷就是韩国的宰相，呃，他爷爷是韩国宰相，他爸爸也是韩国宰相，他爷爷是三朝的宰相，他爸爸是两朝的宰相。如果按照战国时代的规则，他长大了也是宰相。但我在这里说的那个韩国不是现在思密达那个韩国，而是战国七雄之一的那个韩国，主要就是国土在山西南部和河南北部这一块。不幸的是呢，秦始皇就把韩国给灭了。这个张良肯定灭了国了嘛，你这个当宰相的梦想你就破灭了。

张良肯定是很伤心嘛。但毕竟张良是个非常有胆识的年轻人，他就要刺杀秦始皇。现在很多年轻人胆量就是在网上骂一骂，就是俗称键盘侠，只能骂。但张良不是说干就干，他散尽了家财，家里肯定是有很多钱的，然后就找个大力士造了一个大铁球，就想把秦始皇砸死。因为秦始皇要出游嘛，他就在那个著名的“博浪沙”刺杀秦始皇事件中，是主角之一，他策划了，但很可惜没砸死。因为秦始皇你想当皇帝也聪明，他同时有四辆车，你不知道砸哪一个。结果呢，他就找了一个最华丽的一下砸过去，发现哎，不是那个是斧车，上面不是秦始皇，是另外一个人。所以当时还是考虑的不太周全，应该同时找 4 个刺客，每个人扔一个铁球，但是前提你要打得好。他今天出几辆车，如果出八辆车，你就找 8 个刺客。但没刺杀成功之后呢，张良就逃走了。后来逃走的时候，全国就已经通缉他了。但据说张良这个人长得比较文文弱弱，而且有点女人的样子，就像是个大姑娘一样，所以大家都都不认为是她。因为她看起来不像是那种很彪悍的人。但后来他逃走之后，才发生了这个“张良纳履”这个事情。

原文就是说“良尝从容步游下邳圯上”，就是说张良是在全国通缉的时候，他还从容，迈着个四方步子就在那里走。然后呢，原文说就是这个老头呢，是“治圯所”，也就是说这个老头是故意走到张良所在的地方，这个很重要，是这个老头故意来找茬的。看到张良过来了，他就故意把鞋子一下丢在桥下，然后让张良说，“你给我捡起来”。

然后张良的反应是什么？“良愕然，欲殴之”，什么意思？就是说张良这时候一看，我靠，老头想让我给他捡鞋，就突然吃了一惊，然后呢就想揍他，“欲殴之”，殴打嘛。所以说呢，我们可以看看这个浓缩的小成语故事，跟这个一点不一样。张良显然也没有什么尊老爱幼的优良传统，因为想揍这个老头啊，但是他还是忍住了。因为一看，毕竟这个老头有可能当时也有碰瓷的嫌疑。比如说现在咱们大妈经常碰瓷，他一看这个老头别给碰瓷了，又想想，哎，算了，下去把鞋子给他取上来。

结果这个老头又刁难了一下，说你给我穿上。张良这次就更生气了，是吧？咱们一般人受不了了。他不但给穿，而且还是跪着穿。原文就是说“因长跪履之”，也就是说呢，我直接跪下给你穿，还常跪。结果这个老头连个谢谢也没说，就大笑而去。要是搁现在呢，咱们早就给这个老头拍个视频，然后传微博上开批斗会了，大家也纷纷言什么“不是老人变坏了，是坏人变老了”这种的。但是张良可能也没有带手机，或者那时候也没有手机嘛，就说“随目之”，他就目送这个老头远去。

接下来最精彩的部分是这里，原文是说“复去，离所，复还”，就是说这个老头又走了，一里多路，他就回来了，回来和张良再说话。后面的故事就不说了，跟我们成语小故事就差不多了。虽然成语小故事简化的已经不像样，但是开始说重点，最重点的就是说你看这个老头又走，笑着走了一里多路，然后他又回来了。张良肯定是在原地站着没动啊，肯定是。否则你说老头跟谁说话呢？他就回来之后，当时又没有手机，你又不能打手机，张良就会在原地一直站着。

但后面的故事也很精彩，但是这里不讲了，因为等我写这个IT故事写完了也没有什么料了。等到工作号的人都写跑了，我就开始讲死磕。我们只分析上面我说的这一小段，后面还有很长一段，都很精彩，实际非常精彩。

嗯，这和我们想的不同，但我们也可以看出来了，就是这个故事反映的和我们浓缩的那个“尊老爱幼”没有一毛钱关系。真的是。首先，这个老头是不是来找茬呢？肯定是毫无疑问的，因为他到了他这里故意的嘛。如果你说张良是没忍住，上去就抽了老头几个耳光，这就不是瞎话了，就司马迁也不会写了，因为这就会是一个很无聊的笑话：一个老头找张良，张良把人给揍了，这显然也没什么意思。如果说老头折磨完张良，张良又给他穿鞋子，又给他捡鞋子，然后又大笑而去。张良也没有目送，老者就叹了一口气，说：“我操，今天回家吧，真倒霉。”然后老头走了，一里路就回来发现张良回家了。这当然也是个笑话，不会是真话。所以只有司马迁老先生写的这个故事才是真话。但是我们可以看出，他跟尊老爱幼没有任何关系，这就是两个高手之间的对决，互相在试探。

因为这两个人的斗法嘛，只要两个人的功夫差不多，这才是真话。如果哪一个人走错了一步，比如说不管是张良把这个老头打得牙都掉了，或者满脸是血；或者老头羞辱了张良之后就没有回来，比如说回家喝了一壶酒就去睡觉了，只能说明这个老头是个神经病。所以说呢，如果要想流传为一段佳话，需要棋逢对手。

我讲这个故事的意思就是说呢，如果大家只想读那种浓缩版的故事，很容易就曲解了作者的意思。比如说人家司马迁老先生写的这个故事，结果后来我看很多都传承成了什么尊老爱幼的心灵鸡汤——你要尊老爱幼，就给你兵书，你以后就能荣华富贵，这其实都扯的。

本文所讲的这个安德鲁教授和这个林纳斯之间的争吵呢，也属于棋逢对手。两个人虽然说吵得很激烈，但是没有骂，真的是没有骂，不像我们现在经常上来就给两个字是吧？就是互呛，你来我往地吵。关于技术，以现在的眼光来说就是太文雅了。

按照惯例呢，我还是来复原一下当时吵架的这个历史环境。当时是一九九二年，386是主流的电脑芯片，486还在研发中。微软当时还是一家卖这种DOS系统的小公司。在欧美的市场上，Lotus 1-2-3是电子表格的王者，WordPerfect是文本处理的王者。当时他把微软的这个Word打得满地找牙。当时其他的文本处理软件，包括WordPerfect，都是所见即所得的时候，我们可爱的微软Word，如果你要显示个粗体或者斜体的时候，是显示不出来的，都是有个括号，就说“哎，这是斜体”，就是说还是文字显示出来，不能够给你真正显示粗体和斜体，也不是所见即所得。其他的包括中国这边的WPS啊、WordStar啊，都不占有什么市场份额，根本就没有微软什么事。所以啊，有时候你这个人，我很服微软，你不得不服，不管产品怎么样，最后总是赢。

而且当时就像是雅虎啊、网景这种公司啊，还没有开始建立这个吵架的大背景。咱们就说到这里，这场吵架是在1992年1月29日，一直吵到了一九九二年的2月10日，就吵了那么十来天嘛。帖子的导火索就是安德鲁教授发了一个帖子，说“Linux已经过时了”。帖子是在1992年2月10日快结束的时候发的，一个叫尼尔斯的管理者受不了了，管理员受不了了，就开了一个新的论坛给Linux。从此这个Linux和UNIX就大路朝天，各走一边了。

因为这个帖子实在是太长了，我还是必须得浓缩一下，否则的话说真的就写不下来。我就把曾经啊，在我很年轻的时候，我把参战的所有的ID都记下来了，我想知道每个人都是谁，有好多大牛。不过现在我只记得两个人了，一个是UNIX的创始人叫Ken Thompson。以前我做UNIX的时候也说过，这个人非常出名。还有就是Linux内核的二号人物吧，我认为的二号人物叫大卫·米勒，没有人封他为二号人物，但是他实在是很厉害。所以在我心目中，他就是除了林纳斯，第二就是大卫·米勒了，还有几个开发BSD内核的人，但我对不上号了，毕竟十几年前的事情了嘛，现在我也不想再查一遍，大家随意看看。他们的ID都很固定，包括电子邮件也很固定，其实大家都可以知道，所以我只选取几个比较好玩的帖子来念一念，恢复一下这个样子，大家可以搜一下，自己去看看。

帖子好像得有100多个，我不可能发到这里，而且每个帖子都很长，不是说只骂人的那一种。先是安德鲁教授发信息的时候，就欲擒故纵嘛，先放低了姿态，低调地说了一下：“哎呀，我这个去旅游了嘛，就怎么样怎么样。”然后低调地，他就说了一下这个Linux是我的业余爱好，然后就恶心了一下Linux。然后Linux当然很生气了，他说：“你这个哎，就马上就反击，就是你别拿这个开拓，你写的就是垃圾，在你那个破系统上，所有的好代码都是Bruce Evans写的。”科普一下，这个Bruce Evans是给Linux修补了非常多的功能缺陷。但是呢，这个安德鲁教授更厉害的是，就你修补归修补，但是不能放在我这个Linux上。也就是说你的东西虽然好，如果要装你的呢，先要买我的169（可能是指某种授权或产品的价格），先买个授权，才能够再用Bruce Evans做的修补的那些代码。

然而就这样，然后这个林纳斯继续反驳，你也别扯什么业余爱好，这个谁不知道你的业余。你要是业余爱好的话，你还要花169美元买一份嘛，我这个才叫业余爱好，一分钱都不收。然后林纳斯回帖以后呢，这个安德鲁教授毕竟你这个教授也不可能是马上回吧嘛，都是绵里藏针嘛。然后他就唧唧歪歪地说了一通微内核设计的好处，说什么整体内核都落后了。在最后的最后，突然就来一个回马枪，就对林纳斯说：“你要是我的学生啊，在一九九二年你还设计这么个破系统，肯定让你挂科。”就是说给他F嘛，F挂落了。然后紧接着后面就有几个人，态度就不一定了，有的是支持Linux，有的是支持UNIX，看起来支持Linux的多一点。

紧接着就是说UNIX的作者Ken Thompson现身了，他只回了一个帖子，后面没有了，他说：“我同意微内核是趋势，但是目前来说你实现整体内核更容易一些。”这个帖子这样一出呢，几个人就开始赞扬这个：“哎呀，Ken Thompson开始问他问题。”结果他再也没有回过。

等了一会啊，林纳斯又上线了，大概是隔了一天吧，不是等了一会儿，隔了一天，早上十点半左右发的帖子，那帖子很长，估计打字你也得打一个小时。我想的是，很可能就是林纳斯九点钟起床一看，教授的回帖，可能脸也没洗，牙也没刷，吭哧吭哧就打了一个小时，加上润色一下得反击嘛。技术细节我就不说了。

关于这个教授说：“如果你是我的学生的话，你肯定挂科了。”林纳斯这样回复的说：“真是谢谢你哈。”你看这种反话，说的真是谢谢你，就算不是你的学生，我的成绩也很烂。你不用不用说那种冠冕堂皇的话。紧接着呢，一大波人就开始喷这个安德鲁教授嘛，可能那些人都是花了169元的用户，毕竟你花了169元的用户，你肯定有所期待嘛。所以有点问题，肯定喷教授，反正也不认识。后来喷的我就看着有点心疼这个教授。

这个时候呢，教授就憋了个大招，他回复了一个叫罗伦斯的用户，就说了一通技术。先说技术，然后大家不都说你这个东西很落后嘛，然后呢他就开始推荐论文。跟我们吵架，吵急了，也是说说的差不多。我们以前是吵架，吵急了也就像研究生导师让学生最好多回去读点书一样。他这里就是推荐论文嘛，说你最好就是读读论文，就这样。

接下来呢，这个支持教授的人也有，毕竟教授也不是什么喷子，论文也发表了很多，还有操作系统实战派的教授。随后呢，教授又发了个大招，因为当时好几个人说这个Linux是为了赚钱嘛。安德鲁教授，也就是开始含沙射影地说了：“你们啊，真是Naive，是吧？你们以为Linux就不是为了赚钱啊，他也是想控制这个Linux源代码啊，你们都被骗了，我这也是老江湖了，身经百战，见得多了是吧？西方哪一个国家我没去过。”反正就吹他的资历嘛。

然后Linux就接过了话题，然后他又回帖，斩钉截铁地说：“这一点很精彩，我不会控制代码。”然后又解释了一下Linux的整个理念。紧接着呢，又出现了一个叫做David Miller的，就是我说的那个大牛，日后在Linux内核界呼风唤雨好多年的那个。然后当时就发了一个帖子，当时呢他还没有用过Linux，也没有用过UNIX，就问了一些问题给教授。同时呢，他还赞扬了一下Linux。但接下来呢，就是Linux和教授都没有再回复。

这个时候管理员就出现了，就了结了这个帖子，就是：“大家哎呀，差不多够了是吧？我已经给Linux操作系统开了一个频道。如果你有关去谈Linux嘛，就去那边，这里呢咱就留着谈UNIX。大家也别吵了，吵得很那个啥也不礼貌，是吧？”那叫“激情之完结”，最后还用了一个词叫“激情之完结”。

从此呢，这个Linux和UNIX大路朝天，也就各走一边。再后来我还看到过，哎，有人采访这个教授，他还接受采访。他说：“哎呀，当时也没有什么，也没有什么恨啊。”Linux也说没有什么恨，其实跟我们现在想的不一样。因为现在有些人你这样说，他一句压制必报，他搞你好几年是吧？

OK，这一期到此为止。
