---
title: "安卓系统的前生今世"
editor: visual
---

在开始说安卓系统之前，先说一点感想。我在构思这一期音频的时候，正在骑着自行车去接孩子放学。在回来的路上，儿子坐在自行车的后面，不停地唠叨着学校里的事情：老师罚了谁，谁又因为做错了一道题被罚；谁丢了橡皮，不小心砸到了前排的同学，结果也被老师罚了。他就这样说个没完没了。

这个时候，我突然想到了张爱玲的一篇文章，叫《童言无忌》，里面描述的也是这样一个场景：小学生和家长无休无止地说着，而大人则懒得搭理。这个时候，我突然意识到，我做这个音频节目，也像是处于类似的情景。我就这样唠唠叨叨地说个不停，毕竟像我这样一个默默无闻的程序员，如果说话想让别人听，只有一个方法，就是成为一个很大的人物，比如像马云、马化腾那样，干出一番惊天动地的大事业。到时候，就会有各种各样的自传问世，也就不怕没人理了。

但是，要想成为一个这样举世瞩目的大人物，对我来说，基本上是遥不可及的事情。到时候写一本或者是编一本自传，希望太渺茫了。所以这个音频节目，更像是我随时随地把我想说的说出来，免得以后太压抑了。等到老了以后，一发不可收拾，像清朝的左宗棠一样，老了以后只干一件事情，就是骂曾国藩。不过，任何时候，曾国藩都不是他晚年的唯一话题。所以我要在我年轻的时候，先把压抑在心里的话说出来，以免老了以后成为一个超级话痨。

------------------------------------------------------------------------

好了，开始说正题。我们都知道，安卓系统是谷歌的产品。在现在的市场上，除了苹果就是安卓，当然还有Windows Phone和黑莓，但后者都太小众了。再说了，黑莓现在也在使用安卓系统。

我在看谷歌的一本书的时候，那本书的名字叫《In the Plex》，作者是史蒂芬·列维。在书里，他就写到佩奇非常有先见之明，他很早就认为将来就是手机的世界。然后他恰巧碰到了安卓，马上就花了5000万把安卓买了下来。我非常推荐这本书，《In the Plex》里面还提到了谷歌退出中国的事情（如果觉得中国版的话，这一段应该给删除了）。这本书还是非常值得看的，但是浏览一下就好。这本书不像国内的一些书，比如说前段时间618的时候，我在京东买了一本写刘强东的书，里面就觉得吹得有点过头了，把刘强东说得跟先知一样，啥都预见到了。不管是大困难还是小困难，最后反正都是刘强东赢，最后都成了刘强东的勋章。

在谷歌购买安卓之前，安卓团队是在安迪·鲁宾的带领下研发出来了一个非常小众的手机。这个手机的名字叫T-Mobile G1（这里我纠正一下，不是“sad cake”手机）。在这里，我非常推荐大家关注一下我自己的微信公众号“软件那些事儿”。如果大家懒得关注这个公众号的话，还是建议大家去搜一搜这个手机，看看它长得啥样子。然后比较一下这个手机和当时市场上的手机，尤其是跟诺基亚的那款N-Gage手机，你看看是不是有很大的创新。但是在这里，我不是说它有超前的设计，我的意思是英雄所见略同，这两个手机真的还挺像的。

当时，T-Mobile G1手机的用户有两类：一类就是追求时尚的年轻人；另一类呢，就是硅谷的工程师。这个手机可以这样操作：打开屏幕，然后露出键盘，有点像超级小型的笔记本电脑。好像索尼也出过这样一款可以放在牛仔裤后面的兜里的手机。

在2005年7月11日，谷歌就宣布购买了安卓。而在此之前的两周，安迪·鲁宾曾经试图把这个安卓手机操作系统卖给三星。后来安迪·鲁宾也讲到过这个故事：当时他们团队总共7个人，然后去三星推销安卓。三星一下子来了20几个人，齐刷刷地站在会议桌旁边，他们也不坐下。后来等到三星的CEO进来以后，他们这几个人才坐下。这20几个人坐下以后，用安迪的话来说，这就像是一个军事法庭，非常肃穆。然后安迪就开始讲这个安卓系统，等他讲解完了，所有的人也都不敢说话，因为CEO还没开始说话嘛，其他人也不敢说。最后CEO的助理和CEO低声窃窃私语了几句，然后这个助理就说：“你是在说梦话吗？你们只有7个人，怎么能够征服世界？”然后这20几个人就一起嘲笑他们。

在接受了一番嘲笑以后，毕竟CEO先定了一个调子，这20几个人就可以说话了嘛。在接受了一番嘲笑和戏弄以后，会议就以三星比较高兴而结束，毕竟看了个笑话，心情很不错。安迪一行这7个人就有点失望，毕竟被嘲笑嘛。好在两星期以后，他们就去了谷歌，谷歌当场就宣布购买了这个安卓。在这个时候，三星听到这个消息以后，这个CEO的一个助理马上打电话给安迪说，能不能开一个紧急的会议。三星也非常想收购安卓。

这个时候，我突然就想到了前面几次我讲到的类似的故事：有TPK去诺基亚推销电容屏，然后就被拒绝了；诺基亚不买这个电容屏，最后苹果买了；微软和索尼当时拒绝购买体感设备，然后任天堂买了以后就生产了Wii；还有一个就是卡马克当时在PC机上做出了横版的移植，移植了横版的马里奥，然后去找任天堂，任天堂也没买。最后卡马克又做出了这个《半条命》，这几件事情可以说明一个问题：也就是说，如果程序员追一个女生追不上的话，也不见得是坏事嘛，说不定有更好的事情发生了。虽然这有点阿Q精神，但是呢，这个真的不值得伤心很久，更不值得去跳楼。每次我在新闻上看到说某一个人为情所困就跳楼自杀了，我就很恼火。这种人，就应该……哎，不说了。

------------------------------------------------------------------------

安卓之所以叫这个名字，是因为它的创始人叫安迪，安卓的意思其实就是安迪的小玩意。在被谷歌收购以后，安卓部门获得了很大的权利。谷歌基本上是要钱给钱、要物给物，而且他们这个部门想招聘谁就招聘谁，谷歌完全不用管。但是，毕竟被谷歌收购以后，也得服从谷歌的一些规定。比如说，当时谷歌就规定员工不能开豪车，比如说宝马三系这种车。当时的谷歌公司的CEO都是开丰田的Prius，就是那款混合动力车。这款车最主要的买家就是那些大学教授、公司管理层。据说在美国，警察一看到开Prius的这种车都不查，因为开这款车的人根本不可能是罪犯。而当时被收购的时候，罗宾早就卖了好几家公司，他开的是定制版的法拉利。当时的价格能买十辆、二十辆Prius这种车，所以他也只好不好意思开车去上班了。

在被收购以后，为了解决Java的版权问题，谷歌花了不少钱。据说当时为了能让Java运行在安卓上面，做了非常多的修改，修改的代码数已经超过了Sun公司的限制。后来Sun公司被收购以后，甲骨文又开始和谷歌打官司。所以第一期我也讲了这个Java的前世今生，至于这个官司到底谁输谁赢，只能拭目以待了。

安迪当时的愿景是开发一款运营商愿意推广、设备商喜欢、软件开发者愿意开发、用户还很喜欢的手机操作系统。就目前的情况来看，安卓应该算是非常非常成功了。

在安卓还是个半成品的时候，苹果就发布了一台iPhone手机，就是第一台。当时一位安卓工程师说：“说实话，iPhone的发布严重打击了安卓团队的士气。当时我们觉得这个世界末日就要到了，这次我们的对手可是苹果呀！当时苹果就像是耶稣再次降临人间，我们肯定是毫无办法了。”但是安迪·鲁宾肯定不是那种轻易服输的人。在看到iPhone的时候，他当时正在去开会的路上，他让司机赶紧在路边停下，在路边看完了现场发布会。然后和同事说：“哎，我们还是不要先发布我们的手机了，我们的手机没有发布就已经落后了。”在几周以内，安卓团队就改变了策略，他们一边一定要开发一款超过iPhone的手机。当时他们内部有一款项目代号为“Dream”的手机。当时搭载了触控屏的手机，已经是安卓开发的重点了，并且打算在2008年的秋天发布这款手机。

在当时，苹果公司还和安卓公司（就是和谷歌公司）还是亲密的伙伴，他们共同的敌人是微软。苹果公司发布iPhone的时候，当时还邀请了谷歌公司的CEO埃里克·施密特上去讲了3分钟。当时施密特还说要祝贺苹果手机大卖。而与此同时呢，在谷歌公司的内部是为苹果开发那个地图、搜索引擎，还有YouTube这3个软件。当时他们已经能看到苹果的原型机了，并且可以分析苹果使用的是哪一种CPU、哪一种触控屏。当时可以说除了苹果自己，谷歌最了解苹果手机。乔布斯甚至还为谷歌的图标找出了一个bug。

所以在后来这两家公司反目成仇以后，乔布斯说：“如果有必要，我将会用尽最后一口气，花尽苹果银行里剩下的400亿美元，也要摧毁安卓。因为安卓是偷来的产品。”根据我上面提到的那本书《In the Plex》的叙述，按照我本人的价值观，我觉得如果那本书里讲的是正确的话，我认为谷歌当时做得确实有些不厚道，和他们自己宣传的“自己从不作恶”的广告还是差距有点大。

比如说，当时安卓开发的主力机型叫Sooner，是一款非触控屏的。在后来谷歌就知道了苹果这个触控屏了以后（至于怎么知道的呢，也只能乱猜啊，或者根据网上一些传闻），因为当时谷歌的CEO埃里克·施密特还是苹果董事会的成员，可能见过。谷歌就开始做这个Dream这款机器，就是触控屏的了。而且苹果当时是Safari团队，谷歌拼命地从这个团队里去挖人，做这个WebKit版的Chrome浏览器。

当时苹果手机的解锁方式，就是滑动解锁，这样滑一下就能解锁。但安卓手机也可以实现类似的解锁方式，不过是通过几个点，比如9个点，可以设置最下面的3个点，通过一定的滑动轨迹来解锁。然而，乔布斯得知这一消息后非常恼火。他表示，如果安卓设置了通过滑动3个点就能解锁的功能，他将会立即提起诉讼。

在乔布斯的官方传记中，也曾提到过这件事。乔布斯当时感觉被背叛了，因为史密特在研发这款手机时，仍然是苹果公司的董事，对苹果的一举一动都了如指掌。史密特曾表示，他们研发的是带键盘的手机，与苹果不构成直接竞争，而是与微软等公司竞争。然而，这款手机发布后，却直接与苹果手机形成了竞争关系。

后来，史密特可能也觉得不好意思了，最终退出了苹果的董事会。在乔布斯病重的时候，史密特还去看望了他。但据网上的一些小道消息说，乔布斯至始至终都没有原谅史密特，认为他是个小偷。

另外，史密特以前在Sun公司推广Java，他其实是个很厉害的人才。他与比尔·盖茨、鲍尔默等人在商场上都有过交手。但这个人还有更厉害的一点，就是在情场上也是一等一的高手，情人多得数不清。只要在网上输入他的名字和“情人”这个关键字，就能找到很多相关信息。他的情人中有主持人、音乐家、钢琴家、摄影师等，各种各样的人都有。

既然扯到这里了，我们再来说说泡妞这个问题。对程序员来说，找女朋友可能比较困难，因为程序员大部分都是男性。但其实泡妞高手是不分行业的，每个行业都有这种顶尖高手。

说到这里，我突然想到了一个泡妞高手，他就是哲学家、数学家罗素。罗素经常写书谈论幸福之路，要大家重视家庭、珍惜爱情什么的。但他自己本人却经历了多次结婚离婚，情人无数。而且，他的情人中还包括各种各样的人，甚至包括他老师的妻子和他学生的妻子。这在中国人看来是非常不道德的。

然后，我突然想到了一个泡妞的菜鸟，他是意大利的物理学家赛格雷，他获得了诺贝尔物理学奖。他写了一本自传叫《永远进取》，里面讲述了他年轻时的故事。他大概十五六岁的时候，对异性非常痴迷，但自己的交际能力很差。他找不到女朋友，就自己解决生理需求，但之后又觉得罪恶，于是向哥哥诉苦。他哥哥给他看了一些保持心态健康的书籍，类似于正能量的内容，但他觉得越看越郁闷。

他哥哥是个什么样的人呢？他哥哥从来不看这些书籍，却经常逛妓院、泡妞、吸烟、喝酒，什么都会。他在哥哥的抽屉里发现了安全套，但自己也不知道怎么用，哥哥也不教他。他一直很郁闷。所以，我们不能在很多私事上寻求别人的建议，有时候亲哥哥也不一定靠谱。

不过，我还是很推荐大家看看赛格雷的这本自传《永远进取》。我觉得它写得很真诚，很少有这种自传写得这么真诚。里面还有一个很搞笑的事情：为了缓解赛格雷青春期的旺盛精力，他妈妈让他去学习跳舞。结果他妈妈可能认为跳舞是体力劳动，累了就不想女人了。然而，他的舞蹈老师是个漂亮的姑娘，跳舞时穿得很少，他简直被迷得神魂颠倒。他甚至希望她能在床上教他跳舞。

好吧，这一期电台就到这里吧。
