---
title: "Linux传奇2：Linus的童年时光"
editor: visual
---

回到1980年，Commodore公司发布了史上第一台销量超过百万台的家用计算机。

在1980年，大部分的计算机都会提供16K的内存。但是这款电脑只提供了3.5K的内存。当同时代的电脑都提供了彩色显示器的时候，而这台电脑只能接上电视，显示每行22个字符。

为什么这样一台远远落后于时代的机器，竟然卖了上百万台呢？答案就是便宜。当同时代的电脑售价高达3000美金的时候，这台电脑的售价是299.99美金。便宜就是王道。这台电脑几年的时间，销量迅速突破100万台。

如果公众号的读者有好奇宝宝的话，推荐用安卓下载一个Commodore VIC-20的模拟器，来体验一下这台电脑的操作系统。这台电脑其实更类似于一个小霸王学习机。我在公众号里放了一张图片，真的是很复古的样子，像一个厚厚的键盘，这台电脑插上电视就可以运行。我下载了VIC-20在安卓上进行模拟，费尽心思，我在上面终于编译成功了一个BASIC程序，打印出了“Hello World”。

说实在的，这是我第一次运行BASIC程序。话说在我小的时候也有一台小霸王学习机，但是呢，我只用它来玩游戏。我几乎知道《马里奥兄弟》任何一关的任何技巧，都是自己摸索出来的。说真的，我当年玩起《马里奥》来可以憋尿，憋好几个小时，以至于最后实在忍不住了，就去厕所，但根本尿不出来，就是肚子疼。

其实呢，小霸王学习机上也是有一个BASIC编程语言的环境。不知道听众中有没有人年龄比较大了，而且还用过小霸王学习机。但是呢，我看过那个BASIC编程的环境，但是我从来不知道它是干什么用的。我打开过好几次，但是呢，完全不知道怎么下手。过了很多年，我都上大学了，我才恍然大悟，原来那个东西就是BASIC编程啊，这就是后知后觉吧。

在一九八一年，Linux的外公就买回来这样一台VIC-20的机器，接上电视，就让Linux和他一起玩编程。在Linux的自传《只是为了好玩》里，Linus说，他的外公希望和他一起体验其中的乐趣，也试图培养Linux对数学的兴趣。当时这台机器是唯一只能支持唯一一种编程语言，就是BASIC。Linux呢，就开始研究那台计算机的使用手册，并试着把上面的示例程序都敲出来。用他的话来说，那感觉棒极了。BASIC呢，就是Linux的启蒙编程语言。

在这里，我这个公众号的一贯风格就是在犄角旮旯的地方深入挖掘。这次呢，顺带挖一下BASIC这门编程语言的历史。

在1950年，普林斯顿大学，一个统计学的在读博士机缘巧合之下用了一台IBM的机器。当时呢，用完之后，他就开始念念不忘了，因为这个玩意太好玩了。在50多年以后的2001年，他曾经接受采访，鼓励那些对编程心存畏惧的年轻人。他说：“对编程的人来说，编程就是快乐的。”但他的英语原文是：“For people who program, program means fun.”这个人呢，就是日后被称为BASIC之父的托马斯·库尔茨。

此人毫无疑问就是个编程天才。早期的时候，他使用的是汇编，但是他觉得很难。他曾经在某个项目中耗费了巨量的时间，最后以失败告终。他回忆说，在IBM大型机器上用汇编编程序，浪费了自己大量的时间。后来他尝试了一下IBM公司推出的FORTRAN语言。该语言在刚刚推出的时候备受嘲讽。这个以后有机会，我想再做一期FORTRAN语言的历史。毕竟在一篇文章里挖两个语言的坑有点受不了。所以呢，这个BASIC语言我也简略地提一下，FORTRAN语言的历史就先不说了。

托马斯·库尔茨曾经回忆说，他用了5分钟，就觉得心清气爽，和汇编语言相比，FORTRAN节省了我大量的时间。但是呢，如果再简单一点就好了。

他从普林斯顿大学的博士毕业以后，就去了达特茅斯大学去当老师。期间呢，他和他的同事约翰·凯默尼就想让文科生也可以使用计算机编程。于是呢，他就创造了BASIC。

他这个同事，约翰·凯默尼呢，也绝对不是等闲之辈，和这个BASIC之父是校友，都是普林斯顿大学毕业的博士。这个约翰·凯默尼的有一份工作，就是当爱因斯坦的研究助理。凯默尼曾经回忆过爱因斯坦对计算机的一些预言。所以我们也可以看出，爱因斯坦不但物理弄得好，对计算机的预言也非常的准确。但是呢，这个预言和本文也没什么关系，就先不扯了。

BASIC语言的简称，它并不是说是基础的意思，而是英语单词的简称。它全称叫Beginners' All-purpose Symbolic Instruction Code。它其实翻译成中文，就是初学者通用符号指令代码。

这门语言一推出，就受到了编程初学者的热烈欢迎。同时呢，还受到了一些编程中等水平的人极尽所能的嘲讽和谩骂。基本上，你能受多少的欢迎，就要受多大的嘲讽。

在这里多说一点，就是这些喜欢骂人的人，尤其是喜欢骂这个BASIC语言的人呢，或者是直接喜欢人身攻击的人，其实水平都是一般的，不怎么高，可能比初学者高一点吧，但是肯定高的不多。

在前几期的文章里，我也曾经说过，这个Linux也比较喜欢骂人，但是呢，他这个骂人跟搞人身攻击的人还是不同。因为他骂人的话基本上都是对事不对人。比如说骂这个NVIDIA啊，我还没有见过他们只骂单纯的某个人是傻逼什么的。基本上的套路就是骂这个人做的这件事比较傻，但是他好像还从来没有骂过某个人比较傻。

在我们这边互联网上吵架的基本上都是直接对人不对事，很多都是这样。当然也有对事的，比较少。但是呢，BASIC的命运就比较苦了。因为这个新生语言，包括现在还是受到嘲讽，这个嘲讽可以拉一火车了。我觉得这些嘲讽BASIC的应该都不怎么厉害，都应该算是菜鸟。

我看过网易那个公开课上有一个课程，哎，那个教授就自嘲说：“哎，我就是学的BASIC，就大部分人都说我一学了BASIC，这个脑子就坏掉了。”其实他当然是在自嘲了。MIT的一个编程的课我还看过。

但是呢，BASIC出现以后，马上就有人发现了商机。在BASIC推出不久，市面上就有的BASIC版本就已经几十个了，包括苹果、微软都有自己的BASIC版本。初学者呢，也非常喜欢这个语言。比如说微软的Microsoft BASIC，就是微软的第一个商业化的产品，这个产品真是取得了巨大的成功。

在这里我再推荐一本书啊，叫《Inside Microsoft: How the World's Most Powerful Software Company Creates Technology for Our Future》。就是说如果有人因为我英语读得也很烂，如果有人看我微信公众号的话，可以把这个书名输进去，然后一搜，这是一本书，不知道有没有中文版。因为我曾经有一段时间就特别喜欢看英文版，结果大学又读研究生什么的。后来英语还慢慢地变得比较好一点点了。当然，跟比较厉害的还是差很多，但是看技术书问题不大。所以我也希望大家，如果是程序员的话，真的把英文搞得好一点，还是有一些作用的。

比尔·盖茨就曾经在那本书里说：“BASIC一直是我们成功的法宝。”就是说，对，我们就是微软嘛，就因为这本书是讲微软的故事，可见BASIC在盖茨心中是非常崇高的地位。比尔·盖茨呢，让BASIC在4K的内存里就流畅地运行。他多次说过这件事情，他说在他所编写的所有程序中，BASIC是最让他感到自豪的。

再说一个花絮，就苹果公司也有自己的BASIC。当时呢，沃兹就写的是BASIC的解释器，但是呢，他一直不让BASIC支持这个浮点数的运算。当时乔布斯就推了他很多次，沃兹也不怎么理他。嗯，沃兹可能是苹果公司唯一敢不理乔布斯的。乔布斯也从来不骂沃兹，乔布斯还是很佩服沃兹的，他曾经说过：“反正这一切都是沃兹弄出来的嘛，随他怎么搞了。”然后呢，当时乔布斯就和盖茨认识了，即使不算朋友的话，也算是熟人，就求助盖茨问他能不能帮忙写一些代码，让苹果的解释器，就是BASIC解释器，支持浮点运算。然后比尔·盖茨就答应了，就订好机票赶过来，写完之后呢，第二天就订机票回去了。所以说呢，比尔·盖茨的代码水平也是比较高的。

对了，这时候我突然想起了国外有一个Quora上面有个比较热门的问题，就是说比尔·盖茨这个代码水平怎么样，大家可以搜一搜，非常的厉害。很多人就说他代码水平厉害得不得了。

好了，现在我们再来说Linux。Linux说呢，他最初写的代码和初学者也没什么两样，都是显示一行字符串。他记忆中就显示了一个“hello”，然后呢，就跳转，不停地循环那个“hello”。哎，我在那个装了一个VIC-20的模拟器，我就在上面弄了一个这个东西。哎，大家可以试试。有人喜欢的话就搜一下微软的模拟器，不是安卓的模拟器，是微软模拟器的安卓版。

按照Linux自传中的记录呢，他的妹妹萨拉则提供了另一个版本的故事。他的妹妹说，Linux修改了代码，然后让显示器上无休止地显示一行字：“萨拉是最棒的。”他年幼的妹妹对这件事情还非常感动，但是Linux表示呢，他早就把这件事情忘得一干二净了，他根本不记得。

当时芬兰的孩子有很多是热衷于体育运动的，比如说踢足球啊、打篮球啊。但是Linux的父母离婚了。但在芬兰这种国家里，离婚好像对孩子没什么影响，他依旧能够经常见到他的父母，想跟谁住就跟谁住。在这里呢，我得对这个欧美人的离婚价值观表示十分的赞赏，尤其是欧洲。他说的这个芬兰、美国好像还不是这样。以我了解的信息，咱们中国这边就更差了。如果咱们中国这边，你一旦离婚的话，这个孩子如果判给了某一方，另一方想见到他就非常的难，对吧？孩子就会受到非常大的影响，因为整个家庭就不健全了。所以这件事情也搞得我这种35岁的老男人根本就不敢离婚，毕竟你还得顾及孩子的感受，是吧？所以一定要向欧美人学习。

你看，这个Linus的父母就离婚了，对他什么印象都没有，孩子想住谁家就住谁家。他主要还是想住外公家，因为外公家他有电脑嘛。但很可惜的是，在教了Linus四五年电脑以后，他的外公就中风了，中风以后随后就去世了。他的外婆在外公中风以后，也得了一种病，按目前的话来说，我认为应该是老年痴呆症，就经常忘事，然后就去公立的疗养院住了十年左右。而且这十年是很重要的一个现象。我猜啊，因为得了老年痴呆症的话，大部分人活不过九年，就九年左右就去世了。

在这十年中呢，Linus有时候就跟他爸爸住，有时候跟他妈妈住，他的妹妹也是一样，想跟谁住就跟谁住。就在他的外婆住进疗养院以后，他的妈妈就搬进了他外婆的房子里。在琳娜斯的自传里，他就说，在他家离婚以后，生活还是比较窘迫的。幸好他外公当年活着的时候是比较有钱，毕竟是教授，应该是比较有钱。他妈妈拿不出钱来的时候，要么去抵押股票，要么就让Linus去跟他的外公要钱。

他搬到外公家以后，就选了一个小的卧室，因为最大的卧室已经被他的妹妹选了。他在一个小的卧室里挂上了厚厚的窗帘，挡住阳光。但我就不知道他为什么要挡住阳光，因为芬兰是温度非常低的地方，一天的阳光也没几个小时。而且他说，在离他小床60厘米的地方，放着他外公留给他的遗物，就是那台带给他无数快乐的电脑。

好了，这期的节目就到这里，下一期再接着讲这带给他无数快乐的电脑。
