---
title: "第18期  Blogger谁从毫末见参天"
editor: visual
---

唐朝的诗人陆龟蒙，曾经写过一首诗，里面的两句我非常喜欢：“谁从毫末见参天，又到苍苍化十年。万古清风吹作籁，一条寒柳滴成川。”合抱之木，生于毫末；每一棵参天大树都起源于一棵小小的种子，经历过风雨的历练，躲过动物的摧残，从一棵不起眼的树苗，向着太阳的方向生长、生长，直到长成参天的大树。

在IT的历史上，现在风光无限、呼风唤雨的人物，当初也是一棵小小的树苗，经历过嘲笑，经历过挫折，快速地改变着自己，顽强地满足着瞬息万变的需求，直到经历过无数个推倒重建、再推倒再重建的过程，然后被媒体报道，一夜成名。是的，这个一夜成名也许发生在第300天、第600天或者第1000天。没有哪棵参天大树，是一夜长成的。合抱之台，生于毫末；九层之台，起于累土；千里之行，始于足下。让时间倒流，回到最开始的地方。

让我们来看看这些改变世界的企业家所承受的痛苦和幸福，所经历的嘲笑和赞美。在一九九七年，一个离旧金山55公里的小镇上，三两辆汽车驶过尘土弥漫的街道，扬起更多的尘土和刺鼻的尾气。路边，一个年轻人骑着一辆破旧的自行车，汗水混合着尘土，在他的脸上留下了一道又一道的痕迹。每天，他都要骑着这辆破旧的自行车往返于公司和他花费了600美元租下的小窝——一个建立在车库上、协和一般大小的小房子。他希望能有钱买一辆汽车，能去旧金山上班。但是，信用卡里高达5万美元的贷款，让他很快打消了这个念头。旧金山虽然很好，可是下一个月信用卡的欠款不允许这个年轻人有太多不切实际的想法。

这个离旧金山55公里的小镇，这条尘土弥漫的小路，让他想起了小时候在农场的样子。他的父亲和母亲在美国中部一个州经营着一家农场，这是一个几乎毫无存在感的内布拉斯加州。如果不是世界首富巴菲特的总部，也就是在内布拉斯加州的奥马哈，几乎没有人知道这个州还有什么其他值得炫耀的东西。威廉姆斯家族在这里种地、养牛、钓鱼、骑马，平静而坚定地生长在这片荒凉但却自由的土地上。当所有的小孩都喜欢骑马、钓鱼、打猎，将猎物的内脏掏出来剁成香肠的时候，却有一个孤独的小男孩沉迷于制作模型，拆掉家里的农具，然后再组装起来。等到再大一点的时候，他沉迷于计算机，但是却从来没有对种地、养牛和橄榄球感到过丝毫的兴趣。这个与众不同的小男孩，他的名字叫做威廉姆斯·埃文。

埃文上学的时候，满脑子都是古怪的想法，高中时候的孤僻，慢慢地变成了大学时候的孤独。在内布拉斯加大学读了一年以后，为了能找到一份工作，他怀揣着巨额的学生贷款，开着一辆老旧的雪佛兰货车，拉着他全部的家当离开了学校。行驶到3000多公里外的佛罗里达州，没有钱住酒店，他就住在车里。这次远行，让他认识到了生活的艰辛，他收获了一次被骗的经历，以及更多的信用卡欠款。怀着满心的沮丧，他又开了3000公里，回到了内布拉斯加州。这个没有学历的年轻人，换了一个又一个的工作，离开了一个又一个的城市，失败和欠款始终跟着他，一切都变了，唯一没有变的是对编程的热爱，和一台始终跟随他的电脑。他一路走，一路推销着他觉得伟大、别人觉得可笑的想法。他说，总有一天，世界上所有的人都能够发出自己的想法在网络上，每个人都可以自由地表达自己的想法，不需要学习编程。

是的，每个人。在一九九九年的夏天，埃文独自写了一个网站，任何人都可以在这个网上写下自己的文章。他给这个网站起了一个名字叫blog。当时这个词汇并不存在，因为只有创造一个不存在的词汇，他才能够注册一个域名。随着blog的慢慢流行，带给埃文的是巨额的账单，和朋友的分崩离析，他再也没有钱支撑下去了。朋友相继离开，只剩下一台电脑和他客厅里的一片狼藉。本来5个人的团队，现在只剩下他独自一人了。从一九九九年的夏天到两千零一年，这段折磨人的黑色岁月，blog始终起起伏伏，没有钱付账单，不看好blog的人嘲笑他，所有的这些苦，只有埃文自己知道。也许还有满地的红牛罐知道，银行催款的人知道，但是没有朋友知道，因为埃文已经没有朋友了。

随着blog用户的增多，靠着热心用户的捐款和微薄的广告收入，埃文逐渐不再那么贫穷。甚至在两千零二年，他还有钱雇了几个程序员，办公室也不在他的客厅了。他花了每个月400美元，搬到一个只有16平米的阴暗潮湿的房间。blog和硅谷有钱的IT公司不一样，这里没有啤酒，没有零食，也没有活动的空间，甚至厨房里还得安排程序员在里面办公。这里有的只是一群经常发不出工资的人，还有一个让人不可思议的梦想。blog继续进化，一部分用户继续谩骂，另一部分用户则继续赞美。在赞美和谩骂中，blog的功能逐渐完善。终于在两千零三年的时候，有100万篇blog被发表出来，媒体也相继报道了这个一夜成名的网站。这个1000天以后才一夜成名的网站，google等好几家公司开始和埃文联络，试图收购blog。在两千零三年二月十五日，埃文和谷歌宣布消息，blog被谷歌收购。

时光再回到一九九七年，那个在离旧金山55公里的小镇上，那个骑着自行车的风尘仆仆的少年，那脸上的汗水和尘土。他当时想，真希望能有一些钱，能够去旧金山工作，买一辆汽车，再也不用骑自行车上下班了。
