---
title: "第17期 决战光明顶--编译器的圣战"
editor: visual
---

在1990年代，电脑的市场上曾经爆发过一场硝烟弥漫的战斗。战斗的双方是当时编译器的王者——波兰德公司和操作系统的王者——微软公司。两家公司缠斗了十几年，把战火从编译器的战场烧到了数据库的战场。

在这场战斗中，Borland和微软分别使出各自的杀手锏，在打击对手的同时，也把编译器的技术提高到了一个前无古人的境地。

命运往往喜欢和人开玩笑。命运之神把成功和希望交到Borland的手里，在一次次短暂的拥有之后，命运之神又将这所有的一切再次夺去。每次的成功都像是为了承受更大的失败。Borland的公司就这样受尽折磨，一次次地穿梭在悲喜之间。

Borland公司的Turbo Pascal、Turbo C还有Turbo C++，将Borland从一个默默无闻的公司推向了王者之巅。同期的微软则推出了Visual C++，也攻城略地，双方互相缠斗。在C++的战场逐渐被微软蚕食以后，原本沦落的Borland公司竟然在绝境中强力推出了Delphi，上演了绝地反击的好戏，随后又推出了C++ Builder的产品。

反之，微软的Visual C++再后来战火又烧到了Java领域。Borland推出了一个Java工具，叫JBuilder，在Java开发工具的领域，Borland崭露头角。在连续推出几个版本之后，JBuilder 7推出以后，Borland在Java开发市场上形成了唯我独尊的局面。微软公司自然不甘落后，推出了.NET产品来和Java开始竞争。毕竟和微软竞争，微软毕竟是这个时代的罗马帝国。Borland就像不肯过江东的项羽一样，经过了很多年的战斗，在2009年因为经营不善而被其他公司收购。

在和微软竞争的这20多年里，Borland公司多次绝地反击，打出了精彩的战斗。虽然最后战斗输了，但是仍然是我心中可歌可泣的英雄之一。Borland公司就是这样在推出了一个又一个的产品，所有的这些产品最终都散落在历史的角落，被人一个接一个地遗忘。现在谁还能记得当年那些耳熟能详的名字吗？Turbo C、Turbo C++、Delphi……直到现在，连Borland的公司也已经逐渐地被人遗忘。

在这场战斗里，我作为编译器的用户被迫参与其中。我在上大学的时候，做作业使用的就是Borland公司的Turbo C和Turbo C++。在当时市场上的集成开发环境主要有两种，一种是Borland公司的产品，另一种就是微软的产品。

就像所有的故事都有一个美好的开始，Borland公司成立于1983年，两个创始人，一个叫菲利普·卡恩（原文“可汗”为错别字），另一个叫安德斯·海尔斯伯格。这两个家伙到美国创业，这两位兄弟安德森负责编写编译器，飞利浦则负责其他的部分。在这里说一下，论技术的话，安德斯是目前世界上最顶级的工程师之一。如果算在编译器的方面，就是最顶级的工程师，连“之一”都不用加。

创业之前是非常痛苦的。没有资金，卡恩就去西餐厅端盘子赚钱，安德斯则在家里拼命地开发Turbo Pascal。两人开发完毕以后，决定成立一家公司。这两个兄弟当时住在洛杉矶，但是洛杉矶的价格太贵了。于是这两个人打算离开洛杉矶，找个便宜点的地方去创业。然后开车就去找，结果开到了硅谷，汽车没有油了。当时他们就下车，发现硅谷的风景还是不错的。于是就选择在这里创业。

当时还是1983年，硅谷远远没有现在这么热门，仍然属于是一个很不繁华的郊区。这对患难的兄弟从贫困中来，建立了一家令人尊敬的公司。当公司越来越大，这对患难兄弟的周围被越来越多职业经理人所占据。终于，飞利浦离开了自己的公司。失去兄弟的安德斯在公司的影响力也越来越弱，没有了当初亲密战友的资源。虽然作为公司的创始人之一，但是安德斯却没有能力抵抗管理层的力量。

在1996年，一辆豪华的轿车行驶到Borland公司的门口，轿车的主人邀请安德斯吃饭。饭桌上开出了百万年薪的条件。在Borland公司得知以后，马上对安德斯进行了安抚。但是这辆汽车三番五次地开过来，薪水早已加到了每年300万以上，还有数千万的签字费。请吃饭的这个人就是微软公司的比尔·盖茨。钱本来就不是问题。安德斯在备受管理层排挤之后，面对盖茨开出的终极条件——在微软可以拥有自己的团队，外加任意的资源，也可以任意地发挥——终于，安德斯和微软走在了一起。

在Borland公司管理层的排挤下，先是飞利浦离开了公司，随后，另一个创始人安德斯也被排除出了开发小组。安德斯亲手创造了Borland，却被管理层拒绝让他继续带领团队开发Turbo系列。出走以后，安德斯在微软依旧大放异彩，先后开发出了Visual J++和Visual C#。

对Borland的管理层来说，有一种胜利就是公司的彻底失败。现在，在编译器的市场上，微软的操作系统上，微软已经一统天下了，再也听不到另外的声音。此时的微软志得意满，在桌面领域再无对手。当他回头的时候，却发现人们却已经进入了手机的时代。
