---
title: "张嘴看世界——老朋友家的互联网长什么样子"
editor: visual
---

世界上到底有多少种互联网？这个问题简直就像是一道送分题，当然只有一种。

但是，昨天我看到了一篇写古巴互联网的新闻发布，在美帝国主义的网站cloudflare上（不是cloud flair）。这家网站是为了提高你网站的安全性和性能的，它可以提供拒绝服务式攻击的解决方案。我经常去他家的网站上看看有没有新的文章出来。昨天呢，我就看到了一篇写古巴互联网的文章，我就对世界上到底有多少种互联网产生了深深的怀疑。

所以，包括朝鲜的互联网、古巴的互联网、越南的互联网、老挝的互联网，这四个坚定的社会主义国家的互联网，是不是真的和腐朽的资本主义国家一点都不一样呢？

我仔细读了那篇文章，又找了其他很多的文章（在这里我就不一一列出了）。我简短的把我在网上找到的信息给大家罗列一下。每个人都有自己的智慧，至于真伪、对错，相信大家都能够在心里有个自己的判断。

让人感到意外的是，古巴的互联网是没有网络审查的，在古巴你可以随意的浏览facebook、google，还有youtube等服务。但是呢，古巴仅有5%的互联网普及率，而且这5%完全被政府管理和控制，只存在于政府的机构里和涉外的酒店，控制得非常严格。谁可以访问互联网？这种方法简直就是无防火墙胜有防火墙，达到了武术的最高境界——无招胜有招。没有墙，但是比有墙还厉害，因为政府决定了哪个人可以用这台电脑上网。

古巴普通人每个月的收入平均是16美元，教授高一点，二十美元，但是上网费是每小时两美元，一兆数据的费用是一美元。也就是说呢，一个普通的人辛辛苦苦干一个月不吃不喝，攒钱能够上八小时的网（如果他有机会被政府批准上网的话）。

但是呢，人类的天性就是追求自由、追求知识。古巴政府说古巴不能上网都怪美国，好吧，我觉得这个锅美国不背，也没人肯背。在美国的制裁下呢，这些向往自由的年轻人就建立了自己的网络。

主要是有两种网络，一种是叫移动CDN，属于大数据传输。这种网络的基本原理是什么呢？就是首先你得准备好一个1T的移动硬盘或者1T的U盘，每周把这个移动硬盘或者U盘的数据更新一次。这个1T的硬盘里有电影、杀毒软件，还有PDF的杂志（这些PDF的杂志大部分都是美国的，比如说《经济学人》、《商业周刊》等等）。这个移动硬盘里还缓存了热门的网站，比如说CNN、雅虎，所有的网页形式都是以离线的形式放在硬盘里。比如说你也有可能有facebook，但是有个缺点，就是你不能互动，只能看不能互动。这个移动硬盘里还包括很多的手机软件，比如说《植物大战僵尸》、《愤怒的小鸟》，都是以离线文件的形式下载好。然后就骑着脚踏车在大街上流传，真的是大数据传输，被这个1T的硬盘到处传。这个硬盘的数据是每两周更新一次，每次更新是两美元。虽然两美元在古巴是非常大的一笔钱（因为每个人每个月只能赚16美元，大概相当于100块人民币），但是也可以共享，就是说你只要几个人凑钱，就可以共享这个大数据，就是一个硬盘。

这个移动硬盘大数据的网络呢，古巴政府一直在严厉的打击，尤其是涉及批评古巴政府的，抓住以后呢，就丢到监狱里，这辈子肯定是别想出来了。所以呢，谁制造的这些移动硬盘，包括这些数据是怎么传过来的，都没人知道。也有人说很多屋顶上的太阳能都是一些卫星接收器，但也不知道。但是呢，这个谁制造的这些移动硬盘，谁更新的这些数据，始终是这个最高机密之一吧。

还有一个网就是Snet，就是Street的缩写，街道的缩写。这个网呢，跟互联网完全是隔绝的，完全不能够接受互联网，纯粹的局域网。现在据说有一万台机器左右，用户可以在这个局域网里玩游戏、下载电影，还能够网络聊天（就是局域网）。但是古巴政府说是因为美国的限制，古巴政府也经常会把这个局域网打压一下，因为这个局域网多了还是会有腐化的思想、腐化的行为。政府肯定是要保护人民不受不良网络的影响。毕竟是年轻人嘛，一定要在菲德尔·卡斯特罗和他的弟弟劳尔·卡斯特罗的领导下，坚决的以不上网的决心和美帝国主义斗争到底。

但是呢，还是这一小撮年轻人非法建立了这个Snet，但上面还是要自我审查，非常严格，因为你还是不想惹出什么事情来。如果你哪个人不知好歹，就在这个局域网上批评了一下古巴政府，只要你批评一次，就会被屏蔽6个月到一年。如果你不小心分享了一些色情的视频，那就终身屏蔽了，你这个网就再也上不去了，你这个网卡的硬件就被屏蔽掉了。

为什么说古巴政府对这个色情啊什么都这么严厉的打击呢？我觉得从乔治·奥威尔那本著名的《1984》上可以看出一些端倪。在那个书里就是这样写的嘛，那个女主角非常了解党在性方面搞禁欲主义的内在原因。因为两性关系的开发会开发出属于自己的小天地，在这个小天地里党不能控制两个人的爱情。因此呢，必须尽可能的加以摧毁，尤其重要的是剥夺了人正常的性生活，能够让一个人歇斯底里，而歇斯底里是一件很好的事情，可以把歇斯底里的疯狂转化为对战争的狂热和对领袖的崇拜。这就是在《1984》那本很著名的书里写的，如果有人想看的话，应该在网上搜一搜，《1984》乔治·奥威尔很好看，他还有另外一本书叫《巴黎伦敦落魄记》，也非常推荐大家去看一看。

如果有闲的，哎，你闲的没事干的话，我个人认为呢，像古巴这样的政府不让人上网，或者说他的政府的解释是因为美国的制裁不让古巴人上网，显然是不合时宜的。对于传播一些爱情片、动作片也管得太严了，包括自由恋爱肯定是人的基本自由之一嘛。古巴在这一方面也进行干涉，实在是让人有点大跌眼镜。这一点呢，在中国就没有这个情况。我觉得因为早就在井冈山的时期，人们就已经非常抛弃了这种封建思想。比如说那个时候我们只有30多岁的毛润之同志（就是毛泽东），就雄姿英发嘛，肯定也就冲破了封建主义的牢笼，就和贺子珍同志自由恋爱，也就住在了一起，完全没有考虑当时还在家带孩子的杨开慧同志。但是呢，杨开慧同志也非常的开明，没有任何怨言，包括周围的同志也没有人敢指手画脚。没想到现在100年过去了，古巴还这样搞。所以呢，我觉得古巴这样的国家肯定会被中国远远的甩在后面。

这个文章就到这里了。本来我还想写一下老挝和朝鲜的，老挝的倒是找到了一点点互联网的信息，但是朝鲜呢，实在是找不到。就是你说这个朝鲜民主主义人民共和国这个国家的名字就很奇怪，我们都知道是朝鲜，后来我才知道叫朝鲜民主主义人民共和国。朝鲜的互联网呢，我本来想找点信息，也讲个十来分钟看看，但是呢，真是一点材料都没找到，也不知道那个金正恩上不上网，还是朝鲜有另外一个互联网。

哎，讲到这里的时候，我突然意识到世界上到底有几种互联网。但是越想越不明白了，可能真的不是一联联的信息，而是多种。这个问题呢，我是搞不懂了。
