---
title: "智能手机背后的故事(下)"
editor: visual
---

看苹果手机研发的故事，会深刻体会到，开发一款开创性的产品会遇到诸多挑战。正如那句老话所说，吃得苦中苦，方为人上人。

苹果从一个濒临倒闭的公司，到如今一度成为市值最高的公司，这绝非仅凭所谓的“脑残粉”就能做到的。实际上，要找到如此多的忠实粉丝也并非易事。

当iPhone刚刚问世时，它对当时的手机市场产生了巨大的冲击。我记得那时我还没有毕业，用的是一台诺基亚N95手机。在读书期间，我和几个朋友曾试图为塞班系统开发软件。如果没记错的话，当时我们使用的是S60的第三版，它引入了一个签名机制。然而，诺基亚手机的开发环境当时极为复杂，远比苹果现在的情况要棘手得多。具体来说，如果你想分发软件给用户，就需要购买签名，类似于现代苹果每年99美元的开发者账户。但诺基亚的流程更为繁琐，不仅费用高昂（企业版价格好几千块），而且处理速度缓慢，可能需要数周时间才能得到账户。

当年我们几个同学想开发一款类似诺基亚来电通的软件，但当时还是研究生，技术水平有限。更糟糕的是，诺基亚有数十种不同的机型，键盘、喇叭数量和分辨率各不相同。这导致软件开发后需要匹配的手机型号非常多，让我们感到非常崩溃。最终，我们的软件虽然上线了，但稳定性不佳。在测试过的手机上表现稳定，但在未测试过的手机上可能会出现问题。

后来，苹果推出了iPhone，我们几个马上转行做苹果软件的开发。虽然当时苹果使用的是Objective-C，而我们之前用诺基亚时用的是C++，但我认为苹果的开发环境要简单得多，诺基亚则充满了各种坑。

例如，在内存管理方面，诺基亚和苹果都需要手动释放内存。诺基亚使用了一种称为“live”的机制，稍不小心就可能导致内存泄漏。而苹果虽然也需要手动释放内存，但它使用了一种计数器机制。然而，如果塞班系统检测到内存泄漏，程序会立即崩溃。我开发塞班软件的那段时间，软件崩溃的频率让我自己也濒临崩溃。所以，后来诺基亚倒闭时，我感到有些开心，真的，我一点都不怀念诺基亚。

我第一次见到苹果手机时，它给我留下的深刻印象是：下滑屏幕即可解锁。当时诺基亚需要按两个键才能解锁。苹果在设计iPhone初期，并没有采用玻璃屏幕，而是选择了有机玻璃。乔布斯和高管们认为，如果屏幕是玻璃的，一旦掉在地上就会碎裂，不如有机玻璃结实。

然而，有一天，乔布斯把一部塑料原型机和钥匙串放在口袋里，结果发现屏幕被磨损得不成样子。他询问原因时，一位中层管理人员狡辩说有一部玻璃原型机但没有通过跌落测试。乔布斯瞪着他，恶狠狠地问道：“你他妈的告诉我能不能把这个破玩意搞定？”

当时已经是2006年9月份了，距离iPhone发布还有4个月。在这个关键时刻，乔布斯希望更换iPhone最重要的部件之一——屏幕。后来，乔布斯通过他的朋友约翰·西里·布朗找到了康宁公司的CEO温德尔·维克斯。

乔布斯直接拨通了康宁公司的电话，要求与维克斯通话。但康宁公司的助理表示需要转达，乔布斯发火说我是乔布斯，要求直接接通CEO。助理不听，直接挂了电话。乔布斯只好向朋友抱怨，称自己受到了侮辱。康宁公司的CEO后来听说了这件事，打电话给苹果公司的总监，要求与乔布斯通话。但苹果公司表示需要先写一份申请并传真过来。

乔布斯得知此事后，对维克斯产生了兴趣。他邀请维克斯来苹果公司谈谈，询问是否能制造出一种硬度强的玻璃。后来，康宁公司真的制造出了这种玻璃。

这段故事在乔布斯的官方自传中有详细描述，我就不再赘述了。有兴趣的话可以去买本书看看，我觉得还是挺有意思的。我想说的是，这种玻璃强度非常高，是一种铝硅酸盐玻璃，通常用于高铁或直升飞机上，硬度极高。

其实玻璃本身的硬度就比金属要高，何况这还是加强版本的玻璃。所以，即使放在口袋里与钥匙串等物品摩擦，也不太容易留下划痕（当然，长时间不贴膜还是会有划痕的）。我的手机就是这样，一直裸奔，有时候也不知道口袋里放了些什么东西，用一段时间后就会发现划痕很多。不过后来我也不管它了，因为用不久就要换新的了。

第一代iPhone的玻璃并不像iPhone 4那样有弹性，而是经过后来改良的。提到改良的话，得提一下中国的玻璃制造商蓝思科技。这家公司原本是做手表玻璃的，后来解决了苹果公司的难题。蓝思科技的CEO叫周群飞，如果大家看新闻的话，应该能经常看到她是中国的女首富之一。

iPhone手机的玻璃非常薄，只有0.3毫米厚，和一张白纸差不多。iPhone的玻璃碎了以后，并不像普通玻璃那样碎成一片一片的，而是基本保持一个整体，有点像汽车的挡风玻璃。如果用砖头砸下去的话，它会裂成像蜘蛛网那样的纹路，但不会碎得很厉害，边缘也不会非常锋利。

接下来我们讲讲CPU。上一期提到过，苹果使用的是ARM的芯片。ARM刚刚成立时专注于做微型低功耗的芯片。然而，在20世纪90年代，市场需要的是高性能的芯片。例如，当时的硅谷图形公司（SGI）就嘲讽ARM的技术是雕虫小技。当时的CPU霸主是英特尔，现在的PC机霸主依然是英特尔。英特尔的产品价格从几十块美金到几千美金不等。我最近为了编译安卓软件速度更快一些，配了一台组装机，买了一个英特尔的i7处理器，大概是2500块左右。这个编译速度确实快了很多，因为我以前用的是i5处理器，相对便宜很多。

ARM不像英特尔那样自己生产芯片，而是转让设计许可给合作公司来生产。因此，很多半导体厂商都是从ARM公司购买其设计的ARM处理器，并根据不同的领域加入自己的设计。例如，ARM架构的CPU厂商有三星、MTK（联发科）以及高通等。现在很多手机都使用高通的ARM芯片，但苹果的CPU并不是高通的，而是苹果自己基于ARM架构深度定制的。

多说一点，我们电脑上的架构是x86架构，主要有两个主要玩家：英特尔和AMD。英特尔也有自己的移动芯片叫Atom，但我没有见过也没用过，听说耗电比较严重。在2010年的时候，曾经传出过苹果要收购ARM的消息，ARM的股票因此暴涨了很多。不过最后什么也没发生，后来苹果还是收购了几家芯片厂商，如原本设计Power PC处理器的Palm公司以及设计芯片的Intrinsity公司（一家被苹果收购的芯片设计公司）。苹果利用这些公司的资源对ARM芯片进行了深入的定制生产，所以在手机芯片上无论是速度还是功耗都基本领先于其他竞争对手。

讲完了玻璃和CPU，我们再来说说触摸屏。在2007年苹果发布会上，台下还坐着两位台湾人，他们作为核心员工坐在第五排，同样非常激动、泪流满面。这两位是触摸屏幕生产厂商宸鸿（TPK）的老板姜朝瑞和孙大明。这家公司研发成功了透明玻璃投射式电容技术。如果没有这项技术，iPhone最惊艳的技术之一——滑动解锁、双指缩放等根本无法实现。关于宸鸿和姜朝瑞在网络上和杂志上有很多报道，尤其是到台湾的繁体网站上搜索会发现更多信息。

姜朝瑞这个人也很有传奇色彩（当然，成功后的传奇色彩可能有所夸大，但我们可以简略了解一下）。宸鸿公司原本是做CRT显示器的（可能现在很多人都不知道CRT显示器什么样了，就是那种后面有个大屁股的显示器，非常沉）。姜朝瑞赚了很多钱后，在印尼建厂却被骗走了资金。于是他开始做触摸屏的监控业务，后来就专门做这个触摸屏业务。

当时还是1995年，离iPhone发布还有十几年时间。根据台湾杂志的报道，苹果和宸鸿公司的CTO（当时叫张恒耀）联合研发电容式触控屏，研发了两年多都没有成功。CTO多次向老板汇报说太难了，要放弃。老板先是痛骂他一顿再鼓励他继续研发。据说反反复复骂了九次又鼓励了九次之后这项技术才成功。因为当时的手机都是电阻屏的。

我记得小时候电视上经常有一个广告叫“商务通”，广告词是“呼机、手机、商务通，一个都不能少”。这个商务通当时就是电阻屏的，需要拿笔在上面写字。现在的电阻屏越来越少了，在工业控制上可能还用得比较多，但手机上电阻屏用得越来越少了。我上次用电阻屏的手机还是诺基亚5250，你得用力按才行。经常修剪指甲的人不好用，点不准，它也不支持多点触控，只能识别一个点。

这里还讲一个小插曲。在2005年的时候，姜朝瑞还没有和苹果公司合作开发电容触控屏。他当时坐飞机去芬兰向诺基亚推销电容屏技术，但诺基亚根本不理他。这让我想起了另一个人——被称为任天堂背后的男人汤姆·奎因。他在上个世纪80年代的时候开着自己的飞机在天空中飞行时突然想到应该做一个容易操控的飞机运动控制器。他搞了十多年后终于成功了，然后到处推销这个控制器。他先去微软家推销但被野蛮对待了（按他的话说）。后来他又去找索尼，结果索尼的久多良木健在演示时竟然睡着了。久多良木健醒来后只问了一个问题：“你这个破玩意能一美元生产俩不？”汤姆·奎因说肯定不行。也就是说在当时的久多良木健眼里这个技术顶多值50美分。不过后来任天堂机缘巧合地收购了这项技术。（这段任天堂的故事你可以在另一个音频里详细了解）

这一期就说到这里吧，我每期都想控制在15分钟左右。下一期再接着说苹果手机的故事或者安卓手机的故事。在苹果发布iPhone的时候安卓也在研发中只是当时安卓是带键盘的后来看到苹果的成功才取消了键盘。其实安卓在一定程度上是学习了苹果但后来大家也互相学习互相进步。
