---
title: "Doom的前生今世"
editor: visual
---

这几天，Steam 游戏上正在进行暑假打折活动，一直持续到7月5号。我就在 Steam 上买了两个游戏，一个是《Doom》，另一个是《垃圾车机械师》（注：原文中的《垃圾机械师》可能是误写，这里假设为《垃圾车机械师》）。

买回来以后，我就连续玩了很久的《Doom》，感觉非常爽。以前也一直玩，所以我就想这一期先做一个《Doom》的前生今世。

我非常喜欢《Doom》游戏，说起《Doom》来一定要提到两个人。这两个人分别是约翰·卡马克和约翰·罗梅罗。从某种程度上说，这两个人创造了《Doom》。卡马克是天才的3D引擎设计师，罗梅罗则是一个天才的关卡设计师。现在这两个人还在 Twitter 上很活跃（当然得翻墙出去）。

我把这两个人的 Twitter 账号说一下：罗梅罗的就是“\@罗梅罗”，卡马克的就是“\@aa_卡马克”。这两个人经常在推特上面互动，我经常去看看，但也就只是看看。

目前，卡马克在Oculus（一家做VR眼镜的公司）担任CTO，这是前一段时间被Facebook收购的那一家公司。不过我觉得这个虚拟现实眼镜这个项目有可能不会成功，原因就是它太丑了，你戴上那个眼镜跟戴个防毒面具差不多，实在没有美感。我觉得这种东西不大可能取得成功，非常小众。想想看，一个眼睛水汪汪的妹子，让她天天戴这么个丑东西，毕竟眼睛是心灵的窗户，结果你用一个那么大的东西把人家心灵的窗户给挡住了。

我觉得以后虚拟现实可能会成功，但是有可能是那种裸眼3D，就像是任天堂的那种裸眼3D技术，然后再怎么先进一些，起码不用戴那么丑的眼镜。总不能戴个像防毒面具一样的东西玩游戏吧，那实在是不好看。

目前，罗梅罗还是在做游戏方面的东西。前不久在Kickstarter上面集资，打算做一个新的射击游戏，游戏的名字叫《Black Room》。合作者也叫卡马克，不过这个卡马克跟以前我们讲的那个卡马克不是一个人，只是名字相同。这个卡马克以前也在ID Software找过工作，所以这两个卡马克之间肯定是认识的。

我来说一个花絮，就是我在讲任天堂的前生今世里也曾经提到过，约翰·卡马克和约翰·罗梅罗曾经试图把马里奥移植到PC上面。然后两个人做好以后，就去找任天堂谈判，希望能够获得授权，结果任天堂根本没有理他们。这两个年轻人就去创造了《Doom》。否则的话，如果谈判成功的话，卡马克和罗梅罗有可能就去制作马里奥了。

在第一次发布《Doom》之前，ID Software这个公司已经发布了《重返德军总部》，也是一款第一人称的射击游戏，但在市场上的反响非常大。这里所说的反响大有两个方面的原因：第一个是玩这款游戏的人觉得很爽；但是另一方面，玩这种游戏的人的家长就有点受不了，毕竟美国是一个基督教国家，让他们看屏幕上全是血肉横飞的游戏，那些家长有可能受不了。

这里说到了宗教，其实并不是说所有的基督教徒都不喜欢玩这种游戏。比方说，ID Software曾经雇佣过一个家伙，他名字叫桑迪·彼得森。他当时已经37岁了。因为ID Software缺一个关卡设计人员，这个人是一个摩门教徒（摩门教在美国是支持一夫多妻的，不知道现在有没有废除）。

有一次我去美国出差，突然意识到，我去出差的这个地方离盐湖城很近。因为盐湖城是美国摩门教的大本营，我就去顺道去盐湖城看了一下。本来也想去看看，如果有机会还可以入个教啥的，结果就去看了一下，也没有人给我传教，就去看了看旅游了一下，还有点失望。

据说这个教的宗旨就是：如果你是男的，你就得承担家庭的责任、社会的责任什么的；女的就不用管这些事情，就服侍自己的丈夫，可能有点像中国这边三从四德的意思。但我本身是一个无神论者，或者叫虚无主义者。我不觉得神不存在，也不觉得神存在，我也不反对宗教。说实在的，我并不太关心宗教，我在这里随便说一说。

ID Software雇佣了这个摩门教徒。在雇佣他之前，罗梅罗看了一下简历，说咱们不能招募有宗教信仰的人。我们做的游戏都是一些魔鬼、地狱、乱七八糟的乱砍乱杀的游戏。如果你把这种人招进来，就是给自己添堵嘛。卡马克说，你说的也对，不过现在很缺人，要不找来看看，不行就算了嘛。然后就这样同意了，结果桑迪就来了。

当时桑迪身材非常魁梧，还秃头，穿着吊带裤。一说起游戏来，他就嗷嗷的激动，挥动着拳头大声地喊，让罗梅罗以为简历上是不是写错了，他还写自己是摩门教徒。随后，罗梅罗就让桑迪来试用一下，来设计个关卡，看一看水平怎么样。然后桑迪就设计了一个关卡，结果罗梅罗一看，这个关卡真是要多血腥有多血腥，要多暴力就有多暴力。还有那种用枪轰开怪物胸膛的特写镜头，罗梅罗就很高兴，说反正我们公司要的就是这种又黄又暴力的人。

最后，桑迪确实不负众望，分担了罗梅罗不少做关卡的工作。等混熟了以后，罗梅罗就试图和桑迪聊一聊宗教信仰的问题。罗梅罗就问桑迪：“你是不是把这个简历上写错了？当时你还写了你是摩门教徒？”桑迪抬起头来就回答：“本来就是罗门，我本来就是摩门教徒好不好？”罗梅罗说：“我靠，你一点也不像呀。人家摩门教徒都是生一大堆孩子。”桑迪就看了看，他回答说：“我就有5个孩子呀。”罗梅罗就没话说了，憋了好一阵子，他又说：“人家摩门教徒可都是带教会卡的。”然后桑迪就从兜里掏出了教会卡，说：“哎，在这里，你看不看？”罗梅罗肯定当时心里就已经崩溃了。

过了一会儿，他说：“我看人家摩门教徒，每天都穿着教会的袍子，也没见你穿。”这个时候桑迪就慢慢的站起来，脱掉了外套，露出了外套里面的教会衣服，说：“在这里，罗密罗老师好，那我闭嘴算了。”

桑迪这时候就说：“哎，其实我知道你什么意思，毕竟电脑里都是恶魔，都是坏蛋嘛。本来就应该拿枪把他们都崩了。所以说呢，也并不是说所有的宗教都让人不能玩这个杀戮游戏。你看人家这个还涉及杀人的游戏呢，但都是杀的恶魔。”

现在包括以前美国的家长，包括现在中国的家长，也是这个意思。你如果在游戏里玩得很血腥，现实中也有可能有暴力倾向。以前我记得玩《魔兽世界》的时候，人死了还不能出现尸体，就得出现墓碑。

其实咱们随便想一想，比如说我每年打《FIFA》足球，想来想去可能平均每天得一个小时或者什么的。假设说我每年打300个小时，但是我这个踢球还是烂的跟狗屎一样，也对我这个球技没影响。你说玩暴力游戏就有暴力倾向，像我这每年玩300个小时的《FIFA》，是不是应该成了世界足球先生啊？其实这都是非常扯的事情。

**《Doom》发布时的盛况**

在《Doom》发布前的几天，有个计算机杂志的标题是这样的：“家长们的圣诞噩梦”。里面是这样写的：“当你们以为天使般的孩子在期盼圣诞糖果的时候，他们的心里已经被一个精彩的游戏吸引住了。这个游戏就是《Doom》，也就是说是家长的噩梦。”

在1993年12月10日的时候，ID Software要把《Doom》放在互联网上，当时放在威斯康星大学的FTP服务器上。得知这个消息以后，威斯康星大学的服务器上就挤满了人。当时还没有现在这种可以上传文件的聊天方式，当时人家就上传文件夹，以文件夹的名字来命名，就是说以文件夹这个名字来聊天，就是问：“现在上传了吗？”就这样不停地建文件夹来问这个事情。

后来呢，结果上传的人根本就上传不上去，因为人太多。他当时就说：“我现在要上传了，结果人太多，你们要不要就先散了。”然后大家就潮水般地散去了。等到上传了以后，他就发了一个东西，说：“哎，现在已经上传成功了，可以去下载了。”结果就从四面八方的人就涌向了威斯康星大学的FTP服务器，那就是发动了人肉拒绝服务式攻击嘛。

当时这个大学的服务器的管理员叫大卫，他就打电话给ID Software的人，说：“我从来没有见过这么多人。”其实呢，当时这个世界上也真是没发生过这种事情，就靠人就把一个大学的FTP给挤瘫痪了。

《Doom》这个游戏玩的就是非常爽，你可以把怪物一下打成两半。不过现在也是到处都是血浆，怪物的身体的残肢崩得到处都是。但如果你喜欢玩这种游戏，比如说我，就很喜欢，就觉得越血腥越好。但在美国当年出来的时候，就一下子惊动了美国议员。

当时一个叫列伯曼的议员，一手拿着《Doom》的光盘，一手高瞻远瞩，声情并茂、痛心疾首地呼吁：“看到这个游戏的时候，我坚信这个世界上有那么一小坨不负责任的不明真相的游戏制作者，我希望伟大光荣正确的美国政府可以将他们斩草除根。”但也就是这个意思嘛。

但政客和卫道士总是在试图拯救下一代于水火之中，尽管他们和年轻人有深深的代沟。当然，这不妨碍他们有钱、有枪、有话语权，还有立法权和行政权。

其实早在美国内战结束的时候，宗教就非常排斥言情小说。等到言情小说可以公开出版的时候，他们就把矛头又指向了电影和电视。在五十年代的时候，上个世纪五十年代，非常出名的猫王是不允许全身露出来的，只允许露上半身。

后来他们又指责《龙与地下城》这个游戏，甚至把杂志的创办者就被美国国会传唤去了，就说这个《龙与地下城》很有可能有一个恐怖组织有关系。

后来他们指的就是这种重金属音乐，比如说现在玛丽莲·曼森的音乐，肯定也是现在被抵制的一种。有很多人受不了这种音乐，当时接着轮到电脑游戏成为焦点。其中，“杜姆”（可能是指经典游戏“Doom”）这款游戏就处于漩涡的中心，各种专家、政客纷纷粉墨登场，一起指责这个游戏，声称它对青少年的心理有影响。

在青少年的世界里，这完全是另一个世界。杜姆就像野火一般迅速蔓延。发布杜姆后的一段时间，几乎每个大学的网络都变得非常缓慢。卡耐基梅隆大学甚至要求杜姆玩家不要联网对战，因为当时的校园网已经不堪重负。如果发现了有人联网对战，就会封掉他们的账号。

当时在公司也是如此。英特尔公司很快就发现了这个网络异常，他们调查后禁止员工在上班时玩这个游戏。还有路易斯大学的管理员，直接编写了一个软件，能够循环递归地检查所有机器，一旦发现有“Doom”软件就自动删除。因此，当时“电子海洛因”就是用来形容“Doom”的。现在，“电子海洛因”一般用来形容所有的电子游戏。

“Doom”发布的时候，就让ID Software名声大噪，也让这个公司赚了很多钱。据说在第一天，你可以下载试玩版，然后再购买完整版。第一天刚下载完，就赚了十几万美元，之后收入越来越多。

再后来，卡马克和罗梅罗就慢慢地分道扬镳了，两个曾经亲密无间的朋友逐渐形同陌路。在一次采访中，卡马克表示，罗梅罗想要建立一个帝国，而他自己只想做出好玩的游戏。

好，这一期关于这个话题我们就讲到这里吧。我们再讲一点怎么购买Steam游戏。从前年还是去年开始，Steam就可以使用人民币结算了，但后来又不能用支付宝了。自从可以用人民币结算以后，中国区的价格算是比较低的。其实不用再像以前那样跑到其他区去买，但还有一个区就是俄罗斯区，可能还是比中国的要便宜一些，不过也没必要。现在我觉得中国区已经算是比较便宜的了。

Steam游戏的一个特点是一年打很多次折，在中国就至少有六次。春节有一次，然后春夏秋冬各一次。春天是二月份打折，夏天是六月份，秋天是十月份，冬天打折它叫圣诞节。期间还有一个感恩节，是十月份。圣诞节是十二月，总共这六次打折就是春节、圣诞节和感恩节，以及春夏秋各一次的打折活动。
