---
title: "Linux传奇：终端到操作系统"
editor: visual
---

在节目正式开始之前，我先来回答一个ID叫“超级炮车”的朋友的问题，这个是“打炮”的那个“炮”，“超级炮车”。还有一个ID叫“家住海边，喜欢浪”的朋友。说真的，我很希望大家每个人都注册一个公众号来写文章，能碰到好多有趣的人或事。目前这两个ID是我最喜欢的两个ID，一个叫“超级炮车”，然后还有一个叫“家住海边，喜欢浪”。

先回答一下这个“超级炮车”读者提到的问题，其实呢也不算回答。因为昨天我发出了那篇《如何在裸机上运行软件》的文章以后，这位热心的读者就和我讨论了很多操作系统的问题。后来还加了微信，讨论了好久。说实在的，我虽然35岁了，而这位叫“超级炮车”的小孩，真的是小孩，刚刚上大学，他对操作系统的很多理解已经远远超过我了，让我非常的佩服，也很欣慰。在我的内心，我还是一个技术宅男。相比于技术，我其实挺讨厌讨论那些经济、政治、金融这种话题，我觉得那都是上层阶级关心的问题。我更喜欢没事折腾一下电脑或者陪我两个小孩玩玩。

我跟这个“超级炮车”讨论的问题其实也很简单，也很有趣。就是说如何编译一个软件，让这个软件可以不借助操作系统运行，就是上一期节目的意思。然后他就提出了这个问题，我觉得也非常好。比方说呢，我们从网上下载一个游戏，比如说《魔兽争霸》或者什么游戏的话，如果没有Windows操作系统，是不是我们没办法让这个游戏运行起来？对啊，你没办法，你下载了之后，你没有操作系统，你就没法让它运行。因为这个软件是要借助操作系统才能装上，然后游戏才能运行。如果一段代码可以直接让它运行在软件上，而恰恰这一段代码又恰好可以做一些事情，比如说它做的事情是管理计算机的硬件资源这件事，那么这段代码就是个操作系统。那如果这段代码不做管理计算机硬件资源的事呢，这就是一个不依赖操作系统的代码。那如何才能做到呢？

其实重点呢就是说你要静态链接所有的依赖，并且规定这个程序内存地址空间的一些顺序。因为现在我们程序员开发的都是非常高层的东西，比如说很不接近底层了，我们都是用IDE（集成开发环境）来开发软件。所以很多同学在编译和链接的时候，就算点一下，它自动就完成了编译和链接。整个过程其实是两个独立的过程，编译是编译，链接是链接，但是现在的编译器呢，都把这两个东西结合在一起了。其实现在的编译器，你用命令的话，都会有以下的一些功能。第一个呢，它实际上是可以指定特定的函数在你最后生成的那个文件中的偏移量。还有一个功能呢，是保存一张符号表，里面就标明了每一个函数的偏移量。知道了这些东西以后呢，如果我们有一个loader的话，就可以直接根据规定的那个偏移量，直接就把那个entry function加载到那里。

比如说呢，如果有年龄比较大的朋友用过MS-DOS的话，像我就用过MS-DOS或者Windows3.1。它的本质是什么？就是一个loader，我一下子就要找到那个安全防护tion，就把它load起来好了。（注：此处“tion”应为识别错误，但根据上下文无法确定正确词汇，可能是“section”或其他相关术语）就不说这个了，我觉得这个问题讨论得非常好，所以我单独说一下。

上一期说了呢，Linux在软盘里就写了一个可以启动的终端模拟器，用来上网、在网上发帖或者看新闻。这个软件的功能当时就是这些，没有其他的功能了。但是Linux非常希望再添加一些功能，比如说它从网上下载或者上传一些文件，但是呢，这个目前的终端仿真器是没法完成这个任务的。因为如果你这个软盘想要存储文件的话，需要一个文件系统。现在我们都知道一些文件格式、文件系统，比如说Windows上常用的文件格式就是NTFS格式或者FAT32，Linux常用的格式有EXT4等等。但是在Linux那个年代，它使用的是软盘。

说实在的，我用软盘的机会也不多，用过，但是不多。我知道它这个格式是FAT12，因为我用电脑的时候，这个软驱就已经渐渐地要退役了。我那时候已经出来U盘了，只是比较小，16兆或者32兆，但总比1.44兆的软盘要好很多。因为我对软驱和软盘了解不多，我就知道它的文件格式，但是实际上其他的也不知道了。但我也不可能为了写这篇文章，再去研究一个已经退役了的文件格式。但是我可以谈谈硬盘，我还是了解一些机械硬盘的。

假设Windows当年是在它的机械硬盘上弄一个文件系统的话，它应该关注哪些技术细节呢？就是硬盘在操作系统里和其他的硬件设备都是一样的，就和我们的显卡和我们的键盘控制器一样。如果你要对硬盘控制器的IO进行操作的话呢，其实都是一样的。硬盘的IO端口也是分成两种，一种叫做命令块寄存器，一种叫做（此处重复，应为另一种寄存器名称，但根据上下文无法确定，可能是“数据块寄存器”或其他相关术语）。简单的来说，你如果先要做的事情，就是先向命令块寄存器中写入正确的值，然后再通过控制块寄存器发送命令就可以了。就这两步。

如果我们买回一个硬件，比如说我们要买个显卡什么的，你装在那个主板上，实际上是先要装驱动程序的。其实硬盘也有驱动程序，只是我们很难说“哎，我买了个硬盘要去装驱动程序”，是因为操作系统都已经帮我们装好了，我们不知道而已。它就是你一装操作系统，它自动地就帮你装好了，它偷偷地帮我们装好了。驱动程序的作用呢，就是隐藏硬件的细节，像其他的使用它。比如说有很多进程使用这个硬盘的话，它在提供一个统一的接口。

当年Linux是完全想写自己的文件系统，因此呢，他还要写一个自己的文件系统的驱动来查看他那台Linux硬盘上的一些组织文件。你如果想要查看的话，你必须要先写一个驱动程序。按照他自传里的话说，它的文件都保存在Minix系统上，这个硬盘嘛，所以呢，这个他是要在软盘里。如果要做的话呢，就需要兼容这个Minix系统，否则的话你完全读不出来。但它在它的自传里呢，也没有透露它的硬盘容量的大小。说实在的，我也很难查到它当年那个硬盘是多少兆的，应该也不大可能100兆不到。但是呢，那个年代的硬盘是一种叫做IDE接口的，这个我是确定的。这个IDE接口是一个有几家公司，包括西部数据啊、康柏、希捷这些公司合作开发的一种标准的接口。

可能那个时候呢，现在我们都使用SATA接口，那时候还没有。为了区别呢，那个年代的接口我们称之为并口硬盘，现在的呢，我们称之为串口硬盘。但他们的祖宗都是在一九七三年IBM开发的一种叫做Winchester硬盘的东西。也就是我们有人会听到过“温盘”，就是这个东西。现在在很多地方呢，仍然可以看到驱动文件。比如说尤其是很多开源的系统，如果你看到有一个驱动文件叫Winter Ter（此处应为识别错误，可能是指某种硬盘驱动的名称，但无法确定正确名称），就这么个驱动文件的话，这个不用想，99%就是这个硬盘驱动，因为它都是有历史遗留问题嘛。以前那个技术叫温彻斯特技术，是IBM搞的。

我大体就讲了一下硬盘。有了硬盘以后，我们再说一下文件系统。比如说FAT32、NTFS这种就是文件系统。当年Linux需要兼容的是一个Minix文件系统。我在微机百科上看了一下，这个Minix文件系统也不是自己独创的，他当年就是学习Unix文件系统的东西。但对这个Minix我也没用过啊，肯定也不懂，但是我可以以FAT32格式来代替。我觉得整个文件系统跟我们教科书上学的一样，虽然不同的名字，但是本质差别不大。

所以我就先说一个大概。比如说我们现在就是玩游戏嘛，想一想如果我们是Linux的话，碰到这个情况应该怎么做？如果你要做一个文件系统呢，从大的方面我们要考虑搞定几件事情。就是说你第一个呢，就要有地方记录硬盘扇区使用的情况；第二呢，就是要有地方记录哪个文件占用了哪个扇区；第三呢，你要有地方存放文件的索引，查找的时候要方便。总结成一句话来说呢，这件事情Linux做了一件什么事情呢？就是他做了一套方法。这套方法呢，就是用于存储、组织和管理计算机文件数据的一套方法。就是文件系统就是这么一件事情。他呢，还是要兼容Minix。

为了开发这个文件系统呢，我们这个可爱的Linux同学呢，就整个放弃了他所有的社交活动，生活就只剩下了吃饭、编程、睡觉。吃饭、编程、睡觉。花了好几个月的时间。他在自传里自己说，整个夏天，他除了编程，什么也没干，才终于搞定了这个文件系统。在开发期间呢，他也沮丧过很多次。从他自己的自传里，我可以挑出一些故事来讲一讲，讲一讲这个Linux当年激情燃烧的岁月，以表达我对Linux无限的敬佩。

他说：“这个项目花了我很大的力气，我的日程安排也成了编程、睡觉、编程、睡觉、编程、吃饭，吃一点椒盐卷饼，再编程、再睡觉、再编程、再洗澡，就是随便匆匆了事，然后再编程。”随着项目逐渐完善，我意识到它越来越像一个操作系统了。于是我改变了想法，不再把它当成一个改进型的终端仿真程序，而是一个可运行的操作系统。既然它的功能已经如此之多，那么只需要再加把劲，它就能破茧成蝶了，变成一个操作系统。

每当我看到这一段的时候，我就非常的感慨。就真的是纯粹是为了兴趣搞文件系统、搞什么的，然后最后就搞出来了一个操作系统。对于喜欢编程的人来说，这个编程是世界上最有趣的事情。对不喜欢编程的人来说，这个可能是世界上最无聊的事情。但对我来说，我觉得编程也要分成两种：一种是你有兴趣编程；另一种是你给谁给的钱多，你就给谁编程。这两种有时候是冲突的，尤其是你为了工作的时候，其实很多时候编程是没有什么乐趣的。因为我干过很多类似没有这种乐趣的编程，其实跟农民工挖个水沟也差不多，就是人家给你画一条线，你挖过去，客户让你怎么干，其实能自由发挥的地方也不多。

长都是叫舅舅。就是这4个人怎么做呢？就是点四次确定，然后弹出一个对话框，有一个文本框，输入自己的名字，然后还要在电脑上给他配一个摄像头，他点确定、输名字，然后再拿着摄像头拍一张是他点的这个人的照片。然后这4个人只有都干了这件事情以后呢，这个钱才能发下去。最后再交给管财务的那个人再点一个确定。

也就是说，整套系统我们又给它加了5个确定的地方，加了5个写名字的地方，还加了5个用摄像头拍照片的地方。

其实，有的时候生活就是这样，也很无奈。有时候我想想，我也就是为了混一口饭吃嘛，人家让你怎么改，你就怎么改，否则的话，你这个系统人家也不给你钱。可能是因为我在现实中有时候也经常碰到这种客户，就是比较刁难嘛。所以我有时候想想，哎，可能我热衷于技术有点是躲避现实的感觉吧。当然我也不知道，但是实际上我还是真心觉得编程很有意思。有时候调试整个bug的时候，调试半天，然后突然找出了这个bug，那个感觉还真是很爽。我也很热衷于学习新的东西啊，各种有用的没用的编程知识、编程故事也知道了一大堆。

所以呢，我就写这个公众号来告诉一些后来者。如果有人喜欢听的话，我还是感觉到比较高兴。虽然这个公众号的人也很少。最后呢，我前一段时间是学习怎么录视频嘛，结果录的还是太差了。因为各种录屏软件我也不会用，我只会普通的录屏，而且废话也太多。

我有一个为期五年的视频录制计划，就是我打算把我知道的这些编程知识都录成视频，打算放3个地方。第一个呢，放百度网盘上，因为这个可以下载，你可以看得比较清楚一点。因为我都是弄的720p或者是1080p的，你可以下载，如果有人看的话。第二个是b站，就是哔哩哔哩这个网站，很多人还不知道哔哩哔哩这个网站的好处，就是它没有广告。然后还有一个是腾讯视频，之所以放腾讯视频呢，是因为你如果在微信公众号里要添加视频链接的话，它只支持腾讯视频。我也不知道有没有广告，看起来好像没有，有的人说又有，我也不知道。但有可能要看广告的话，它只支持这个腾讯的微信公众号，你只能放腾讯的视频。百度的链接呢，我就放在我的公众号里，就在下面好长一串。如果有了我新录制好的视频呢，我就都放在这个地方。如果你关注一下这个文件夹，就应该可以看到。

这期呢，我也就先放在这里。我是录了一个叫《三十分钟讲Python》的视频，就是让大家看一下喜不喜欢这个Python，对不对胃口，但是讲得也不仔细。但是我还是学了很多的技术，怎么去切换镜头啊，怎么把它字体放大缩小。这样作为录视频界的新人，以前录的实在是太烂了，废话也太多。这个是我闭门思过一周多搞出来的嘛，还是非常欢迎大家提意见。
