---
title: "任天堂往事，马里奥之父宫本茂"
editor: visual
---

我在刚刚做这个公众号的时候，写了两篇关于任天堂的故事，但一直拖着没有再写下去。因为那个时候这个公众号刚刚开始，每一篇文章只有五到六个人去看。其中四个人是我认识的，一个是我，另一个是老婆，还有另外两个是我同事。所以，根本就没有动力写下去。我就打算做一些跟风的题材可能会比较好，比如说有什么热点就写点什么。因为微信的文章，只要第一天没人看，可能就永远不会再有人看了。尤其是我这样的公众号，如果是名人的公众号可能会好一些。不过呢，我还是继续想把那些坑给填起来。

现在开始说正题。任天堂的老大山内溥当时非常想进军美国，让任天堂冲出日本，成为一流的公司。任天堂当时在日本已经有了很大的知名度，但是你想换一个国家，去美国是得从零开始。如果想开公司的话，首先考虑就是找谁去美国开公司。当时山内溥的儿子还非常年轻，经验也不足。如果有人看过前两期公众号的文章——当然这个也很困难，根本没有人看过那两期文章——为了能让这个故事连贯一下，我就提一下。上两期讲关于任天堂故事的时候，说这个山内家族的老传统，经常是生不出儿子来，家族企业就传给自己的女婿。山内溥虽然破天荒地生了一个儿子，但是这个儿子是第三胎，前两个都是女儿，分别是养子和次子。因此，这个儿子的年龄就有点偏小。如果当时让他去单枪匹马去美国监理公司，就有点虐待年轻人的感觉。

幸好山内家族有女婿的传统。说起来山内家还算是比较宽容。以前的时候，山内家族找女婿来，第一件事情就是让女婿把姓给改了。不管以前姓什么，只要不是姓山内，就先改为山内再说。否则的话，这个女儿留下，这个男的就赶紧滚。山内溥的大女儿叫洋子，找了个女婿叫荒川实。如果按照老传统的话，这个荒川实应该改成山内实。可能是山内溥网开一面，或者他忘了，就没有让这个女婿去改名。荒川实和洋子当时就住在加拿大，做房地产方面的事情。而且这个荒川实的性格也非常潇洒，比较爱享受生活。按照现在的话来说，就是比较喜欢玩自驾游，经常开车穿越北美。和山内溥比起来，山内溥本身就没有什么爱好，就是喜欢去逛个艺伎店。前两期公众号也提到过，洋子她过20岁生日的时候，山内溥就把女儿生日派对的地点就定在了一个艺伎店。洋子过完生日都回家了，山内溥还留在那里，跟艺伎们聊人生、谈理想什么的。

如果通过常理推测，性格不合的人很难做朋友，更别说性格不合的岳父和女婿了。这两个人基本上是互相不搭理。山内溥当时就提出让女婿别干房地产了，去美国开分公司。女婿也就很爽快地一口拒绝了。但是山内溥软硬兼施、三番五次地提这个事，最终荒川实还是答应了。这个时候洋子，也就是荒川实的妻子、山内溥的大女儿就非常担心。据说洋子和山内溥的关系也不好。这个传闻我猜应该是真的，因为从来没有传闻说过山内溥和谁关系好过。

后来呢，不出洋子所料，山内溥这个岳父以后就越来越讨厌他这个女婿，三番五次地说任天堂这个公司以后打死也不肯再传给这个女婿。后来呢，确实也没有传给女婿，这都是后话，以后再有机会谈。但是当时的时候还得依靠女婿。在任天堂美国分公司建立的时候，毕竟拆过桥拆桥也得先过了河再说。现在呢，他这个岳父还没有对女婿表现出非常讨厌，女婿就被忽悠着去美国开公司了。

荒川实刚刚把公司建在纽约，山内溥刚刚知道地址，就发了3000台街机给女婿，说让他把这个3000台卖掉。当时仓库都没有，好不容易就在新泽西搞了一个仓库。那个时候呢，任天堂是卖街机，咱们也都见过街机，就像冰箱那么大。3000台街机只卖了1000台，总共3000台，巨大的压力！然后荒川实和洋子就是轮番出马，还雇了当时只有两个员工——除了他们夫妻俩还有两个员工，就是两个卡车司机，总共4个人要卖掉3000台街机。所以说这个山内溥老爷子坑女婿、坑女儿，手段也是一流，根本卖不掉嘛！

这4个人白天黑夜地卖，好不容易卖掉1000台，还剩下2000台，根本没有卖掉。这边的山内溥还打电话问你要不要再发3000台过去。山内溥给了他女儿极大的压力，毕竟东西卖不出去，赚不到钱不说，还得付着房租。我看报道的时候，这段时间洋子非常抑郁，然后开始吸烟，每天最后要吸三包烟。就这样，其实创业就是那么辛苦。你这游戏机卖不出去，总共4个人——一个老公、两个司机——可能实在是太苦了，每天都要吸三包烟来减轻压力。现在想想还是挺心疼的。

这个时候山内溥也很生气，当然并不是生气他女儿吸烟，而是生气他女儿女婿卖不出游戏机。其实这也不能怪荒川实和洋子，毕竟当时美国的市场老大是雅达利，想挑战老大靠当时的任天堂肯定是不行。因为名气没有，你一到美国就想把当时市场的霸主打翻在地，基本上这种故事只会出现在电影里，现实中是非常难上演的。

当时在日本的公司也不止任天堂，比如说南梦宫和泰东也在试图开拓美国的市场，毕竟美国是最大的市场。现在不知道大家有没有人知道这两个公司。南梦宫——如果大家玩过《吃豆人》的话，最近还拍了一个电影《吃豆人》，这个就是南梦宫做的；还有个游戏叫《太空侵略者》，那个游戏是泰东公司做的。当时这两家公司在美国的时候是通过代理公司来做这个事，因为你要给代理公司一些钱嘛。任天堂是自己开公司也自己做，肥水不流外人田，不用代理公司。

简单来说，任天堂的主打游戏是雷达范围（这里可能是笔误或特定语境下的表述），根本就没有销量。这2000台机器要么丢了，要么更新一个游戏就旧瓶装新酒、死马当活马医，看看还有没有转机。当荒川实把这个想法告诉山内溥的时候，山内溥也同意了，说可以制作一个新游戏。但当时任天堂公司很忙，没有足够的人来设计新的游戏。于是公司就开始收集游戏的点子。当时有一个29岁的人，脑洞大开，提了一些脑洞大开的点子。山内溥当时觉得比较惊讶，毕竟这个家伙以前是设计游戏机包装的，怎么能设计游戏呢？但他觉得还不错，他就让任天堂的大将横田军平来协助他，看看能不能搞定这些脑洞大开的点子。

这个年轻人就是宫本茂。但也的确不负众望，将任天堂一个一直没有取得版权的游戏进行了大规模改版。原来这个游戏的主角就是大力水手，但是大力水手这个版权一直也没有弄好。宫本茂只是借鉴了大力水手的故事情节，这个故事情节也比较老套，就是英雄救美人嘛。宫本茂的故事具体情节就是一个叫跳跳人的英雄打败了大猩猩，救出了美丽的女孩。这个跳跳人就是日后的马里奥，那个女孩呢就是日后的桃子公主（在大陆这边都叫桃子公主，其他的什么也有叫碧奇公主的，反正就是一个人）。

如果玩过的话，这个游戏设计出来以后，经过复杂的开发过程——这里就省略掉这些复杂的过程不谈——包括需要很多修改硬件，还要跟三洋公司去改硬件什么的，还要修改软件。而且宫本茂还要加入开场动画，还要加入音乐等等，反正也得罪了不少人，也确实让一些人有点讨厌他。当时简单来说，最后还是搞定了，并且把修改的方法告诉了美国的任天堂。

美国任天堂那边呢就是要对每一台游戏机进行大刀阔斧的修改，反正软件硬件你都要改，还要接新的连线。就是要先把那个游戏机的主板拿出来，连一些新的线，什么喇叭呀都要重新弄一下，变更游戏主板。要知道，当时美国任天堂只有4个人，全都不懂电器工厂那一套。因为以前洋子跟她的老公都是搞房地产的，但你还是要硬着头皮干活，因为你一根线在上面焊接错了，这个机器也就冒烟报废了。

而当年做这件事的时候正是八月，恰逢夏天，还遇到了史上最热的夏天。据说那一年的温度最高达到41.7摄氏度（好像我们看起来也不是特别热，在中国我们经常到四十二三度）。创业就是这样啊，和打工不同。洋子和荒川实反正也就坚持下来了。好不容易搞了两台改装好的机器，把它卖给了酒吧。结果当天机器就不能运行了，就打电话告诉荒川实，让他赶紧回来修。荒川实回去一看，原来是这个游戏太火了，投的硬币太多，导致机器不能运行了。因为这个游戏一下子就让人觉得非常好玩，酒吧肯定也是为了赚钱嘛，见钱眼开，订购的机器也就越来越多，就成指数级地增加。

这个游戏就救活了美国的任天堂公司，任天堂就不停地发货。从日本不停地发货，那2000台很快就卖完了，也让任天堂赚得盆满钵满。虽然这个游戏那个时候还不叫马里奥，而是叫《大金刚》，但是这个跳跳人已经做出来了，他还是需要一些时间来登上这个世界的舞台。总有一天，这个可爱的跳跳人，也就是以后的马里奥大叔，将会让世界瞩目。

其实这样说起来，马里奥的诞生充满了偶然。如果当时美国任天堂卖掉了库存的机器，而当时山内溥也没有答应荒川禅师可以造一款新的游戏，或者横井军平根本就不理睬宫本茂那些很无理的要求，包括什么三洋电器那些不按宫本茂的要求修改硬件，也许这个马里奥根本不会诞生。但是呢，如果宫本茂也许还继续设计他的游戏机包装，也没有人知道今天这个如雷贯耳的名字。他就被称为马里奥之父。

好了，这一期节目就到这里，再见。

2016-08-03
