---
title: "第16期  一个伟大的公司之死"
editor: visual
---

历史是一条长长的河，里面流淌着的是红红的鲜血，从历史的深处滚滚而来，向未来滚滚而去。顿河静静地流淌在俄罗斯的大地上，一年四季变换着不同的颜色，两岸有优美的风景、美丽的田园和一望无际的草原。没有人曾经想到过，这里有残酷的杀戮，有嗜血的疯狂，有无尽的虚伪和贪婪的欲望。当尘埃落定，一切喧嚣回归平静，顿河还是静静地流淌，日夜不息地流向海洋。

《静静的顿河》是苏联小说家肖洛霍夫的一部作品，他花了十四年的时间写出了这本史诗级的长篇小说。每一种杀戮都被赋予了一种意义，每一种疯狂都被赋予了一种赞美。在人类的历史上，这一切被反反复复地上演，反反复复地又被人遗忘。

在整个IT工业发展史上，微软的光芒几乎始终掩盖着其他所有的公司，很少能有公司掩盖住微软的光芒，网景就是其中的一家。然而，在和微软的斗争中，它最终还是败下阵来。但是，它毫无疑问算是西楚的霸王，败，也败得惊天动地。

在20世纪90年代，互联网开始从小众的大学实验室慢慢地走向了广大的消费市场。当时的互联网兴起的时候，大家并不知道该如何方便地使用互联网。1990年，伯纳斯-李博士在麻省理工学院发明了HTTP协议，并且实现了一个简陋的网页浏览器，但是那个时候离普罗大众的需求还有非常遥远的距离。马克·安德森和吉姆·克拉科为了方便大家浏览网页，创造了一种带有图形界面的、对普通用户非常友好的浏览器，并且在一九九四年成立了自己的公司，名字叫网景公司。在一九九四年的10月13日，发布了第一个新版本的浏览器Netscape 0.9。借助网络上升的浪潮，该浏览器迅速占领了市场。在成立一年以后，网景公司便在纳斯达克上市，开盘价是28美金。在第一天收盘的时候，股票已经上涨到了75美金。在一九九五年，网景的Netscape浏览器便占据了70%的市场份额。网景公司的巨大成功，甚至让创始人马克登上了一九九五年的《时代》杂志封面。网景浏览器的巨大成功一度让股价超越了微软。

刚开始的时候，比尔·盖茨忽视了互联网的巨大潜力，对网景公司无动于衷。在同事和华尔街的百般劝告下，比尔·盖茨才看了Netscape的展示。凭借比尔·盖茨过人的嗅觉，他意识到了互联网的重要性，而浏览器是进入互联网的入口，微软必须要进行一场战争，并且一定要赢下这场战争。按照微软竞争的一贯策略，都是先收购，收购不成功就模仿，如果再不行的话，就进入持久战。比流血，微软的钱非常的多，肯定是对手先死。这三板斧下来，至今还没有公司能够受得了。

当时的网景公司价格非常的高，属于手里有粮心里不慌的公司。所以网景公司很干脆利落地拒绝了微软的收购。两个公司就都回去，各自准备弹药，准备在市场上决一死战。微软公司迅速组织了人马，花费了超过一亿美金，雇佣了超过1000个程序员，开始模仿Netscape。由于网景公司是这个市场的先行者，即使微软这种山寨高手模仿起来的难度也非常大。因此，微软出的IE 1.0和IE 2.0对网景公司的打击无关痛痒，网景公司甚至一度掉以轻心。网景公司的信心也不是盲目的自信，毕竟这个伟大的公司发明了太多的东西，包括至今仍然被广泛使用的SSL、Cookie以及JavaScript，都是网景公司首先发明出来的。

但是在残酷的市场上，只靠技术的先进是没有办法赢得战争的。技术上领先但商业上失败的例子不胜枚举。结果，在一九九七年，IE推出了稳定的4.0版本，微软拿重金开发布会宣传IE，并且不惜把发布会开到了网景公司总部附近。微软的总部在华盛顿的雷德蒙德，他们不辞劳苦来到了硅谷示威。在发布会当天的夜里，微软公司的员工将一个大大的“RE”标志偷偷地竖立在网景公司的草坪上。在第二天，这个恶作剧就被网景公司的员工发现了，他们就把IE的标志丢在地上，并且在这个标志之上放上了自家的标志——一个绿色的恐龙，这个恐龙还拿着一个牌子，牌子上写着：“Netscape，市场占有率72%，RE占有率12%。”以这两张截图，我在网上都找到了，我把它放在我的微信公众号里，“软件那些事”里面。如果有兴趣的话，可以关注一下，看一看还是挺有意思的。

网景公司掉以轻心了。微软采取了激进的免费策略，完全免费，并且使用操作系统进行了捆绑，这一招直接命中了网景公司的要害，Netscape的市场占有率直线下降，而且网景公司对此束手无策。微软反反复复地使用相同的招数，打赢了莲花公司和WordPerfect，此时的网景公司也面临灭顶之灾。

在非正常的竞争之下，网景公司只好对微软发起了诉讼。旷日持久的官司彻底地把网景拖垮了。在官司宣判之前，也就是1998年12月24日，网景公司被美国在线公司以42亿美金收购，结束了自己的历史使命。

在被收购之前的一九九八年三月，面对不断被微软蚕食的市场，网景公司做出了一个伟大的决定。他们把自己的浏览器源代码开放，这就是后来的Mozilla。这份源代码形成了今天三大浏览器之一的火狐浏览器，这些年市场份额始终在第二和第三之间起起伏伏。

网景公司虽然已经死了，但是他的代码永生。有一部很好看的纪录片，叫做《奔腾年代之硅谷传奇》。这是在一九九八年，一个摄制组在网景公司跟拍了一年的成果。从这部影片中我们可以看到硅谷的曾经，以及当年那些明星程序员年轻的模样。我把这个电影下载下来，放在了百度网盘里。如果真的非常希望大家去看一看的话，网址我就写在微信公众号里面。因为读一个网址还是很麻烦的。

我最喜欢的程序员之一就是网景公司桀骜不驯的程序员，他的名字叫杰米，他在高中都没有毕业。在那部纪录片里，你可以看到他一身摇滚明星的打扮。当网景被微软击败的时候，他支持开源，并且编译了开源版本的第一个版本的浏览器。他写过很多的代码，但是他声明永远不授权任何人将代码运行在微软的平台上，他也永远不使用微软任何的产品。当他离开的时候，已经心灰意冷，他买下了旧金山的一个酒吧，离开了编程的行业。后来我在YouTube上看到他一次采访，记者问他：“你现在还写软件吗？”他愣了一下，几秒钟以后，他缓缓地说：“有时候我会写一个屏幕保护程序。”

网景虽然已经死去了，但是JavaScript、SSL、Cookie还有火狐浏览器，这就是他留给我们的遗产。这是一个伟大的公司，我认为他值得我们所有人记住，而且这家公司也配得上人们去怀念。
