---
title: "转给苹果用户一段不可不知的历史"
editor: visual
---

苹果手机的用户，每次点击屏幕上的图标，APP将会启动。启动背后的技术有着悠久的历史，可谓是点击的都是历史，启动的都是文化。本文将向你讲述苹果手机系统的悠久历史故事，还得从上个世纪八十年代说起。

乔布斯把卖可乐的约翰·斯卡利请进公司当CEO。乔布斯说了那句著名的话：“你是想卖一辈子糖水，还是想改变世界？”从某种意义上来说，约翰·斯卡利的确改变了世界，只是改变世界的方法比较奇特。约翰·斯卡利当上苹果公司的CEO不久，就把乔布斯轰出了公司。

乔布斯被苹果公司扫地出门以后，找了一些投资人，组建了另外一家电脑公司，这家公司的名字叫Next。也许有人说他是为了复仇，但是他自己的话是说他是为了改变世界。当然了，不管怎么说了，反正约翰·斯卡利就通过这种方法间接地改变了世界，比卖一辈子糖水肯定要强。

苹果早期的投资人之一亚瑟·罗克曾经说过，对乔布斯来说，最好的事情就是让苹果公司解雇他。可能我们普通人不能理解，这其实是一种非常严厉的爱。比如说有一些我们现实生活中的恋人，分手复合多少次，他们之间一定有我所不理解的那种爱情。比如说那就叫虐恋，虐待的虐，恋爱的恋。乔布斯离开了苹果公司以后，就自由了嘛，经历了一系列巨大的失败，从而变得更加成熟。

再接着说离开了乔布斯的苹果公司。当时的CEO已经换成了一个叫做阿梅里奥的人。此人在乔布斯的嘴里就是说非常的蠢。乔布斯对此人的评价就是最差劲的CEO。当然，我们听听也就行了。比如这个阿梅里奥开始当CEO的时候，苹果公司就要倒闭了，据说当时只能支撑3个月。但是当他离开苹果公司的时候，苹果公司实际上已经接近盈利了，账户上的钱有30多亿美金。

当然，这些事情和本文要说的事情关系不大，我们就省略点不说。关系比较大的是这个阿梅里奥，虽然挺会赚钱，但是不懂技术，尤其是不懂操作系统的技术。因为以前他是做硬件出身的，做芯片。在一九九六年的时候，他很开心地向苹果的用户宣布，苹果公司要发布新的操作系统了，新的操作系统的名字叫System Eight，就是系统8，非常的先进。

当然，苹果的粉丝肯定是非常兴高采烈，就等着秋天发布正式版。但是实际情况呢，这个System 8根本没法用，甚至连文本文件都不能编辑。就是你现在想打几个字都没法做。为了展示的需要，当时用户界面上那些按钮都是图片，没法点，就相当于用Photoshop做了一张图片，做展示的时候就靠一张照片来忽悠观众。

在苹果内部呢，肯定是有很多懂技术的人嘛，懂技术的人肯定是心知肚明。别说秋天了，内部的员工就开玩笑说，System 8这个正式版啊，至少得五十年后发布。也就是说，从一九九六年一直到五十年之后，应该是二零四六年了。即使按今天的话，还得等二十年才发布。

但是苹果的CEO不懂技术这件事情，问题也不大。为什么呢？因为苹果公司还是有牛人的，这个牛人是个女的，她的名字叫Avie Tevanian，是苹果公司的技术总监。乔布斯对她的评价依然不好，但就像前面说的，乔帮主评价人的话，能评为“白痴”的，也应该是个牛人。因为一般人他连觉得连“白痴”可能都算不上。这个女的实际上还是非常猛的，她一下子就看出来这个System Eight这个系统根本没戏。

因此，就在她的坚持下，这个System 8项目就被取消了。因为她知道根本不可能让这个系统运行起来。她一方面呢，就把原先能运行的那个操作系统，也就是说7系统，然后按7.5继续开发，看看能不能添上一些新东西。先把秋天承诺的那个系统先糊弄过去，换点皮肤呀，或者是买很多的第三方的插件软件，然后能糊弄就先糊弄着，因为这个8肯定是发不了。

另一方面呢，她知道老是糊弄肯定不是办法，就看能不能买一个现成的操作系统。这个女的我还是挺佩服她的魄力的。她一方面就是用这个老系统糊弄那些用户，先稳住阵脚；另一方面呢，她就想直接采购一套全新的完整的操作系统。

当时进入苹果公司视野的就这两家：一个是BE公司，它有一个操作系统叫BeOS；还有一家就是乔布斯被扫地出门以后，重新建的那家公司——Next。那家公司的硬件不行，但是操作系统还是非常好的。这两家公司都有自己的操作系统。

我当年上大学的时候，用过这个BeOS操作系统，跟那个Linux差不多，但是感觉看起来比Linux还是好很多。我还找了一张图，放在这个微信公众号里，大家可以看一下。因为现在没法装了，以前的时候我喜欢买电脑杂志，里面就带这种光盘。有一次它就带了这个光盘，上面就有这个系统，我就装了一下，用了不久估计就删了。

BeOS的公司呢，感觉自己的操作系统还是非常厉害，要价就特别高，所以要4亿美元。苹果公司就给这个公司估价嘛，当时估值就是8000万，然后给你个1.2亿，相当于溢价50%，你也够意思了。但是后来呢，这个公司就死活不卖。后来苹果公司赚到了两亿，哎，他还是不卖。这个Be公司的CEO也有一个传记，他说的话如果有人看的话，对小朋友不太合适的话，反正就就觉得他肯定是抓住苹果公司的把柄了，少一分都不能卖。

但实际上呢，这个苹果公司就因为有备胎嘛，买不了BeOS就买Next。后来就买了乔布斯的公司，乔布斯这个公司的操作系统叫NextStep。就是这个系统，今天我们使用的苹果手机这个系统的祖宗。

所以拉拉扯扯地讲了这么多，我们现在才引出重点来。就是现在我们苹果手机这个iOS系统，实际上就是被扫地出门的乔布斯去了开的一家新公司，那家新公司出的一个操作系统，就是继承而来的，那个操作系统叫NextStep。

所以我文章开始是说，每次点击都是点击的历史，这真的是历史。Next的公司被收购以后，乔布斯也就顺理成章地回归了。苹果公司就着手基于这个NextStep系统，开发新一代操作系统。因为苹果公司没有操作系统了嘛，以后新的操作系统，就是我们现在包括苹果手机、iPad还是台式机的macOS系统，都是一样的，都是基于这个NextStep。被收购的这家NextStep系统内核是基于BSD的。

如果大家想知道BSD系统的话，有机会的话，并且我要看看大家如果不讨厌这种讲操作系统这种话题的话，我就讲一讲BSD系统跟雅虎公司的故事。我整天就研究这种犄角旮旯的东西。BSD系统也是开源的，但是他和这个Linux开源协议是不同的。总体来说呢，这个BSD系统的更新频率和Linux系统还是有一些差距。

乔布斯当时也就动了动脑筋，就想既然Linux系统要好一些，比BSD好，那就把那个收购来的那个操作系统的内核换成Linux算了。因此在多方的筹备之下，苹果公司就安排见了一个人，就是Linux的操作系统的创始人Linus Torvalds，就去拜访一下，大家互相见个面嘛，看看能不能谈成。

但苹果公司也知道这个Linus Torvalds是个牛脾气，脾气就是非常倔，经常骂人。据说呀，乔布斯还表现出了礼贤下士的样子，就相当于规格还挺高，就把这个收购来的那些CTO啊，各种技术的骨干都拉过来参加会议。但是这个会议最后还是谈崩了。

不过我们也只能猜一下，比如说Linus Torvalds这种大神，他基本上连比尔·盖茨都瞧不上，乔布斯估计他也不放在眼里。而且一山难容二虎嘛。不过后来两个人都没有提这次会议的内容，估计因为这两个人水平相当嘛，Linus Torvalds也不是菜鸟，估计就是相当于火星撞地球，这种碰撞都不好惹，也就大家都不谈了。

不过这个Linus Torvalds的脾气确实不好，这个点和不少国内的大牛什么的都有共同之处，经常开口就骂人。前段时间他就把一个开源界的大美女就骂跑了，真的是破口大骂，而且还不道歉，就说我以后还会骂人。就这种人，他还公开说，有些人认为我是个好人，再发现我不是好人以后还感到震惊。其实呢，我本来就不是个好人，我也不在乎你们震惊不震惊，我根本就不在乎。

不过这个人确实是那种火爆脾气，包括他骂的那种厂商，NVIDIA这种显卡厂商也真是骂得毫不留情。Linus Torvalds也是，说起来我这脾气就非常好，真的非常好，从不骂人。所以我这个编程技术啊，什么各方面都很菜。哎，这是后话了。

但是后来呢，就是安卓发展起来了，使用的内核就是Linux。如果当年那场会议谈成了的话，比如说Linux答应了苹果，我给你搞这个内核，说不定现在的手机都是Linux内核。但这个没法假设，就苹果手机如果当年谈成了的话，现在苹果手机肯定也是安卓系统，说不定它两个的系统搞搞还是一样的。不过现在也没法说了，都是后话嘛。

历史你不能假设。在和Linus Torvalds谈这个内核事件的时候，也就谈分手了。当然了，他的苹果公司里还是有牛人的，叫做Avie Tevanian。哎，我不知道这个名字怎么读，反正这个人是非常厉害，他是卡耐基梅隆大学的。

如果大家学过操作系统，并且研究生方向读过操作系统的话，比如说研究微内核，你一定知道这个人。他就是开发出了一个微内核的系统，这个系统叫Mach。如果听说中有人学操作系统的话，这个大家都知道，微内核之间传递信息是非常难搞的。Linux就不是微内核，微内核之间你要互相地传递信息，这个非常难搞。因为你得确保bug非常少，互相传信息，你不知道在什么地方就传丢了。

微内核是非常难搞的，比Linux内核要难搞很多倍。我不能说多少倍，因为我不是高手，但是他肯定是很难搞。但这个人搞成了，他就发了一篇论文，告诉大家怎么搞这个微内核。这篇论文如果你要是搞整个计算机界操作系统的话，这个肯定是引用最多的一篇论文之一。

后来这个人就加入了Next，后来就到了苹果公司。被买了之后，基于这个Mach的内核，NextStep这个操作系统就取得了巨大的成功。成功到什么程度？就是大家不买硬件，光买软件，光买这个操作系统。具体的一些琐事也就不说了，挑重点来说。

后来，这个人就成为了苹果公司开发软件的总裁。如果你关注我这个微信公众号，你把这个人的名字抄过去，虽然这名字难读，但你一搜，我就能搜到前面他说的内容，还有前面提到的BSD系统，大家应该记得吧？BSD系统有一个领军人物就叫乔丹，不是打篮球的那个乔丹，只是重名，他也叫乔丹，后来也被苹果公司给挖过来了。

前面说过，如果大家对BSD系统感兴趣的话，我可以做一期相关内容。但是，因为我这个公众号做得也不怎么好，转发率、浏览量、关注度都非常少。我觉得最大的原因还是，我一谈起技术来就收不住，而且大部分人都不喜欢这个，但是我就喜欢谈这个。虽然我技术不好，但是写起代码来也能完成工作。我大量的工作就是在BSD系统上，用C语言写了好多年，我是做路由器的。因为BSD协议比Linux协议要开放，所以公司那时候开发整个路由器的时候，就是选BSD作为基础的代码。所以我对BSD比较了解。

好了，不说了，再说说苹果公司。苹果公司前面我也说了，虽然我技术不怎么好，但是你看看苹果公司，乔布斯麾下真是名将如云，非常厉害。什么BSD的核心，包括微内核的核心都在苹果公司，并不是网上说的苹果没啥创新，不是的，苹果在技术方面的创新真是多了去了。

后来呢，这个操作系统就经过了大幅的修改，就塞进了一台手机里。这台手机就是iPhone。所以我前面也说了，呼应一下，前面就说你每次点击的话都是历史，每次启动的话真是都是文化。你如果仔细研究的话，真是文化，包括什么面向对象都是这时候搞的。

作为一个苹果手机的用户，还是有必要知道一点点手机系统的历史。但是呢，如果你现在是个男生，又在追女朋友，那你那个女生恰好又使用苹果手机，你最好不要跟人家坐下说：“哎，我们来谈谈这个手机操作系统的历史。”那就分手了。所以还是这篇文章就自己读着有用就行了。

好了，这一期就到这里，希望大家听得有趣。再见！
