---
title: "Unix的起源和长久的发展"
editor: visual
---

11辆深蓝色的甲壳虫轿车飞奔在尼米兹高速公路上。开车的司机是一个年轻的大学生，他一边开车，一边翻看着一本厚厚的书。这本书是当时的电脑巨头IBM的一份程序员手册。这个叫肯·汤姆逊的学生开了100公里，从加州大学伯克利分校到圣何塞的办事处，领取了一份IBM 360大型机的程序员手册。此前，他已经连续等了半个月的电话，询问IBM的办事处这本书有没有到货。今天他得到了确切的消息，于是驱车来圣何塞领取这本书。拿到了手册以后，他迫不及待地边开车边阅读。后来他功成名就，在2000年接受采访的时候，他回忆说：“我当时太兴奋了，差点儿出了车祸。”他说，一路上，他边看边确信了一件事情：IBM这台360的大型机是彻头彻尾的垃圾。

多年以后，汤姆逊依然掩饰不住自己对IBM的鄙视。他以嘲讽的口吻对IBM的销售人员说：“你们产品最好的部分就是这些蓝色的包装盒。”当时的汤姆逊才21岁，他一针见血地指出了IBM 360的设计失误。他说：“IBM完完全全地忽略了和计算机打交道的人——程序员和工程师，他们对我们太傲慢无礼了。”事实证明了，这个只有21岁的年轻学生的判断还是很独到的。IBM 360这个机器是计算机历史上最大的一次赌博。IBM为了这台大型机，决定招聘6万名新的员工，新盖五座工厂，但是整个项目还是不断地延迟。作为该项目的项目经理，弗雷德里克·布鲁克斯根据研发IBM 360的经验，写了一本书，叫做《人月神话：软件项目管理之道》。这本书现在仍然是计算机系学生必读的书目之一。这本书记录了人类工程史上一座里程碑式的大型复杂软件开发的经验。

在1969年，这个边开车边读书的学生，在贝尔实验室的两位同事，一位叫做丹尼斯·里奇，还有一位叫做罗伯特·卡内基的家伙，开始秘密地计划一个新的操作系统。在1969年的夏天，肯·汤姆逊的老婆要带着他们新生的小孩回娘家，所以肯·汤姆逊有一个月的时间重新体验一下单身汉的快乐。他在这一个月的时间里，给一台废弃的PDP-7写了一个操作系统，这就是后来的Unix。第一个版本的Unix只有4200行代码，其中有34个系统调用，到现在仍然在使用。

我觉得有关Unix、Linux、BSD，还有Mac操作系统的故事都非常的精彩，所以我要把整个故事都完整地记录下来。虽然现在这个读图的年代写很长的文章显得非常格格不入，但这一系列的文章会比较长，我会分成好几期写。为了照顾微信的读者，因为每一期都是一个相对独立的故事，我也会尽量起一个相对独立一点的文章标题。这样大部分人都不会从头开始看，就是偶尔不小心看到一篇，起码也不会让上下文显得很纠结。在这一系列文章的标题里，最少都会有一个“Unix”这个单词，证明它是一个系列。

1943年，今后创造出Unix操作系统的肯·汤姆逊出生在新奥尔良，他的父亲是个海军的飞行员，从小就跟着父母东奔西走，去过非常多的地方、非常多的国家，包括意大利、日本。从小肯·汤姆逊就对机械电子产生了浓厚的兴趣，非常喜欢冒险。他最崇拜的人就是他当飞行员的父亲。当肯·汤姆逊48岁的时候，他在俄罗斯花了12000美元，就是为了体验一把他父亲开战斗机的感觉。他开的是俄罗斯的米格-29喷气式战机，他在空中做各种惊险的动作，翻滚、失速、画圆圈，做响尾蛇式的避让动作，做空中急转弯。

肯·汤姆逊是一个不善言辞的家伙，他一贯追求简单。在2008年，一群计算机爱好者把第一个版本的Unix源代码找过来，对着源代码实现了一台当初PDP-7的虚拟机，并且让这些源代码重新地运行起来。当这些计算机爱好者兴奋地告诉肯·汤姆逊这件事情以后，肯·汤姆逊只是回复了一个单词：“Amazing。”他一贯地如此安静、简单、不善言辞。但是在他48岁开上米格-29翱翔天空以后，这个48岁的大男孩也许想起了他父亲当年翱翔天空的样子。一贯不善言辞的他甚至写了一篇博客来记录这件事情。其中他写道：“起飞了，喷射引擎全速运转。我感觉到有人在踢我的肾。”

在2000年的12月，57岁的肯·汤姆逊离开了贝尔实验室，正式退休。他成了一名飞行员。上高三的时候，他的父亲才从那不勒斯的空军基地调回到美国本土，回到了圣地亚哥海军基地。他父亲年轻的时候从俄克拉荷马大学辍学，因为家境非常贫穷，因此他的父亲决定要让他的孩子都能够上大学。肯·汤姆逊回忆说：“我上大学是没有问题的，问题是我要选择上哪一所？”最后，这个家庭并不富裕的孩子选择了学费低廉的加州大学伯克利分校，这是一个公立学校，学费会比较低一点。虽然录取他的还有包括麻省理工在内的诸多私立大学。在上大学的时候，他选择了电子工程系，但是他在大学的时候更喜欢待在计算机中心，他对各种编程都非常的着迷。他这样形容编程行业：“这就像盖房子，不需要购买水泥，你自己创造自己的世界，你拥有这一切。而且你不用离开自己的房间。”和Java的创始人高斯林一样，汤姆逊也喜欢玩一字棋，并且在计算机上编写了一字棋的游戏，他和电脑对战，直到他认识了伯克利分校的一个数学教授，那个数学教授的名字叫波尔·肯普。

接下来的几个月里，汤姆逊屡战屡败，但是他并没有气馁，开始编写计算机程序来辅助他。有了电脑的帮助，汤姆逊的棋艺大增，但是他还是没有赢得这位数学教授。在采访中，汤姆逊说：“我快气疯了，我从来没有赢过他，我用电脑来计算，这样我都没有赢过。”在一字棋上，汤姆逊虽然没有赢得波尔·肯普，但是波尔·肯普这个数学系的教授却对汤姆逊青睐有加。他推荐汤姆逊进入当时鼎鼎有名的贝尔实验室。汤姆逊进入贝尔实验室的是计算机科学中心，这个中心在当时的贝尔实验室并不是很出名，但是没有关系，这个中心就要出名了，因为这个中心聘请了汤姆逊和里奇，这两个家伙在今后会让贝尔实验室计算机科学中心名声大噪。

肯·汤姆逊在2006年，又从一个飞行员进入了谷歌工作，开发了Go语言。目前仍然在谷歌工作。在1983年，汤姆逊和里奇因为Unix被授予图灵奖。在这里就引出了Unix的另外一个作者，叫丹尼斯·里奇。这个家伙是一个平易近人的人。举个例子，在2003年，当时已经名声非常大的丹尼斯·里奇收到了一名17岁的瑞典少年发来的一封邮件，问里奇能否接受他的采访？这个获奖无数的科学家欣然答应了这个17岁少年的要求。里奇是从哈佛大学毕业，他用C语言实现了Unix，他也发明了C语言。不幸的是，他在2011年10月12日因病去世，享年只有70岁。他的死讯是2011年10月12日由他的好友罗布·派克发布的。这个罗布·派克也是非常出名的，他是Plan 9的开发者之一，现在他也是谷歌公司Go语言的开发者之一。

由于里奇一直未婚，在2007年从贝尔实验室退休以后，他就一直隐居在新泽西，所以他去世并没有人知道他具体的死亡日期。只是罗布·派克联系了好久都没有联系上他，然后从加州赶到新泽西去看他的时候，就已经发现他去世了。看起来，这是一个有些伤感的故事。他去世以后，也没有引起太多人的关注。在2011年的时候，我曾经写过一篇比较长的文章介绍他，但是也没有人知道，也没有人看。

作为我的微信公众号“软件那些事儿”的关注者，这里我贴一张福利——2002年，里奇发给小朋友的他的桌面截图。在2002年的7月9日，一个网站要求大家说：“我们想看一下你电脑的桌面。”然后呢，他就很愉快地发了一张截图。从我发的这个截图上，我们可以看到，他当时用的应该是Windows NT 4.0的操作系统。这个桌面上开着11个term，这个term的名字应该叫drawterm。这个term呢，据他说是连到一个Plan 9的服务器上，所有的工作都是在那个服务器上完成的。嗯，我觉得我会出一期去介绍一下这个Plan 9。很多人说这是一个失败的操作系统，实际上它还是蕴含了非常多先进的理念，并且也不能算失败。他就因为这个Plan 9，然后罗布·派克就说：“哎，现在的人就没有人关注技术了嘛？”然后喷了一通，然后google就把它挖去了以后再讲。然后这个里奇呢，所有的工作都是在这个Plan 9上完成的。包括从这张图上我们可以看到，有看电子邮件的，还有一个应该是查牛津字典的。

有一次，一个程序员问他：“一个程序员从新手成长为精通C语言的开发者，并且能够写出优秀的代码，根据你的经验，需要多长时间？”他回答说：“我不知道，因为我没有学习过C语言。”当然了，因为C语言就是他创造的，当然不需要再学习了。

这一期就到这里。下一期呢，我将会介绍这个C语言的作者、Unix的发明人之一、Plan 9的发明者之一——丹尼斯·里奇的故事。谢谢大家。
