---
title: "BT(BitTorrent)的前生今世"
editor: visual
---

在2003年，BT下载在全球风靡一时，其作者是布莱姆·科恩，于2002年创作了这款名为BitTorrent（简称BT下载）的软件。据统计，2004年12月，35%的网络流量源自BT软件；而到了2009年2月，这一比例更是攀升至43%至70%。尽管到2013年2月，BT软件所占的网络流量下降至3.35%，但当时文件分享仍占据了6%的网络流量，BT作为主要的文件分享方式，其份额超过一半。

接下来，我们聊聊作者科恩。他1975年12月12日出生于美国，大学未毕业便辍学。从1992年夏天至1993年秋天，他先后在三所大学就读，却都未能完成学业。他的职业生涯也颇为曲折，从1994年至2001年，他历经六个公司，一直从事技术工作，曾担任SAC保险公司的首席软件设计师一职。

科恩最擅长的语言是Java和Python，对SQL语言也较为熟悉，但对C和C++语言则兴趣不大。事实上，BT软件的第一个版本就是用Python编写的，而后续的Java版、C版或C++版的BT软件都是基于他的BT协议实现的。他还曾因发现浏览器漏洞而获得网景公司1000美元的奖励。

这就是科恩的大致情况。他从未真正完成过大学学业，但他的业余爱好却显示了他内心的童真。他热爱杂耍，擅长各种球类和短棒的技巧，能同时扔五个球而不落地（我尝试了一下，两个球都有点手忙脚乱）。此外，他还会做一些体操般的平衡动作和折纸游戏，甚至发明了一些独特的折纸方法。他在英国布法罗汉普郡大学的半年实习经历，是他所受过的最长的大学教育。而他职业生涯中最辉煌的时刻，则是在1993年至1995年间，于贝尔实验室担任了两年的人工智能助理研究员。

科恩曾坦言：“我不是一个梦想家，也从未奢望在某些方面取得巨大成就。我只是一个站在起跑线上却迷失方向的选手，总是在徘徊和观望。”在互联网低迷的时期，科恩和许多程序员一样，频繁地换工作，经历着就业与失业的循环。他一直希望做一个既实用又有趣的项目，以方便网友下载。这就是“非梦想家”科恩的梦想。他说：“我是一个软件工程师，以写软件为生。当我写出一个又一个软件时，我感到非常满足。我也有一个小小的梦想，那就是写出所有人都喜欢的软件。”就这样，BT软件在2002年应运而生。

当时，下载主要通过HTTP、FTP等方式进行，而BT则是一种全新的方法。它充分利用了用户的力量，用户越多，下载速度就越快。这种“人人为我，我为人人”的下载方式赢得了众多下载爱好者的青睐。后来的下载软件或多或少都借鉴了这种思想。BT下载的基本原理是：文件发布者根据要发布的文件生成一个.torrent文件（我们称之为“种子”）。种子文件实际上是一个文本文件，包含Tracker信息和文件信息两部分。用户下载到种子文件后，使用BT客户端（如迅雷、uTorrent等）根据种子文件中的Tracker信息自动连接到Tracker服务器，接收其他正在下载该文件用户的网址名单。然后，软件开始与这些用户联系，从他们那里获取文件的片段，同时别人也会从你这里获取片段，从而加速下载过程。

在这个过程中，Tracker服务器的提供者至关重要，因此成为版权组织重点打击的对象。例如，最著名的Tracker服务器提供者海盗湾在2009年11月17日永久关闭了Tracker服务器。他们在声明中表示：“我们认为没有必要再维护Tracker服务器了，它不会再上线了！它的时代已经结束了。”

我们先暂时跳过磁力链技术，继续聊聊科恩。他的BT软件不仅免费，还开源。当BT风靡全球时，科恩却过着穷困潦倒的生活。很长一段时间里，他靠一张信用卡透支来维持生计。即使BT越来越受欢迎，他的收入依然微薄，主要依靠网友的捐赠和网站文化衫的销售利润来维持生活。

幸运的是，BT软件的流行引起了媒体的广泛关注，也吸引了企业家的注意。其中一位企业家为科恩解决了部分生活费问题，使得BT软件的开发得以继续。后来，一家名为Steam的游戏销售商（就是那个让我们钱包空空如也的G胖的公司）发现了科恩，并邀请他加入。科恩搬到了西雅图，开始了新的工作。Steam利用BT技术发行了《半条命2》这款游戏。科恩依然保持着桀骜不驯的性格，他说：“我最想做的事情就是不工作，然后好好想想该做什么。”他还自我诊断患有亚斯伯格症候群（一种自闭症类型之一），特征是社交困难但注意力集中。

在Steam工作了一段时间后，科恩又离职了。2004年，他与弟弟罗斯·科恩以及商业合伙人Navin共同创立了BitTorrent公司。2012年，该公司推出了一款名为BitTorrent Live for TV的直播产品，通过P2P方式传输数据。

如今，科恩已经结婚，并与三个孩子一起生活在旧金山湾区。

接下来，我来介绍一下几个著名的BT客户端。按用户量来看，排名第一的是迅雷。我相信国内很多用户都使用过它。迅雷因被指责为“吸血迅雷”而备受争议（尽管有人为其辩护说它并非吸血软件），但电驴、BT社区等多次封杀迅雷的事实表明，迅雷在国内BT下载领域占据主导地位。

排名第二的是uTorrent。这款软件在国外拥有众多用户。uTorrent的作者是一位传奇人物——瑞典人Ludvig Strigeus（我不会读这个名字），他毕业于瑞典排名第一的查尔姆斯理工大学。uTorrent软件使用C++编写，速度快。后来被BitTorrent公司收购，现在下载时会附带两个广告条。如果要去除广告条，需要付费购买高级会员，每年费用约为20美元。

我最常用的BT客户端是Transmission，它是一个运行在Ubuntu上的简洁软件。其实，我也写过。当然，还有很多其他优秀的BT客户端，在这里就不一一介绍了。

前面提到过海盗湾的官司和声明。由于海盗湾上存在大量侵权内容（尤其是音乐和电影），因此被多家唱片公司和电影公司起诉。在压力下，海盗湾关闭了所有的Tracker服务器。海盗湾解释称：“去中心化的下载模式已经非常成熟，使用Tracker的模式已经落后于时代了。现在是时候将这种下载模式送进博物馆了。”

现在登录海盗湾，你会发现上面没有种子下载，只有一个磁力链图标（一个磁铁形状）。点击这个图标就能启动BT客户端进行下载。磁力链实际上是一串字符，主要包括资源标识符等必要部分以及文件名、Tracker服务器地址等可选部分。这种方式的优点是可靠性增加、每个节点可替代且难以追查下载者身份。现在这种方式已成为BT下载的主流方式。

另外值得一提的是，包括瑞典在内的许多国家都成立了盗版党。该党派由理查德·法尔科明创立，认为现有的版权制度已经过时，不应无止境限制知识的传播；同时注重公民隐私尤其是网络隐私。2006年，美国向瑞典政府施压要求关闭海盗湾，导致瑞典政府突袭海盗湾并引发民间反弹，使得盗版党在民众中的支持率飙升。目前盗版党已成为瑞典第三大党。2011年9月18日，德国盗版党获得了8.9%的选票成功进入柏林议会，提名的15个候选人全部当选。

在电视辩论中，盗版党的成员与其他竞选者形成了鲜明对比：他们穿着休闲服、不修边幅；而其他政治家则西装革履、一本正经。盗版党的政治主张主要包括两点：一是为了个人目的使用、获得信息是一种权利；二是注重隐私、反对网络审查。盗版党的发起人和中坚分子主要是程序员和计算机爱好者。

关于我跟BT下载的关系，在以后的节目中我再讲吧，我通过写开源软件，找到了第一份工作。
