---
title: "流水线上的兵马俑"
editor: visual
---

我会发一篇有关IT啊、程序员啊或者职业生涯的感想。周日呢，则会发一个黑程序员的笑话。

在2014年10月1日，这个新中国过生日的那一天，富士康一位流水线上的员工，他的名字叫许立志，跳楼自杀了。在这个新闻热点层出不穷的国家，他和我们大部分人一样，没有人会再记得他。如果不是我在翻看日记找素材，写微信公众号的文章，我早已经把他忘掉了。在他去世以后，我从网上获得了这个消息，然后读到了这个已经自杀的年轻人的诗。当时我就抄了一首在我的日记本上，结果又被我翻到了，我还记得。当时我压抑的心情，因为这首诗的名字叫《流水线上的兵马俑》：

“沿线站着夏秋、张子凤、肖鹏、李孝定、唐秀猛、雷兰娇、许立志、朱正武、潘霞、冉雪梅……这些不分昼夜的打工者，穿戴好静电衣、静电帽、静电鞋、静电手套、静电环，整装待发，静候军令。没想到功夫悉数回到秦朝……”

就是这样一首诗。在两年以前许立志去世的时候，就有人当时说许立志的诗写得不好，没有什么文学性。但是呢，我作为一个程序员，本身也没有什么文学细胞，也许那些文学批评家都是对的。因为这首诗看起来也没有什么非常华丽的词语，就是一串年轻人的名字，然后又加上一串静电衣、静电帽、静电鞋这种东西。但是当时我读了以后仍然非常的感动，我就把它插在了日记本上。这次带我找那种要写微信公众号素材的时候，我翻日记，然后翻出来，现在想想还是很感动。

随着工业化的发展，流水线就开始进入了我们的生活。最早好像是在1913年，美国福特公司建造了世界上第一家流水线，他们发明了世界上第一条汽车流水线。随后呢，就从福特公司开始，慢慢地到大众汽车、丰田汽车，以至于流水线开始在各行各业中被广泛普及。比如说快递行业、电子制造行业，当然包括富士康。现在呢，流水线已经在程序员行业中逐渐扎根生长了。比如说一些外包公司，大部分程序员的宿命其实并不是开发新的软件，而是被迫去维护旧的软件。尤其是一家非常大的IT公司，绝大部分的程序员都是在维护一个已经运行了十年甚至更久的软件。因为客户仍然在使用它，你就必须得有人去维护下去。

在工业革命时代，大家看过喜剧大师卓别林的一部电影叫做《摩登时代》，就能够对那个时代的流水线有了一些了解。在这部电影里，查理·卓别林就扮演了一个流水线上的工人。作为工人呢，他受尽了压榨，成了机器大生产中一个小小的螺丝钉。他在一个工厂里就这样夜以继日地工作，以至于下班的时候脑袋都不太好用了，就把路人的鼻子当螺丝钉来拧。这就是流水线上的生活，每个人只负责那一项很小很小的任务，可替代性非常的高。即使你在一个工厂干了好几年，你能接触到的东西依然是非常少。因为工厂并不是把工人培育成全能的选手，因为这也违背了流水线的本质。流水线创造出来的目的就是让员工变成一个螺丝钉，要可替代性非常的高。你今天上午离职，甚至不要过了中午，就随便抓个人来，就把这个空缺给补上，这才是流水线真正的含义。

就在这种情况下呢，工人所受的压力是非常大的，要不然富士康也不会接二连三地出现自杀的现象。但是呢，一个职位上你只干一件事情干久了，无论是心理上还是生理上，可能都会受到非常大的损伤。但是我们还是来分析一下，为什么受到的损伤如此大，而且这些工厂至今还看起来也没有什么改进，还是有点肆无忌惮的。我认为最主要的原因是因为工人没有足够能够威胁到工厂的力量。这个力量并不是说你工人力气很大，然后抓住厂长来揍一顿，而是整个工人在流水线上，这本身就是一个商品，买来的商品，买来的你的劳动力，它的可替代性还是太强。如果没有足够的实力，你光靠媒体啊或者什么去打打道德牌、打打悲情牌，非常不靠谱。你如果想要靠同情来获得尊重，基本上最后的结果就是：第一，你获得不了同情；第二，你又获得不了尊重，两个什么都获得不了。

但这个我们也不用去过多的回避。这些工厂之所以敢这么做，而且做了这么多年，发展的势头现在看起来还是有增无减。很大程度上就是因为这些工厂、这些流水线上的工人，基本上都没有什么可以依靠的。其实去流水线上也不能靠爹，这些工人所能找到的最好的工作之一，就是站在流水线上，起码还有口饭吃。虽然看起来这个生活很残酷，但确实是事实。你总比饿着肚子流落街头还是要强的。工人是不可能在一家这种富士康类似的公司学到一身本领，然后辞职出来就建另外一个富士康的，可能性微乎其微。根本不可能说你在一个电子工厂打工，比如说去哪个造冰箱的厂，然后你出来建个冰箱厂，不可能的。因为你只干了一件非常小的工作。

当然我并不关心其他的行业，我最关心的仍然是程序员这个行业。那程序员这个行业最终会不会也变成像富士康一样，就是一条流水线的？我虽然从来没有去过富士康，但是呢，我还是在网上啊，或者在什么媒体渠道上看到过很多富士康的照片。就是每个很年轻漂亮的那种小姑娘，那工人面前都有一台看起来价值不菲的机器。我们就假设那台机器平均10万一台（当然有可能更贵，也有可能更便宜），不过没关系，这不影响我们的分析。总之这台机器它不便宜。在计算机早期的时候也是这种情况，和现在的情况相反的是，早期的程序员大部分都是女的，因为每个女程序员都站在一台巨大的电脑面前，给计算机编程。编程的方法就是连线嘛，跟电子管连不同的线，然后这个程序就发生改变了。因为那个时候一台电脑跟那个富士康前面那台机器类似，非常的贵。电子管的计算机还是后来刚开始晶体管的计算机都非常的贵，价值不菲。普通人不但买不起，就算你买得起，你放在家里，除了占地方也没有什么用。比如说现在人家富士康发了善心，给了你一台机床，除非我们把它卖了换钱，要是自己留着的话，只能在家里吃灰。当年电脑也是这个样子，个头大还费电，对个人来说用处也非常的小。

但是呢，随着科技日新月异，电脑的用处也就越来越大，尤其是个人电脑普及，一直到现在的手机。其实现在的手机也是某种程度上说就是一台电脑，而且电脑还越来越多了。你现在花个几千块钱就能买一个很好用的电脑，或者一个还很好用的手机。而且现在用户群也越来越多了，有几亿人都在用这种电脑，或者有10亿人。

我们都知道像硅谷这样一些IT的公司，就对员工就相当来说特别的好。比如说又帮你洗衣服啊，还帮你做饭呀，还帮你带孩子，还帮你养宠物，有可能再这样发展下去，没过几年，有可能连生孩子公司都会找人帮你代劳。一方面呢，我们可以看到两个极端：一方面就是流水线上的这种公司对员工不太好，像富士康员工就不是很受重视；另一方面就像一些大的IT公司啊，对员工就看起来比较好。为什么会出现这种情况呢？我认为从某一些方面来说，就是这些大的IT公司比较人性化，这些老板的人品本来就好，可能比那些血汗工厂的老板人品好1%或者2%。但更重要的一点就是说，对这些IT公司的员工，相比于在那种电子厂上班的员工来说，力量是更强大的，他能够威胁到公司。你如果伺候不好这些员工，这些员工就有可能出去开一个公司，真的能伤害掉这些老板。比如说你开一个IT公司，你离职的员工有非常大的可能马上跟你是竞争对手。但你如果去个电子厂，可能就微乎其微了。我们耳熟能详的很多公司都是这样，就在一个车库里，然后弄出来一个软件，就把上一任巨头给打垮了。比如说我们想一下，如果这个世界上有后悔药的话，当年的IBM肯定会选择把比尔·盖茨给他年薪200万，给他一个单独的办公室，一脚踢进去（这里可能是个误听或夸张的说法，原意可能是“让他进来”），给他洗衣服啊，给他做饭，总比让他弄出个微软来再打压IBM要强很多。如果有后悔药的话，当年雅虎也会直接出100万，把谷歌的技术就买下来了嘛。要知道，当年谷歌的创始人当年想卖给雅虎的话，也不过是要价100万。要是讲讲价，打个又是校友的折扣，估计也就够了。

所以说呢，在IT行业对员工好一点，本身就是老板对自己好一点。在IT行业呢，当然还没有达到流水线员工的那种程度。虽然在大公司里很多的员工跟那个流水线的工人其实差不多，公司的核心业务是懂一点，但是主要是业务首先太复杂，而且是存在了很多年。比如说存在了二十年，你进去的时候你就干了五六年，你不可能知道这个所有业务的影响，所以呢，很大程度上也是个螺丝钉。

这篇周末的感慨就先写到这里。下周周末的时候，我们再谈一谈对这个IT行业的一些感悟，谈谈这个IT流水线对我们这些普通的程序员的影响，以及像我这些已经沦为或者是即将沦为码农的人，他能不能找到一点稍微光明一点的出路？以后别最后像富士康那些员工一样，写着代码写着写着，就给写跳楼自杀了。好的，下一周周末的时候再谈。
