---
title: "可视化的一生(鸡汤文)"
editor: visual
---

我这里只举一个例子吧。其实如果大家不知道这个人，或者没有看过这本书，你得从这个书中抽出几句话出来。但是这也是我最讨厌的事情之一，就是人家说句句，也不联系上下文就拿出来给人讲。但现在好像也没什么好办法，因为你不引用上下文的话，那就可能曲解他的意思。在这里也没办法，只能先举出一个例子来，就是他讲怎么把生活过得别太悲惨。他这样说的：“你就别太透支，那种情况连莫扎特也没法应付。”这里我们都知道，莫扎特是个非常厉害的音乐家，但是他一生都在透支自己的收入，其实他过得很悲惨。虽然有很多钱，但是他花了更多。我在这里再补充一个大文豪，就是大仲马，大家应该知道吧？他写了《三个火枪手》，赚了很多的钱，买了很多的城堡，然后有很多的情人。他最后去世的时候呢，就没有什么钱，城堡已经被人收走了。然后他就到他的私生子那里去，住了几天还是六星期还是六天，我忘记了，好像是个带六的数字，然后他就去世了。他跟他的儿子说：“我来你这里就是要死的。”然后他的遗物只留下了六块钱。

在现实生活中也是这样，很多人就透支自己的收入，比如借信用卡，或者是借那种校园贷。我看社会新闻上有些大学生就拍个照片来借贷款买个手机，结果借了3500，最后要还10万，很悲惨。芒格就讲这种小东西，他说不要太透支自己的收入，但其他的我就不说了。

在这里，我觉得苹果的这个推荐算法还真是挺好的。因为这几天我就不停地看芒格的文章，然后当我关了以后呢，这个苹果可能有一种算法，它推荐了我一堆的鸡汤文。可能是我年轻时看鸡汤看多了，喝多了就齁得慌。所以很多的鸡汤文，我在那看一眼标题我就关了。结果呢，就碰到了一篇不按常理出牌的鸡汤文。

既然这里谈到了鸡汤，我觉得我对鸡汤还有自己的观点可以跟大家说一下。其实鸡汤对人是没有什么坏处的，那种文章对人是没什么坏处。可能有些人比我还讨厌看鸡汤的人，他们就会嘲讽人家说：“哎呀，哪个科学家做了某个研究，那些爱看鸡汤的人呢，就脑袋比较笨，智商很低。”其实这肯定不是这样，因为大家智商都差不多，按正态分布的话，智商差不了多少。只是爱看鸡汤的人，可能这个阶段生活压力真是比较大。看鸡汤呢，确实能缓解这个情绪，让这个生活的压力就像牙疼一样，它始终就那样疼，但是又要不了你的命。鸡汤呢，就像麻醉药差不多，你弄上一下，持续的时间也不会太久，可能就是一个小时、半个小时这样。麻醉药下去了，你这牙又疼了；你看完鸡汤也是这样，你看完这篇鸡汤，你这个心里就好受个半小时或者一小时，然后你这个精神压力又来了。因此呢，你就得一小时或者每半小时或者每一小时就得来一篇，你这个精神压力压不住。

所以微信朋友圈里最多的是什么？就是鸡汤文。这个鸡汤就算再差，也肯定比跟老婆孩子吵架来得好是吧？尤其是像我这个年龄段的，比如说你到35到40岁，你上有老下有小，你要钱嘛，也没什么钱，失业了，你也不可能像马云那种。一辈子也差不多想想就交代了，想想也就很崩溃，就是所说的什么中年危机。所以你就必须得大量的服用鸡汤。你这个喝大量的鸡汤，其实还是有助于社会稳定。

而且这个鸡汤都是有套路的。我把鸡汤分为两种套路，一种就是正派的套路。尤其是那种一上来就讲故事的说：“哎呀，有一个商人、有个教授或者有一个朋友，或者哪里有个总裁，或者谁家的老公啊，什么张三李四就多么痛苦，就很痛苦，或者有很多钱也很痛苦，死去活来嘛。但是呢，经过某种小事，他就开始怜惜人生的大道理，也没什么逻辑，也就乐善好施、乐于助人。最后因果轮回嘛，讲一堆废话，最后达到了人生巅峰，或者获得了心灵的平衡。”你说这有什么用吗？是有用，就管这半小时一小时。但这种套路就是正派的套路，其实就是人给自己穷、自己懒、还有自己馋找借口。比如说那比较胖的，也管不住自己的嘴，也迈不开自己的腿，能找个台阶。你读完这种呢，就一个小时之内，可能这个心里会舒坦一点：“哎，我胖又咋了？我这个穷又咋了，是不是都一样？”但是呢，你一个小时之后呢，你这个痛苦就会回来，因为你没有钱，这个痛苦始终在，就跟牙疼一样。你这个胖衣服穿不进去，这个痛苦还是会来，一换衣服又来，这个时候你必须得再读一遍。

还有一种套路呢，就是反派的套路——骂人。因为大部分人在现实生活中跟阿Q其实都差不多的，那我也是啊。在外面，你有可能被老板骂，在家里被老婆骂，反正你两头都硬不起来。你不能硬气点，就跟那封箱里的老鼠两头受气嘛。有很多学生也是这样，同学呢，你总是看到几个不顺眼的，那老师呢，都个个都不顺眼。现实中你怎么办？你不敢办，就只能这样忍着，你又不敢骂回去。你骂回去，被老师开除了怎么办？你也不敢打回去，有可能打不过人家。如果按照正牌鸡汤的那种套路，就是我们上面说的第一种套路，他就跟你说这是因果报应，显然不行。因为你如果一旦说这是因果报应的话，你这辈子受气，就说你上辈子是个坏蛋是吧？所以肯定不行，而且你骂也不敢骂怎么办呀？你就转发别人骂人的，你自己不敢骂，你就转发一个别人骂人的。这样就这种鸡汤文很多，也是鸡汤。你随便找找，到处都是。就是说我这种反派啊，就是骂鸡汤的主体思想，就是说我并不是不敢惹你，是我不屑理你。就是阿Q那个精神嘛，就是说我这个精神是非常高贵的，因为你这个素质很low，我就不理你。你是不是现在有很多啊？就是什么low逼骂人家low逼，自己就显得自己很高贵嘛。但这也是一种。但我说的这一篇文章很大一部分，对不对不上号，跟我上面所说的对不上号。这篇的文章也许是鸡汤的分类，但是呢，可能由于是我这个段位还是太低，没识别出来的可能性比较大。如果有读者一眼看出来，哎，这是鸡汤们的第三种分类，现在已经进化到第三种分类了，你就留言告诉我是什么？

这篇文章的英文题目叫做“Till the End”，就是讲到终点嘛。有兴趣的读者你可以搜一下，很多的图。他没多少话，就是图。嗯，因为是图的话，我就没法读是吧？所以你可以去搜这篇文章的名字，在Google啊或者在哪里搜一搜，然后或者关注一下我这个微信公众号。我把图——哎，盗版说侵权就侵了他的图。

这篇文章呢，就是说他假使人可以活九十年，就像是前面所提到的那个查理·芒格一样。人家都九十多岁了，还活蹦乱跳，到处演讲，那个还挺厉害的，就是人生的赢家，又有钱身体又好，身体健康。他第一幅图呢，就是把90年按照一年一个格子画出来。因为一年一个正方形的格子画出来，就是你第二幅图呢，它就是把一年一个小圈圈，哎，不是一个月，一个月一个小圈圈，哎，画了个九十年，因为它就假设人可以活九十年。那第三幅呢，就是每天是一个小点，十然后又画了九十年。他还有密集恐惧症的，还不用关注，还挺吓人的。尤其是天的时候也没关系，其实大家应该有所免疫。这个作者呢，比我还小一岁，他才34岁。然后他就开始计算，他还能看多少只超级碗。因为超级碗是一年一次嘛，然后还画了个图，画了每个都有橄榄球嘛。然后在他那个，因为他34岁了嘛，这个那34个就取消了，就画了个叉号。然后呢，还有他说他因为不喜欢冬天或者不喜欢哪里不喜欢去游泳，然后呢，一年去一次吧，哎，又画了一个图，然后又算了，他每年读几本书，五本书或者多少，又能读多少本书。

他说：“他又画了一个图，就是你说有没有意义啊？可能到了我这个年龄就有点感想。对，年轻人可能觉得年轻这段时间还久着呢。哎，后面他还有几幅图，我就不细说了。最后呢，他还是在文章最后说了几句话，就是鸡汤话嘛，但是也没有说你要奋斗啊，也没有说其他什么。他就说，要好好过日子，是吧？九十年嗖的一下也就没了。”所以这篇文章可能有点鸡汤味，可能也由于是我到了这个年龄——哎呀，上有老下有小这种年龄——也有可能。可能就希望大家好好过日子，因为时间真是很快。

这篇文章让我真的很有感想，可能两篇加起来读有点让人受不了。因为比如说，时间过得很快，四年一次的奥运会，大部分人根本看不了20次。尤其是我觉得，现在我们听众中很难有人能看到20次奥运会，可能有少部分活得比较久的人。今年是第几届奥运会？第31届是吧？所以大家可以体会一下，你看，31届了，然而我们所有人都看不了20回。现在想想，还是挺崩溃的。

好了，这篇鸡汤文就到这里，再见。
