---
title: "第15期  短平快前女友的照片是怎么晒出去的？"
editor: visual
---

中国著名的媒体人白岩松，也许曾经痛心疾首地说过这样一句话：“都在低头看手机，有谁会仰望星空呢？”其实在城市里仰望星空，啥也看不见，只能看见个月亮，而且还是在雾霾比较少，并且月亮比较大的时候。抛开雾霾和光污染的问题，对大部分人来说，仰望星空其实没什么意思。当白岩松仰望星空的时候，和他的祖先、秦国的白起、唐朝的白居易以及民国时候的白崇禧所看到的星空其实是一模一样的。我反正觉得没什么好看的，看几次就烦了。我小的时候住在乡下，一眼就能看到银河。但是这个世界上不需要人人都是天文学家，反而是大家都喜欢看手机。因为手机比较能抓住人的注意力，只要愿意，能够随时随地的看到新鲜有趣的信息。比如说，在朋友圈里点几下，就能看见前女友的孩子都已经长大了，见面都已经可以喊叔叔了。

那么我们短平快地说一下，前女友是怎么把照片传到微信上的？微信又是怎么把照片推送到咱们的手机上，还在朋友圈里显示一个喜气洋洋的红点点来提醒我们生气的呢？要讲清楚这个问题，首先要讲两个概念，一个概念是HTTP方法，另一个概念是API。不用怕，我觉得我能说清楚。即使你没有学习过计算机的课程，HTTP方法主要有七种。在这里我们只讲其中的三种，我们可以把HTTP想象成《西厢记》里的红娘。如果有人不知道《西厢记》，那我用一句话来介绍一下，就是一个叫红娘的姑娘，撮合了一个叫崔莺莺的姑娘和一个叫张生的小伙的好事。这里讲的HTTP三种常用的方法分别叫GET、POST和DELETE。翻译成中文的意思分别是取东西、送东西、销毁东西。《西厢记》里的红娘也是做这三种事情。其实，任何牵线搭桥的红娘，包括《水浒传》里的王婆也是做这三种方法。但是在和谐社会讲，西门庆和潘金莲不符合社会主义价值观，还是讲崔莺莺和张生，他们勇敢的追求爱情的故事。其实呢，我个人认为其实差不多，红娘主要做了三件事情：取东西回来给小姐，送东西回去给张生，销毁证据。

放在微信的应用场景里，我们可以这样大概的解释一下：前女友选好了照片，然后点击完成。这个时候，HTTP这个红娘马上启动一个PUSH的方法，把照片发了出去。然后我们的手机就会也是执行一个HTTP方法，在这里HTTP相当于红娘，它执行一个GET的方法，把照片取回来。然后你看了以后，可能心里五味杂陈，小手一抖，点了个赞。点赞的时候，相当于你手机上的红娘启动了一个POST，把一个赞发了出去。这个时候呢，你前女友的手机上的红娘也没有闲着。这个红娘呢，她会执行一个GET的动作，把你发的这个赞取了过去。这个时候你的前女友应该看到了你点的这个赞，她应该就很纳闷了。这个时候她也许在想，哎，这家伙到底是什么意思呀？给我点个赞，是兴高采烈呢，还是幸灾乐祸呢？是因为我的妆化的不好看呢，还是他看出我用美图秀秀来了？结果她纠结了15分钟以后，想想还是删了吧。然后他执行了一个删除，这个时候呢，他会让红娘（HTTP）马上起来响应。这个HTTP就响应了，开始发送一个DELETE，这个照片就删除了。

至此我们就讲完了HTTP三个常用的方法，分别是GET、POST和DELETE。另外的一个概念就是API。这个API的全称叫做Application Programming Interface，简称是API。现在基本上所有的网络服务都用API，每一家成功的网络公司对外提供的服务都是API。比如说Google提供的搜索，它会提供一个搜索的API；亚马逊则是提供商品的API；腾讯提供的是各种服务的API。这些API定义了这些公司。本质上来说，我们所使用的网络服务就是API。如果搞创业公司的话，其实只需要想清楚或者问清楚一个问题就行了，就是要给用户提供什么API？这个API用来做什么？如果答案简明扼要，那很好啊，说不定这个公司就有前途。如果在这个问题上，创业者尤其是CEO给出的答案都非常的虚，比如说我们这个API是改变世界的，还是改变人类，让中华民族屹立于世界民族之林。那时候加不加入这个公司，就真的好好想一想了。

好了，再说一下夹带私货的时间，我打算在哔哩哔哩这个网站上上传视频。这个视频是从零开始使用Swift开发一个iOS软件，一直把这个软件做到能在Apple Store上上架为止。主要的内容就是使用我上面所说的HTTP的各种方法来操作各种网站的API。我还没有想好用哪个网站，目前我看了一下，因为很多优秀的网站都被封了，到时候再说吧。比如说Twitter、YouTube、Facebook，他们都提供了非常优秀的API，但国内的呢，就基本上都不太友好。因为我跟微博打过交道，微博的话，你这个API经常是有很多限制，所以我还没有想好怎么做。比如说发照片呀，用那些API发照片，比如说到烂番茄上面，每个网站都有各种各样的API可以发照片啊，怎么去看电影？比如说从iTunes（我们用苹果电脑的话，就会知道有个叫iTunes的），上面你是可以看它的MV啊，或者是电影的预告片，那个都可以用API取回来。就怎么看电影、怎么看照片，欢迎大家到时候去围观。是免费的，不要钱。

我做这个东西的原因呢，是我在上一期音频里也说了，上一期音频就是钻钻牛角尖——《电脑开机干了啥》里面我讲了，就是说我发现这个教育跟现实脱节嘛，所以我想看看能不能做一些什么事情，做一些叫什么“杯水车薪”或者是“螳臂挡车”的事情。不过我现在还没有开始做，先做做广告，因为我没有其他的什么好的途径。我的广告对象就是这个公众号“软件那些事”里面一共40来个兄弟，实在是打扰了。大概20%的人会打开，其实大概10个人会看到。好，这次短平快的音频到此为止。应该到现在你应该知道了前女友发照片的技术流程。如果知道了这些以后，下次再看到他发照片的时候应该更生气了吧。因为打扰到打开微信公众号的这十几个兄弟，为了表示歉意，最后在公众号里，我放一张我前女友的照片（此句为玩笑话，实际操作时请尊重他人隐私）。
