---
title: "Linux传奇：0.01版Linux出生了"
editor: visual
---

在1991年9月17日，Linux把这个操作系统发布到了FTP上，0.01版的Linux也终于出生了。在4个月之前，Linux发帖寻找POSIX标准的那一天，这个FTP就已经被阿里·克莱姆设置了。在4个多月的时间里，这个孤独的FTP文件夹被命名为“linux”。虽然Linux起初想把这个操作系统起名为“Freax”，这个英文单词的意思是“怪胎”，但是阿里·克莱姆并不喜欢这个名字，于是就使用了“Linux”这个名字。

在很多年以后，Linux在接受采访的时候说：“我是个自大狂，我用我的名字来命名我所做的软件。第一个是Linux，第二个是Git。”Git这个单词在英语中并不是“饭桶”的意思，而是一个版本控制系统的名称。Linux说，0.01版的Linux大约有一万行代码，如果用小一点的字体，用不了100页纸就可以打印下来。要知道现在Linux的内核已经超过、快奔向2000万行代码了。如果打印出来的话，一辆金杯车肯定是装不下的。

在他的自传里，Linux不无谦虚地说，那个时候Linux只是一个能够运行shell的程序而已。这句话当然是非常谦虚的，在我看来，能够运行shell程序的就已经算是操作系统了。在这本自传里，我们可以看出Linux使用了一个叫做Bash的shell，到目前为止，这是大多数Linux系统以及Mac系统默认的shell。这个开源软件是1987年由布莱恩·福克斯创造的。

当我们在使用Unix或者Linux的时候，如果我们钻牛角尖的话，其实我们并不是直接使用操作系统的内核本身，而是使用一个叫做shell的程序。这个叫做shell的程序是一个命令行解释器，我们通过它与系统内核进行交互。换句话说，shell相当于是内核的秘书，我们只和这个秘书打交道。如果这个秘书需要做什么事情，他就去和操作系统的内核打交道。这个shell当然也不是什么奇特的东西，只是一个普通的秘书。所以除了Linux选择Bash以外，还有非常多的秘书可以选用，比如说ksh、csh，还有tcsh等等。当然，你只要会用一个就可以了，大部分都会选择Bash。当然我个人选择的是一个较旧的zsh的shell，但都是萝卜白菜各有所爱，越用多了、越用顺手，就越离不开其中的一个。

这篇文章主要是分析Linux自传中的这样一句话：“那个时候，Linux只能运行shell的程序而已。”因为这句话也是Linux自己一个谦虚的说法。为什么要只要能运行了这个shell程序，Linux就很高兴，并且把这个以前的终端仿真器就直接作为操作系统发布了呢？因为所有的东西，包括操作系统、任何东西、电脑等等，都有一个最核心的功能。这个最核心的功能是不能丢的，只要把这个最核心的功能丢了，这个东西就已经被“散架”了。

我们举一个例子，比如说一个杯子，最核心的功能是什么？就是喝水。杯子的花纹到底漂不漂亮？是红色的还是黄色的？这些也重要，但并不影响它核心喝水的功能。但是如果你说一个杯子花纹都很漂亮，然后有各种美丽的图案，但是就是不能喝水，那么这个就不能称作为杯子。

我们再举一个例子，比如说有一个国家叫朝鲜，它的政府最核心的功能是什么？就是为了让那2500万人吃饱饭，然后最好是幸福自由地过一辈子，生活得有点尊严。

朝鲜有一个电视台叫中央电视台，周一到周六每天都播放7个小时的节目，周日每天播放13个半小时。这个电视台当然是非常有特色的，按现在的话来说简直就是一股清流，没有任何商业广告。我当年出于好奇，下载过一些简单的介绍。这个电视台上来二话不说，先轮番放几首歌，第一首歌就是朝鲜的国歌，第二首歌是金日成将军之歌，第三首歌可能是金正日将军之歌（注：金正日是金日成的儿子，已去世），第四首歌的情况我不太清楚，可能是开玩笑的说法，因为金正恩是80后，现在还健在，我估计她得去世以后才会有专门的歌曲。然后这三首歌会不停地循环播放，可能会持续两个小时或两个半小时。在放歌的时候还会有些变化，比如会出来文工团（在朝鲜不叫文工团，可能叫欢乐组）出来跳舞边唱，期间也会有一些领袖语录等，你可能听不懂。等到两个多小时酝酿得差不多了，也就到下午五点多了，然后整个朝鲜也没有其他电视台，你想换个台都不行，就这一个台只能看这个。你想看个广告啊、电视购物啊、那种像8848那种傻了吧唧的手机广告啊，根本没有。等到五点开始，五点到5:30，就会是整个电视台每一天最重头戏的开始。朝鲜的那些人们就开始搬一个小板凳，在电视机面前就赶紧主动打开自己的“脑壳”（此处可能是语音识别错误或夸张说法，应理解为“关注”或“精神集中”）看半小时。一个叫《报道》的节目，报道翻译成中文就是讲新闻。这个节目主持人叫李春姬，前20分钟她就慷慨激昂地讲述朝鲜的伟大成就以及各个领导人的忙碌，基本上就是走路时周围一群人围着拿着小本子到处视察。后10分钟就慷慨激昂地骂美国，说美帝国主义狼子野心。她的声音被朝鲜媒体评为可以让敌人胆战心惊，还有她的声音可以让敌人什么肝胆俱裂（此处为夸张说法）。我不知道敌人有没有肝胆俱裂，反正我是“裂”了（此处为夸张说法，表示印象深刻）。我十年前左右的时候看他的视频，到现在还余音绕梁，十年了经常从梦中惊醒。就这个李春姬，我估计这一辈子我是忘不掉她了，真是“在人群中多看了她一眼，再也没能忘掉她的容颜”。

就这样整天被洗脑嘛，真的是面对那个大胖（金日成）、二胖（金正日）、还有三胖（金正恩）的照片痛哭流涕。我还看过一个纪录片，美国的医生帮朝鲜的人去治疗白内障。然后这些被治好的人一下子看到光明了，第一件事情就是对着墙上的金胖子们磕头。然后等到磕完头之后一看，哎呀，竟然是美国医生帮他们治好的，这个眼神子就充满了痛恨。

其实呢，一个政府你有没有原子弹啊，或者是不是三胖33岁就会打手枪、7岁的时候就会开坦克。这些其实都不是政府的核心功能，政府的核心功能就是你要让老百姓自由一点、幸福一点其实比什么都强。

在这里我们就讲电脑的操作系统最核心的功能是什么？就是通过一个界面让我们管理并且使用硬件就行了。至于这个界面是不是丑啊、是不是容易崩溃啊、不稳定啊。那显然都是次要的，即使界面也不是很好看，并且这个还经常运行一段时间就自己挂了、比较丑、还很容易崩溃。其实0.01版的Linux就是这样。但是呢它满足了操作系统的核心功能，它确实能够管理并且使用硬件，而且使用的界面是shell，可能暂时丑一点也不稳定。但是它肯定这个东西就是叫操作系统，以前那个只能算是终端模拟器。

因为在Unix系统中呢，shell是所有的程序之母。只要你运行了这个shell，你才能再运行其他二进制的程序。为什么这么说呢？因为shell的原理简单来说就是如果你要运行一个命令呢，shell就先生成一个子进程然后再让这个子进程去执行这个命令。在Linux操作系统中呢所有的进程都有一个共同的主线这个进程就叫init进程。

为什么会这样呢？我们可以从Linux发的帖子中找到原因。因为他在发0.01版的Linux的时候他介绍这样说：“因为我的操作系统和Unix有点雷同。”通过这句话我们可以看出当年他确实是在模仿Minix尤其是文件系统。当然了这个里面的进程也是因为在这个Minix操作系统中啊就有一个init进程作为其他所有进程的祖先。但是如果一个系统中只有这个init进程其实也没什么用。因为在操作系统中你只有这个进程而没有其他进程的话尤其是没有shell进程的话这个操作系统就没什么用嘛因为你没法操作它。所以说做一个操作系统最重要的还是你要把shell启动起来。

正因为如此呢Linux他在他的自传中就这样说用了大量的篇幅就来说这个shell这个事情他兴奋地说我甚至通过书都能看到他的兴奋了。他说一旦shell程序运行了就等于进度从接近零转眼飞窜到了100。因为所有的准备工作都已经到位有时候我会有一种创世的错觉因为在此之前还没有什么东西能真正的运行起来。既然这件事如此重要我再花一点篇幅来说一下这个shell的工作原理顺便介绍一下进程和内存管理的事情。

不知道大家有没有看过一部叫做《致命魔术》的电影那个是克里斯托弗·诺兰导演的这位导演是我最喜欢的导演之一。就这个《致命魔术》里呢有一个反派的老大他的绝活是什么？演魔术嘛就是复制自己每次表演魔术的时候就使用特斯拉提供的一种高科技把自己这样复制一份一模一样的。在Unix上呢每时每刻都发生着这种复制这个过程就是fork操作（注：原文中的“folk”为错误拼写）fork操作的精髓就是复制一份和自己一模一样的进程。新的进程里所有的数据包括变量、环境变量、程序计数器啊和原来的进程一模一样。但是呢一个全新的进程虽然是一模一样但它还是一个全新的进程。

就跟我们说的《致命魔术》中他把自己复制了一下那个反派的主角一样。因为新的进程里所有的数据都一样嘛所以呢你想一下Linux中所有的进程都应该是成树状结构因为所有都是复制的嘛它一定是不停地在形成一个树状结构根节点肯定是init进程其他的进程呢都有自己的父亲根节点没有父亲的就是init进程本身。比如说呢在shell下你运行了一个命令这个命令的父亲是shell进程因为我们都是和shell进行交互嘛所以这个shell就不停地当爹当父亲他就负责创建子进程来执行我们的操作。

所以说呢，shell 程序又称之为进程之母，当然这里有点混乱。因为我们的教科书，一会说进程之母，但是呢，它里面又说这个不叫母进程，要父进程。所以说，如果统一一下的话，应该说，如果你称之为进程之父呢，就应该每个进程都有自己的父进程；你如果称之为进程之母呢，那应该每个进程（理论上）都可以追溯到一个最初的母进程（但实际上更常用父进程的概念）。结果我们教科书里挺搞笑，一会说他每个人都有“父亲”，但是呢，它又叫进程之母。

但在这个自传里面，Linux 说这个0.01版本的Linux最多支持64个任务，也就是说最多最多就是有64个任务同时进行。因为进程都有一个唯一且不可冲突的整数来作为标识。这个进程标识就是一个整数，一串数字。这个数字呢，叫 PID（Process IDentifier，进程标识符）。在目前的Linux上，这个数字是从1开始一直到32768，其中1这个进程是不变的，是init这个进程（注：现代Linux中可能是systemd等其他init系统）。其他数字呢，就这样2、3、4……一直用到32768以后，用完了，它就再从1开始再重新用一遍（实际上是采用循环分配的方式，但会避免与现有PID冲突）。如果你再用完了（理论上不会完全用完，因为会有进程结束释放PID），又会从某个未使用的编号开始用。

但因为当年是0.01版本呢，它最多只能支持64个任务，我觉得也已经是非常了不起的成就了。

希望通过这篇文章，能让大家了解，为什么Linux上只要弄好了shell，就感觉开发进度一下子从零快进到了100。因为从某种意义上来说，你只要能够运行shell，并且能管理这些硬件通过shell那个接口（或说环境），那基本上就称之为操作系统了。虽然现在还经常容易崩溃，界面也不好，还经常把硬盘给弄坏。但是呢，这就是一个有点bug的操作系统。

好，这期就到这里，再见。
