---
title: "任天堂的前生今世(上)"
editor: visual
---

我小时候就很喜欢玩游戏，特别是在小霸王学习机上玩的超级马里奥。其实，直到我上了初中以后，才知道这个游戏是任天堂出品的，那时候，我们都不叫它超级马里奥，而是叫它超级玛丽。当时，我心里还有点儿奇怪，怎么一个大胡子叔叔的游戏，会起了个这么像女生的名字呢？

后来随着学业加重，我玩游戏的时间也越来越少，毕业工作之后更是少之又少。但每当聊起游戏，我脑海中第一个浮现出来的总是超级玛丽。我依稀记得，在一个下午，超级玛丽的一关游戏情节是这样的：马里奥跳上一个类似打气筒的东西，每跳一次就会打一些气进去，跳到第三次或第四次时，一下子就能把坏蛋喷上天。当时我觉得这个动作太搞笑了，就这一个动作，我反反复复地玩了一下午，每次都笑得前仰后合。

说到怀旧，我想聊聊任天堂的故事。任天堂这些年来历经风雨，浮浮沉沉，我总担心有一天它会被收购或者倒闭。毕竟在智能手机兴起之后，固执的任天堂显得有些跟不上时代了。在讲述任天堂的故事时，我会反复提及任天堂发展历程中，当年的中国在做什么。这个音频节目的名字叫《软件那些事儿》，这个名字是模仿《明朝那些事儿》取的。我是一个历史爱好者，虽然水平业余，但闲暇时喜欢看的书主要有三类：历史书、科技书和科幻书。这个音频节目的听众非常少，大概只有个位数的听众，我觉得最重要的听众可能是将来的我，所以我就讲得随心所欲一些。

尽管这几年任天堂在科技界已不再是主角，但在游戏界它仍然是举足轻重的巨头。毕竟瘦死的骆驼比马大，任天堂头上的光环依旧耀眼。然而，如果把时间的指针拨回到130多年前的1889年，任天堂刚刚诞生的日子，谁又能想到这个当初制作骨牌的小作坊，日后能成长为举世瞩目的游戏巨头呢？

在19世纪60年代，中国和日本这两个古老的亚洲国家都内外交困，在闭关锁国时被西方国家强行打开国门，仓促应战。面对内忧外患，这两个国家都走上了以变革求富强之路，日本进行了明治维新，中国则进行了洋务运动。

明治维新的结果是德川幕府被迫交出权力，天皇掌权，并废除了德川幕府的名号，为日本的近代化打下了坚实的基础。明治维新将日本的商业力量加以集中，商业开始影响全国。日本在1872年建立了铁路，1882年建立了西方银行，得以跻身世界强国之列，为后来出现一批世界级公司迈出了坚实的一步。任天堂就是在明治维新成功之后建立的。

而在大洋彼岸的中国，也进行了一场声势浩大的洋务运动。当时的清王朝只是希望借此巩固自己的权力，让清王朝自己革自己的命，自然是难上加难，最终以失败告终。中国继续在王朝更迭的道路上反复，当时的清王朝依旧沉浸在天朝梦中。

1889年，一个叫山内房治郎的人成立了任天堂骨牌公司，“任天堂”在日语里的意思是“谋事在人，成事在天”。作为一个提供赌博工具的公司，任天堂这个名字取得非常贴切。当时任天堂生产的产品是花札，一种日本传统的纸牌。我查到的资料显示，当时日本黑社会庞大，他们每次赌博都会换一副新牌，不像我们在大学时打扑克，一副扑克能玩四年。所以，花札的需求量很大，任天堂公司得以迅速扩张。

1929年，山内房治郎将任天堂公司传给了他的上门女婿山内积良（山内房治郎只有一个女儿，我未查到关于他女儿的任何资料，只知道女婿叫山内积良）。这里说点小知识，山内是日本的一个姓氏，如果入赘就要改姓。因此山内积良以前不姓山内，而是姓金田，叫金田积良。这个山内家族还有个传统，就是生儿子的概率不高。比如山内房治郎没有儿子，事业传给女婿山内积良；山内积良也没有儿子，本来要传给入赘的女婿（也就是山内溥的爸爸），结果山内溥的爸爸和另外一个女人私奔了，最后只能传给外甥山内溥。

我猜这件事对山内溥影响很大，毕竟老爸为了爱情私奔了，所以山内溥一生和子女关系都比较冷淡。比如，他给女儿过20岁生日时，如果是一般父亲，可能会搞得温馨一点，去餐厅切个蛋糕，唱首生日快乐歌；但山内溥却直接领女儿去了艺妓店。当我得知这件事时，还在读大学，就和寝室的哥们说了。我寝室的哥们是个任天堂的忠实粉丝，他查了很多资料要为山内溥正名，他和我说日本艺妓都是卖艺不卖身，男女关系很纯洁。我有点不太相信，毕竟也看过不少日本的影视作品。不管怎么说，女儿过生日带去艺妓店还是有点儿不寻常。更厉害的是，女儿过完生日都回家了，他还在和艺妓交流感情。

说到这里，我突然想起了苹果公司的乔布斯，他的父亲也是这样，孩子都没见过就走了，是个纯粹的革命播种机。乔布斯有个妹妹，和乔布斯一样是个大作家。还有美国的总统奥巴马，他三岁的时候，老爸就走了，直到奥巴马10岁才回来看了一次，然后至死都没有再见面。我突然思考了一个严肃的问题：为了孩子将来能成才，我是不是也应该私奔呢？

前面说到，1929年山内房治郎把任天堂骨牌传给了女婿山内积良之后，山内积良不负老丈人的期望，进行了一系列的投资、重组等，把任天堂骨牌改成了股份制公司，并重命名为山内任天堂公司。在1929年到1949年这20年期间，任天堂在山内积良的带领下虽不能说一帆风顺，但也是螺旋式上升。此时，任天堂已经开始使用机器生产扑克牌和花札，并且组建了自己专门的销售公司——丸福公司，用现在的话来说，实现了产销一体化。到1949年山内积良因病退休之前，公司已经扩张到100多人。

在我们的大主角山内溥正式登场之前，再来回顾一下同期中国的情况。从1889年任天堂建立到1949年第二任社长退休的这60年间，中国也发生了巨大的变化。先是搞君主立宪的闹剧，后来八国联军侵华，后来军阀混战，再后来抗日、内战，基本上一直在打仗。在战乱中，想活命得靠运气，而且革命党还尤其喜欢暗杀。所以，当日本的任天堂经过了两代人或多或少的沉淀之后，中国还没有任何企业生存的土壤，仍然是家天下的国家。

接着回来说任天堂。1949年，新中国成立的这一年，山内积良因中风不得不将公司交给下一代接班人（多说一句，任天堂第一任社长山内房治郎也是因为中风把公司交给山内积良的）。此时，山内积良的女婿已经和别人私奔了，只剩下唯一的传人山内溥。当时山内溥22岁，尚在日本早稻田大学读法律。在接受外祖父嘱托之前，山内溥提出了一个条件：如果让他接手公司，其他所有的族人都要退出任天堂公司。山内积良只好答应。

山内溥上任之后，此时日本刚刚战败第四年，大部分民众生活比较困难，但家境富裕的山内溥显然没打算勒紧腰带过日子。他很快就在涩谷区购买了房子（电影《忠犬八公》中的车站就在涩谷区），生活非常奢侈。由于山内溥在接手公司前提出的要求是清除所有的族人，他开始着手清除所有供职超过20年的员工，这引起了100多名工会员工的罢工。山内溥通过关闭工厂、暴力镇压、买通警察等方式，在1950年解散了工会。接手公司几个月后，员工已经解散了一半，曾经跟随山内积良打天下的老臣都纷纷离开了公司。

与此同时，山内溥广泛招聘高学历年轻人才加入公司，给予高于市场的薪水，将任天堂变成了一个独裁的公司，公司只有他一个人说了算。他把负责销售的“丸福”改组为“任天堂骨牌有限会社”，在京都市中心购买大量土地建立新工厂，将落后的设备更新，推出新的塑料扑克产品。这些措施都让任天堂的市场占有率稳步提升。在1959年，任天堂和美国迪士尼公司合作，推出印有米老鼠图案的扑克。在广告的轰炸下，当年卖出63万套扑克，占日本市场份额60%以上，这63万套扑克相当于任天堂过去15年销售的总和。在这次巨大的成功里，有两个关键的因素：一个是改组后的丸福销售网络，联合诸多玩具厂商组成了一个遍布全日本的销售网络，山内溥给这个销售网络起了一个名字——钻石会。后来这个组织发展成了控制日本游戏销售的初心会，初心会为任天堂的发展立下了汗马功劳；另一个关键的因素就是“米老鼠”。

米老鼠扑克的成功，也让山内溥了解到了“米老鼠”的威力。要想成为世界一流的公司，任天堂也必须要有自己的“米老鼠”。只要有了自己的“米老鼠”，不仅可以让扑克大卖，也可以让任何产品迅速取得成功。任天堂逐渐确立了自己“软件为主，硬件为辅”的经营哲学。

在1956年，山内溥前往美国进行考察。经过观察，他发现美国最大的扑克公司其实只是一家中小型企业，反倒是美国强大的工业实力给山内溥留下了更为深刻的印象。扑克的市场规模实在太小，即便做到世界第一，也仍然只是一个微不足道的小公司。在接下来的几年里，任天堂公司一帆风顺，成功上市，股价大幅上涨。然而，这一好景持续到1964年东京奥运会结束后，任天堂遭遇了严重的危机，股价从600日元的最高峰暴跌至不足60日元。在内外困境的夹击下，山内溥毅然决然地采取了反击措施，尝试了多种挽救方法。下一期我们将继续讲述山内溥尝试了哪些方法，以及最终如何让任天堂成功实现转型的故事。
