---
title: "Unix痛恨者手册读后感"
editor: visual
---

在前面两期的那篇“Unix 和 C：里奇留给人类最好的遗产”里，我提到了一本书叫做《Unix 痛恨者手册》，并且我把这本书放在了百度网盘里。如果有人没有听过那一期的话，我就再在这里放一下地址，希望有这种爱好者可以去看一下。本来这一期我想讲 Linux 的，但是我还没有想好 Linux 的文章应该怎么写。因为 Linux 这个故事本身就非常值得去讲一下，因为它的用途非常广，所以暂时在这里我就放一篇我很久以前写的读后感。

当然，后来因为做这些公众号的文章，我还是把那篇读后感看了一下，并且思考了一下。我发现当年我的很多观点已经发生了改变，也许以后这篇文章的观点还会继续发生改变。所以这篇文章都是我主观性很强的东西，随着以后的情况可能还会发生改变。所以大家随便听一听就好。

为了照顾没有看过上两期公众号文章的人，我就先简单地介绍一下这本《Unix 痛恨者手册》这本书。这本书呢，我们可以通过名字一下就能猜出来，这是骂 Unix 的。这本书的几个作者呢，就是恨 Unix 已经恨到了惊天动地的程度，所以还写了一本书专门来骂它。

比如说我们普通人，爱一个东西爱的惊天动地，可能会出一本情书集。比如说咱们中国就有一本很出名的情书集，叫《朱生豪情书》。昨天不是七夕嘛，那些美女朋友们应该赶紧买一本这个《朱生豪情书》来读一下。他是民国时候的一个诗人、作家，就是写给一个叫宋清如的女诗人的情书。他们两个人共同翻译了整个莎士比亚的戏剧。我虽然从来没有看过莎士比亚的戏剧，但我觉得作为单身的人嘛，应该学习一下这个朱生豪的情书，还是挺有意思的。所以当年的时候我就买了，我随便念两句给大家听听，他写的都很美好，比现在的歌词都好。比如说：“我想作诗，写雨，写夜的相思，写你，写不出。”再念一句吧：“我们都是世界上多余的人，但至少我们对于彼此都是世界上最重要的人。”哎，如果有人喜欢，可以去买一本，很便宜，这种书也没人买。现在应该单身的人可以去买一本学习一下，人家当年是怎么追女朋友的。不过现在这个年代可能也不太好了，你可能没有车子、没有房子，你写这些东西写得再好也没什么用处。你光写的诗好，可能用处也不大吧。不过，这个朱生豪里面也写了篇文章，他评价中国人说，中国人太不浪漫了，务实到心理卑琐的地步的缘故，因此这个情感与想象都很缺乏，就既没有情感也没有想象。

好了，这里不说这些了，再来说说这本 Unix 的书。如果有读者听过上一期又恰好下载了这本书的话，那就更好了。或者在其他地方读过这本书也挺好。因为我这个公众号没几个人关注，就是每期的文章阅读人数六七十人。上一次我放百度网盘的链接，我刚刚去拷贝这个链接的时候，我看了一下，总共就五次下载。所以我还是大体地说一下这本书的内容。

这本书主要是骂 Unix 的，总结的就是 Unix 各种的缺点。但是能够真正算是 Unix 缺点的呢，不到一半，剩下的一半很多都是骂 C 语言啊、嘲笑 C++ 呀。还有一部分是嘲笑 Unix 上的软件，比如说 cinemail（可能是 cinemail 的误识别，实际可能是某个具体的邮件客户端软件名，但无法确定准确名称）。所以本书甩出去的黑锅非常多，但 Unix 本身可能只能背个一半，背个五成，其他的都是编程语言和软件方面的问题。比如说是 Unix 啊，就整个 C++ 的问题可能是 C 语言的问题。

Unix 有很多面向个人的软件，有很多人是用 Unix 做桌面的。包括现在我们的 Linux，有少部分人，我见过那么一两个，就是用 Linux 做桌面，也不玩游戏，就是开个网页。就是说很多这种软件呢，你体面一点说呢，就是你还需要继续的雕琢；直接一点说，确实不太好用。比如说这本《Unix 痛恨者手册》里提到的那个 cinema（可能是对某个软件的误识别或误记）这个软件，我以前配置过，觉得确实很难配置。还有一个就是收电子邮件的，叫 fetchmail，也不好用。但这个软件的作者之一啊，就叫艾克雷蒙德。这个人挺能写文章的，而且还非常热衷于到处讲座。你说他真正参与了哪些软件呢？确实不多。这是我唯一知道的一个就是 fetchmail 是他自己搞出来的。你说他的技术水平比起 Stallman、Lindas 或者是 Larry Wall 这种的肯定是远远不如人家。但这个人有一点很厉害，就是写文章，其他的人都不怎么写文章。他这个人写文章、办讲座，就是推销整个的这个软件的理念，尤其是开放源（open source）这个软件的理念，算是高手。他写了不少文章，其中有本书名字都非常大，叫《Unix 编程的艺术》。但是我个人觉得，如果你钱不是特别多的话，这本书不要买，没什么意思看了。比如说呢，他不停地说他就是某 zzz 了开源软件，就是他的功劳。因为他名气大嘛，可能人家也不好意思否认，其实按照常理推测的话，应该是不怎么靠谱。比如说 Mozilla 开源，很大程度就是微软要把他给干败了嘛，不可能是说他看了他一篇什么叫《大教堂与集市》的文章，这个公司就决定开源。而且这个人写的所有的文章都是非常宏大的题目，就跟毛泽东一样，《论民主》、《论新阶段》。他写的文章呢也都是非常宏大的题目，比如说《论黑客精神简史》，或者是《论黑客的报复》，就这种的，你看了跟没看也差不多。你看了呢，你也不清楚他到底说了啥，说错了你也不好意思说他说错了，因为他的观点也不怎么新颖，他具体工作还有。他不停地说他维护了一个叫黑客字典，其实就是网络的俚语字典，我还去看过，就类似于现在网络的俚语。我个人觉得挺无聊，他倒是不停地说他这个工作很重要。

比如说现在很多网络俚语，我们就知道火一阵，有可能就火个两周、几天，以后大家就不说了。他记录下来，比如说呢，这本《Unix 痛恨者手册》里面就有很多类似的就真知灼见，并非是这篇文章所说的就骂街一样。不是的，就是我个人还是非常支持 Unix。你看我写了那么多文章，你应该知道。但是我认为这本书有非常多的可取之处，并不是乱骂。

再说一点，就是说在桌面端，我们现在用的桌面的 Windows 用户肯定是多于 Unix 或者 Linux 的用户。很多的初学者呢，就是先用了好几年的 Windows，然后呢，突发奇想可能就是想编程了，或者就是纯粹的想去用一下 Linux，就好不容易整了个光盘或者什么就装了，然后又没用两天就赶紧删了，又回到 Windows 中。过一段时间他可能又再重复一次周期性地去安装 Linux。为什么会出现这种情况呢？在这里我来谈谈我的观点啊，结合这本《Unix 痛恨者手册》来谈谈我的观点。

就是说呢，Windows 用户的设计哲学就非常的跟 Unix 非常的不同。Windows 呢，他一定要假设有一个人就是在电脑前面去操作。你只要是呃这个人不操作了呢，Windows 设计哲学就是：我发现你不操作了，那个电源管理里就有一个选项嘛，就是说你多久不操作我这个屏幕啊，我就先给你待机。而 Unix 或者 Linux 设计哲学就完全不同。它的设计哲学就是：我只要运行起来呢，这个电脑前面你就是可以有人也可以没人，随便，最好是没人，其实你可以远程来操作。比如说你用 SSH 登录上去，基本上就是说你现在所有的网站啊、服务器啊，基本上都是用 Unix 或者 Linux 系统。目前我所知道的基本上都是这样。

因此知道了这个设计哲学之后啊，我就觉得如果你还是在那种 Linux 上折腾怎么装中文输入法，或者是你怎么用一个叫 Wine 的软件在 Linux 上运行微软的 Office 软件的话，那你就搞错了。比如说你可以运行 Office 2003、2007，用那个软件你装上之后呢，你就可以在 Linux 上运行 Office 软件。但是我觉得这本身就搞错了。为什么说搞错了呢？因为 Linux 本身就不是这样玩的。你那些用 Linux 做主力桌面的，肯定是非常的小众。你在 Linux 上，你即使装上了这个，你输入法有可能就搭配的不好。比如说你装上 Office 能运行了，结果你输入法在里面输不上字，非常有可能出现这种情况。而且你想玩个大型游戏，想玩个什么《FIFA》、《实况》啊，根本就没法玩。所以如果还是有同学喜欢在 Linux 上折腾这种情况的话，我建议还是别折腾自己了，就赶紧开机或者是启动到 Windows 系统上，或者去苹果电脑上去玩。

如果你是运行一个网络服务，比如说你做了一个网站。这时候呢，你最好就是用 Linux。为什么呢？因为大家首先都在用，你出了问题，网上搜一搜呢，你容易找到解决方案。当然也有人说微软也有做这个网站的服务器嘛，就是 Windows Server 那个系统。比如说 Stack Overflow 这么大的网站，人家就是用 Windows，但是还是用什么 .NET 开发的。但是这就属于非常小众，这就属于抬杠。就跟我前面说的一样，就有人就用那个Ubuntu做主力桌面，但是那是小众。也有的网站就是用 Windows 做这个主力的，但是那也是小众。因为我们还是要随大众，因为你大众的话找解决方案的话会好很多。

所以我的观点就是说，你如果是个人用户，不是为了学编程，你就用这个 Windows 或者 Mac。如果你想做点事，比如说想学个编程啊、做个网站或者做个应用什么的，你就用 Linux，最好是装个双系统，两个都不耽误。没必要像网上很多人说的完全用某个系统，比如说完全用 Linux 工作，或者完全用什么东西工作。我看过一大部分的文章就是告诉你哎我怎么在这个Ubuntu上装上输入法、装上 QQ，其实这不仅误解了 Linux，也误解了 Windows。我们不能没事就写这种、看这种文章，就是发动圣战来讨伐哪个系统。讨伐 Windows、讨伐 Linux，其实也挺无聊的。

当然，我写这篇文章，很大程度上就是因为有两个关注我微信公众号的朋友问我这种问题。当然，这两个小朋友都非常小，其中一个刚刚要去大一，就问Ubuntu上哪个中文输入法好。但想在Ubuntu上配置一下这个“Wine”这个软件。可能听众不知道这个“Wine”软件的话，我就说一下，它就是一个可以运行在Linux上，但是模拟微软操作系统API的一个兼容的软件。也就是说呢，你装了这个软件以后，你在Linux上再安装QQ啊或者Office啊，这些软件就认为自己是运行在Windows上。就这样。

以前的时候，我，我上大学的时候就有了，现在我不知道，我已经好久不折腾这种事情了。对于这两位朋友，或者是再有类似问题的朋友，我的建议就是：如果你要运行微软的Office啊，或者是搜狗输入法或者是腾讯输入法，这种中文输入法，你就真的没必要在“优帮”上折腾。虽然你装了这个软件，就比如说这个兼容层的软件可能是可以运行起来的，但是你为什么不直接用个Windows的呢？是不是？如果这样的话，你还可以省一些时间，然后去读一下我文章开头推荐的那本情感书籍。比如说，就是那个叫《朱生豪情书》的，找个女朋友，也别总让人家笑话咱们这种程序员找不到女朋友什么的。

好了，这期就到这里。
