---
title: "张嘴看世界——三胖家的互联网是什么样的？"
editor: visual
---

三胖家的互联网是什么样的？

昨天看了古巴互联网的新闻以后，我就一直想查一查朝鲜的互联网大概是什么样子。可惜啊，这个资料实在是太少了，三胖家保密得实在是太厉害了。查到最近的新闻是三胖家去巴西参加奥运会，奥组委给每个运动员都发了一台奥运会定制版的手机。朝鲜呢，第一时间他的公务员就把这个机器给没收了，为了防止这些运动员和外界联系。朝鲜的运动员如果能够获得金牌，回国以后最大的一个奖励是奖励北朝鲜首都平壤的户口，同时没收这个定制款的手机。这样算起来也不算什么，毕竟你有可能安静地准备比赛，说不定回去还能获得一个首都户口。

关于朝鲜的新闻啊，我查了很多，实际上起码我的能力是无法真正地确定真伪。大家每个人有自己的智慧嘛，希望还是自行判断，毕竟朝鲜这个地方实在是太神秘了。

先说一下朝鲜的网站，昨天我说过古巴大概有5%的人是能够上网的，朝鲜就更少，只有0.03%的人能上网。也就是说呢，一万个人里面只有3个人用过互联网。我觉得在这0.03%的人里面，肯定有一个是金正恩。在朝鲜，朝鲜使用的是自己的互联网，名字叫光明网。这个网它自成一体，里面有自己的搜索引擎、电子邮件系统，也有自己的网站。还有一个使用Firefox修改而来的浏览器，只有核心机构的人员才能够使用这个网络，并且有严格的权限控制。比如说你是什么官，就可以用这个网络干什么事。比如说有些权限呢，你只能够收发电子邮件，比如说你只是个科长，你就可以收发电子邮件；比如说你这个市长呢，你就可以用这个浏览器。要是我在朝鲜呢，估计就是蹲在路边吃西瓜，连电脑都不能碰。

普通老百姓只能爱国，所以还是非常感谢老天爷没有在我投胎的时候把我投到地狱模式里，我才能在这里下班后写文章来吹牛。如果有人认为朝鲜非常的落后，只能说还是太拿它当回事儿了，落后也要分地方，有落后的地方也有先进的地方。朝鲜使用的是有自主知识产权的操作系统，是一个Linux的发行版，而且是限量发行版的操作系统，名字叫红星操作系统。我说的这里的红星是红色的红、五星红旗的星，不是古惑仔那个红星陈浩南和三星的那个红星，那是黑社会，三胖家肯定不是黑社会，他们比黑社会可厉害多了。

现在说说这个操作系统，这个操作系统不是一般的操作系统，而是非常特别的操作系统。这个操作系统堪称监控之神。如果你想在这台电脑上传输文件，这个操作系统就会自动地去读这个硬盘的序列号，然后将那个序列号加密以后，再偷偷地加载到你的图片或者视频上，作为记录。因此你这个文件经过了哪台电脑，就完全都被记录住了。如果你往电脑里插个U盘，电脑也会自动记录什么时间插入了U盘，然后做了哪些操作，是拷贝的哪个文件，都有记录。

另外，这个系统还经过特别的优化，它要保证这个核心的监控软件不被破坏，而且专门有一个软件是保证他所有的监控功能都要正常的运行。如果发现有人试图修改这个操作系统，就是这个系统感觉到你要想停掉它那些监控的东西，这个系统会通过网络自动报告给警察叔叔，估计这个倒霉蛋就享年到明天了，从家里直接奔赴刑场，直接给枪毙了，或者炮决或者犬决。

另外呢，朝鲜也有自己的社交网站，但不是Facebook，他们也不能上Facebook。所以我们也不用觉得我们自己不能上，他们也不能上Facebook。他们呢，自己开发了一个独特的社交软件、社交网站，用户可以在上面发布自己的生日，这就是这个社交网站唯一的功能，你可以有一个页面发布你是哪一天出生的，其他的没了。

朝鲜还有自己的官方网站，我找到了其中的一个，也应该是最出名的一个，翻译成中文叫做“我的中国网址”，我就写在这里。而且它的语言版本非常的多，包括中文、英文、日文、韩文等九种语言，还有西班牙文，非常的国际化。九种语言你可以一下子点个汉语，就可以看了。这个网站的第一条新闻肯定是金正恩的，今天首页上的第一条就是她穿了一个白色的短袖到一个叫大同江果木综合农场的地方去考察，其他人都在后面穿着军装、戴着帽子，还穿着长袖，看起来衣服还挺厚，也不嫌热。他们这个金正恩就穿着短袖，其他人都穿着很厚的长袖，估计我是内心比较冷，所以也不觉得热。我把这个照片还截了一个图放在这里，大家可以看看。

在这篇新闻的最后就写到，这篇文章如果放在小学作文中，肯定可以拿满分，或者是放在高考作文中，非常的好。我读了之后都很感动，我把最后的一段复制下来了，最后一段这样写的：“金正恩查看着果园，说每个枝头挂满苹果，简直树叶一半、苹果一半。在不利的气象气候条件下，也能获得往年罕见的果实大丰收，是国家兴旺的好兆头。大同江果木综合农场之所以成立以后首次获得果实大丰收，是因为农场干部和劳动者铭记党要为人民充分供应水果的意图，高度发扬誓死贯彻的精神。”就这样，这是最后一段。

然后，这个网站的第二条新闻的标题是斥责美国、南朝鲜（南朝鲜就是韩国），内容是不容庸俗。此次联合军演也以侵害和扼杀朝鲜的尊严、主权和人民的生存权利为目标，是穷凶极恶的亲朝核战争挑衅，挑衅妄动。这是他翻译的，不是我翻译的，上面就直接有这个中文版。就是第一条说这个金正恩非常忙，第二条就是说你这个美国非常坏。

另外呢，这个网站还有个神奇的地方，就是只要出现了金正恩、金正日，还有金日成的名字，这个字号就自动加大一号，而且还加粗，应该是做了一个CSS的样式表，专门给这几个人的名字加黑加粗加大推荐。闲人可以到他的网站上去感受一下这个金家王朝的光芒、太阳的光芒。网址我写在上面了，大家可以复制粘贴一下，很长，还有什么kkp、什么点kp，他们是点kp。

另外呢，这个网站还有一个，我在搜这个新闻网站的时候，竟然还搜到了一个朝鲜的金策工业大学和朝鲜的游戏公司叫Nosocitake，共同开发的一款赛车游戏，名字叫做平壤赛车手。这个网址我也写在这里，就是平壤赛车手，你这样搜一下，如果有兴趣的话可以玩一下。我还玩了一下，应该是个flash游戏。没兴趣的话可以看看这个截图，非常像一九九六年或者一九九五年我们那个时候非常复古风格的一个赛车游戏。我截了个图，可以看看这个游戏非常简单，就是说你用4个方向键来控制，加速会向前加速，向后是减速，左右是转弯，然后空格键是按喇叭，但按喇叭没什么用，因为街上没有车，你可以随便按这个车。

这个赛车最可怕的地方也是最好玩的地方，就是经常没油，100公里耗油100升，就是一公里一升。你在玩游戏的时候呢，要不停地收集路上的那个油桶，否则你这个油桶不够了，这个车就没了，就是game over，就结束了。因此呢，这个游戏是在平整的街头，整个游戏过程就是一条六车道的路，只有一辆车在六车道上跑。你看在这个路上非常空旷，只有一辆车。路的尽头，你能远远地看到就是那个伟大的柳京饭店，那个没钱盖的105层的饭店。你开车驶过这个柳京饭店的时候，就会出现一个柳京卡片，就是卡片上用英文写的柳京饭店105层、5个旋转饭店，是个成就卡片。

因为我平常是玩侠盗猎车的时候嘛，大家应该知道我最喜欢就是开着车到处撞。因为这本来就是犯罪游戏，你可以撞路人、撞路灯、撞房子，这都很好玩，有罪恶感。所以当我玩这款游戏的时候，在经过金正日广场的时候，我就开足了马力，准备朝着这个人民大学堂撞过去。结果呢，车子你一想撞的状态，它神奇地就移到了路的中间。真正地让我体会到了什么叫做力量，就有点对不起人民、对不起朝鲜劳动党，真是对力量一无所知，你根本撞不过去，你只要一撞，它就回到路中央，真是这样。

最后呢，作为一个喜欢钻牛角尖的人，我还找到了前面我说的这个红星操作系统3.0，我就怀着无比激动的心情，在虚拟机里装了一把，玩了一分钟，我就决定这个系统将是我主力的操作系统之一。我觉得这个苹果公司的mac系统肯定是抄袭了红星操作系统3.0，我真的很支持朝鲜去告苹果侵权。

这个红星操作系统3.0呢，我已经把它放在了百度网盘里。如果有真的有那种显然的爱好者，可以自行下载，十几分钟就能够装好，怀着无比崇敬的心去安装一下、去使用一下，然后去膜拜一下。跟以前的那个苹果操作系统真是一样，之后可以感受劳动党的温暖。链接我就写在下面百度网盘里，这个红星操作系统3.0。

好，这期就到这里。
