---
title: "互联网是谁发明？"
editor: visual
---

互联网是谁发明的？当你在网上看美剧的时候，或者当你通过微信聊天的时候，或者当你在电脑上搜索图片的时候，甚至当你访问链接返回404的时候，你有没有想到过，这一切都是互联网的功劳。那么，谁发明了互联网呢？

我们知道，福特发明了第一个实用的电池，贝尔发明了第一个电话，爱迪生则发明了第一个可以大规模生产的灯泡。但是，谁发明了互联网呢？这个问题难以回答，因为互联网太大了也太抽象了。互联网不是看得见的灯泡，也不是摸得着的电池。互联网好像不存在，又好像无所不在，它已经占据了我们的手机，占据了客厅，占据了我们的电脑。我们知道它是存在的，但是却又难以理解它的本质。

它是某个天才突发奇想的杰作吗？不是的。互联网的发明是千千万万工程师的努力成果。虽然有很多的机构和学校参与，但是没有任何机构和学校能够独自承担如此庞大的工程。如果追本溯源，一个比较公认的说法是，种下第一颗互联网种子的是美国高级研究计划署ARPA（应为ARPA，但通常被称为ARPANET的阿帕网的诞生与之相关，此处可能原文有误，但为保持上下文连贯，不做更改）。该组织发布了第一个互联网的鼻祖，名字叫做ARPANET，中文的名字应该叫阿帕网。阿帕网在1969年正式投入运行，在1990年正式退役（原文中的“一九九九”应为笔误，实际应为1990年左右）。在这二十一年里，在阿帕网上，很多的研究机构、大学纷纷做出了很多重要的贡献。无数的人在上面添加自己的一砖一瓦，最后孕育出了我们现在使用的互联网。

我个人的一贯癖好，就是喜欢在犄角旮旯的地方深入研究。举个例子，我当年上中学的时候，上地理课地理老师就说地球核心的温度和太阳表面的温度相当。当时我就举手问老师：“你咋知道的？”然后搞得老师挺下不来台。后来我还有很多的问题，至今仍然有疑惑。比如说，海水是越来越咸还是越来越淡？比如说，飞机如果飞美国的话，为什么要飞呢？为什么不一下子像个窜天猴一样窜到天上，然后等着地球自转，等到美国转到脚下的时候，再掉下来就到美国了？这些问题我都问过老师，后来老师就不爱理我了。我现在已经35岁了，我经常拿这些问题和我的孩子共同讨论，至今也没有讨论出答案来。

在这个公众号里呢，我就再钻个牛角尖，研究一下阿帕网。我在大学里曾经看过一本书，因为当时有点想学英语，就读了一本英文的书，它的名字可能是记错了，但内容是关于一帮已经无法知道确切姓名的人和一些机构，凭借一颗好奇心在阿帕网上如何折腾出现在互联网的故事。当年看到我有点热血澎湃。这本书有一个观点是，互联网是一种偶然，我稍微有点不同意。我觉得互联网是一种必然，人类的天性是热爱自由和希望与人沟通，这种天性导致了互联网的诞生，必须要有这样一个东西来满足人类这种最基本的需求，互联网就应运而生了。

美国高级研究计划署是属于美国国防部下属的一个机构，它的主要任务是研究一些黑科技，用于保护美国的军事力量，遥遥领先于其他国家。这个机构很厉害，不止搞出了今天我们讲的阿帕网，它还搞出了无人飞机、分布式卫星，还有电磁炮。如果大家看过《变形金刚》的话，那个把金字塔上的机器人胳膊一下打断的炮，就是电磁炮。现在已经据说已经可以使用了。

二战以后，美国就是事实上的全球警察。他当时在全球80多个国家和地区有800多个军事基地，军舰、航母、飞机、坦克这些都不计其数。因为当时世界处于冷战的状态，美国要对抗来自红色政权苏联的威胁。但是在1960年代，这么多军事基地之间，不能够实现全方位的指挥，只能靠电话这种东西去指挥，显得比较落后。在指挥的时候也没有办法掌控全局。比如说，美国本土是有大型的计算机，可以计算导弹的轨道。但是在其他的军事基地里没有，比如说在日本的军事基地里就没有大型的计算机来计算导弹的轨道。这个时候因为还没有网络，因此那个计算资源就没法使用，除非在每个军事基地里都分别修一个计算中心。

因此，当时美国高级研究计划署就脑洞大开。如果在这里再多说一句，如果有兴趣的话，大家可以找一些资料看看介绍这个美国高级研究计划署的地方，很神奇。很多的项目都以现在的眼光来看，都是脑洞大开。看了以后保证大家觉得自己的脑洞不够大。嗯，当时美国高级研究计划署决定开发一种系统，就是说无论什么设备，无论在地球的哪个地方，无论是坦克、轮船还是航母、装甲车，都可以使用这个系统。因为当时它在全球七八十个国家有军事基地，所以要把这些东西连起来。所以当时要实现这个目标，因此这就是阿帕网最终要实现的目标。

等到这个项目立项以后，美国反正有钱，一贯也财大气粗，提供了大量的资金来支持阿帕网相关的领域。不仅仅是支持阿帕网，因为当时也不知道能不能弄出这个东西出来。所以呢，当时高级研究计划署就大量投资，比如在计算机、图形学、超级计算机方面都进行了大量的投资。而且为了避免外行领导内行，高级研究计划总署还从各个大学里挖最顶尖的科学家来当领导，当时就挖了当时包括最著名的MIT人工智能专家约瑟夫·利克莱德（此处原文可能有误，但为保持上下文连贯，不做更改）。这个人就当老大，钱随便花，相当于是无限量供应。传闻说这个传闻应该是真的，这个约瑟夫·利克莱德当老大的时候，80%多与计算机相关的公司都是他出钱。而且你只要是研究计算机，不管是民用还是军用，先造出来看看。反正军队上是不要专利权的，造出来算你的，赔了算我的。当时呢，这个人在美国宽松的体制下，一下子就把计算机相关的行业炒起来了。

后来的几任老大，个个也都是顶级的科学家，包括鲍勃·泰勒、拉里·罗伯茨等等，这些都是在科学界都是顶尖高手。后来呢，拉里·罗伯茨被称为阿帕网之父，因为罗伯茨首先想到的这个论法，并且画出来大量的图来论证，连架构什么都想好了。万事俱备，只欠美元的时候，他就去找他的领导。当时就是泰勒，泰勒就说：“你这个随便花嘛，造出来试试看。”结果就真的造出来了。造出来以后发现能够完成一些需求，于是呢，就在1969年开始投入运行。

因为高级研究计划总署一直是奉行“随行随上”的原则，内行领导内行，外行负责给钱。因此，源源不断的一流的科学家和工程师就开始进入阿帕网的项目。按照美国人一贯的性格，这些顶级科学家和优秀的工程师进入阿帕网以后，马上就着手对阿帕网进行改造，反正看到自己不爽的东西就改改。

刚开始的时候，阿帕网只有4个节点。第一个节点选在加州大学洛杉矶分校，因为当时罗伯茨的朋友叫科克莱金·罗克教授在加州大学。因为当时他也在研究计算机网络，而且也是当时最顶尖的科学家之一。这个教授后来也被称为互联网之父。多说一句，就是其后如果大家看书或者是看网上新闻的话，就会不停的看到“互联网之父”这个词。其实好多人都被称为互联网之父，因为互联网确实是这些人做出来的。因为互联网是由非常多有追求、有道德的科学家发明的，每个互联网之父都值得我们尊重。所以我们不能说：“哎，怎么他也是互联网之父？这么多父亲呢？”不是的，确实有非常多的科学家都可以称为互联网之父。

第二个节点选在斯坦福大学，当时选第二个节点考虑的因素还是人，就是道格拉斯·恩格巴特教授。他当时在斯坦福，大家也许不知道这个名字，但是大家一定用过他发明的一个东西，就是鼠标。鼠标就是他发明的。其实从某种意义上来说，他也发明了互联网。不过大家呢，一般不说它是互联网之父，而是说它是鼠标之父。因为鼠标太出名了，如果他没有造出鼠标这么出名的东西，他也被称为互联网之父。其实他也参与发明了很多东西，包括超文本链接、网格、计算机。在硬盘方面，他也做出了很突出的贡献。这些东西他都做出了非常多贡献。

第三个和第四个节点分别选择加州大学圣巴巴拉分校和盐湖城的犹他州立大学。考虑的方面也是人才，就是哪里有顶尖的科学家就把节点放在哪里。这两个学校呢，在计算机图形学方面领先于其他学校。而且犹他大学还有伊凡·苏德兰教授，这个教授呢，被称为虚拟现实之父。比如说现在的虚拟现实是非常的热，算起来呢，应该跑到他那里去认个祖宗。他也是由于计算机图形学和虚拟现实获得了一九八八年的图灵奖。

这四个节点就是阿帕网的种子。这个种子一旦埋进了土地，很快就生根发芽。隔了一年，很快就扩展了15个节点。等到1973年的时候，也就是阿帕网上线之后的第四年，就已经连到了英国和挪威，是通过卫星来连接的。当时使用的协议并不是现在使用的TCP/IP协议，而是使用现在已经已经被淘汰的协议。但是我也不懂，因为它已经被淘汰了。我知道它的名字叫做NCP协议，在一九八二年就被停用了。NCP协议停用以后，就全部都由TCP/IP协议来实现。

因为当年的计算机设备五花八门，而且每个计算机都使用自己的语言。如果想让这些不同的计算机互联是非常困难的。这个时候呢，又出现了两位科学家，分别是鲍勃·卡恩和文特·瑟夫，他们一起发明了TCP/IP协议，就是为了让各种设备通过这个协议能够互联。这两位呢，也被分别都称为互联网之父，他们也确实配得上互联网之父这个名声。

如果再钻一下牛角尖的话，我们就会发现，其实是鲍勃·卡恩和文特·瑟夫他们两个合作发明了IP协议。然后在这个基础上呢，鲍勃·卡恩他又自己发明了TCP协议。不过这并不重要，他们都很伟大。我并不是说他们谁厉害，因为我就喜欢研究这种东西。嗯，这两位呢，最后也获得了图灵奖，而且还获得了很多种奖，包括克林顿总统都发给他奖。包括他还获得了美国普通公民能获得的最高奖章，就是在布什总统向他们颁发了总统自由勋章。

最后，又是一个非常聪明的人，叫伯纳斯·李博士，他也被称为互联网之父，因为他发明了万维网。因为阿帕网接近完成其历史使命的时候，差不多就要退役了。但是基于阿帕网，无数优秀的科学家已经共同孕育出了互联网，它马上就要诞生了。伯纳斯·李博士算是迎接互联网诞生的第一个人，他开发了世界上第一个网页浏览器，互联网也就算是从此诞生，从此开始了一段波澜壮阔的旅程。那是因为他提出了HTTP协议，还有这个浏览器，所以他也算是互联网之父。

好了，这一次讲了非常多的科学家，可能名字都很难记。我那也是查书的时候才去看的，因为我只记得住故事，也记不住这么多名字。比如说，只能记住一些比较好记的，比如卡恩，因为他同时也是拜仁慕尼黑以前的门将，也是德国队的门将，所以我一下就能记住卡恩，像其他的像道格拉斯也能记住，其他的都记不住。

讲这么多科学家的意思是说呢，互联网并不是一个人发明的，而是非常多的人合作，共同孕育出了互联网。因此，大家只需要记住一件事情就好了，互联网之父非常多，能够配得上这个称号的人也非常多。如果大家以后看到好多人都称为互联网之父，也不要惊讶，也不用和别人争吵，大概这都是对的。

呃，再来讲一件题外话，就由此想到互联网是美观的。因为我在微信上会有100多个人嘛，总是有一些热心的听众就会留言问我，哎，这个网站后台应该怎么做，编程怎么选？其实呢，我真不敢提意见，因为我是个35岁的老程序员了，至今也没有做出什么让人震惊的软件。我可以稍微透露一下，我背景确实不合适。我不是不告诉大家这个后台怎么做呀，前端怎么做，后端怎么做，因为我的能力确实达不到指导大家做网站后台的程度。因为我主要的工作经历就是给路由器写软件，而且是给那种运营商使用的，普通大众根本没机会用。它其实就是一个冰箱那么大的路由器，就一个机柜。这也算是我为互联网做的一点贡献。我就是专门写一些互联网协议的实现，比如说MPLS的实现、BGP协议的实现。但是我确实没有能力制定这些协议，能制定互联网协议的人肯定也没空来这里给大家吹牛讲故事。我的工作主要就是读那些RFC，然后根据RFC的规则实现这些协议，让路由器支持这些协议，像BGP、OSPF等各种协议，MPLS我都会写。

所以我大部分时间其实是写的是C语言，少部分时间写写Python、Java以及手机软件，非常少的部分，可能只有30%，70%的时间都是写C。因为我个人非常喜欢编程和编程有关的东西，但是我确实不能给大家提具体的意见，所以以后也希望大家不要问我这种问题，我确实也无能为力。

另外，多说几句这个职业规划呀，问我也确实没用，我也不敢给大家提什么意见。因为这个关系非常重大，而且大家都是成年人了。我认为超过16岁就不应该在重大的事情上再参考别人的意见，连父母有时候都不应该参考。我说的重大事件就是大家要自己衡量，比如说职业规划呀、结婚呀，我认为这些都算是重大的事情。如果你向别人询问的时候，被询问的人如果做不到一些事情，他们就会语重心长的告诉你，这玩意不能做，其实也不见得就是他做不到。比如说你问我用哪个语言实现后台能不能做？如果我冒昧的告诉你不能做，那并不是真的不能做，是我做不到。比如说莱特兄弟造飞机，要是他哥俩到处问，能不能飞呀？百分之百的人告诉你，这玩意儿肯定不能飞。所以呢，别让人家告诉你行或者不行，你自己试试看。更别说让我这么一个35岁了，还没写出好软件的老程序员来告诉你哪个软件能写不能写。

因为另外我也不算什么大牛，连小牛都算不上，顶多算头猪吧。可能如果你有梦想的话，你就去做。在中国这个社会，你光做还不行，你还得捍卫自己的梦想，就像是捍卫你的亲人、你的家庭一样去捍卫你的梦想。因为咱们中国人比较喜欢冷嘲热讽，你的梦想就像你自己的房子，你的家人冷嘲热讽呢就像是城管，你如果不去捍卫你的梦想，你就会被城管拆了，你的房子就会被这些冷嘲热讽给击溃击垮了。也别让那些一事无成的老家伙坐在那里告诉你一些什么狗屁道理。如果你有理想就去实现它，就这样。

如果你想看大牛，我建议大家翻个墙去推特上注册个账户，上面大牛真的很多。比如说卡马克呀、罗梅罗呀，还有很多，包括各种语言的创始人，都在推特上面。或者就在Quora上面直接问问题，比如说维基百科的创始人，还有BT的创始人都在上面，而且非常热心。而且我看了他们那么多的回答，他们好像从来没有骂过人，都是热心地回答问题，还有什么Minecraft的各种游戏的创始人，那个Note的创始人都在上面热心地回答问题。我还问过几个问题，他们都回答了，上面真的有很多大牛。

如果说脾气的话，确实算大牛脾气都很牛，很多都张口就骂人，而且像得了疯牛病似的。算了，不说这种事情了，回来继续讲故事。

互联网就是这样，有无数的人投入其中，有些人做的贡献大一些，有的人做的贡献小一些。有些科学家发明了基础的协议，有些工程师则制作了基础的芯片。比如说他就做了一个小芯片，或者在网卡上加了一个小灯泡，或者就是改变了网线，给网线上涂上颜色。还有些文员记录了会议记录，有些企业提供了场地和资金。有些官员本身不懂技术，但是他招募了大量的科学家，还有一些酒吧提供了大量的啤酒和聊天的环境。真的是有这样一个酒吧，这个酒吧的名字叫Rosty，据说是硅谷的一个酒吧。据说阿帕网第一次实验的时候，就是在这个酒吧前的空地上进行了实验，成功以后就马上去喝啤酒庆祝。哎，我没有去过硅谷，也不知道真假，这个酒吧门口是有一个牌子写着来纪念这件事情。我收到了图片，我认为应该是真的，就是这样。

无数的人就做了或大或小的贡献，就诞生了互联网，这些人都值得敬佩，也值得尊重。所以我就把这个故事写出来，希望大家能够知道好多做出贡献的人，我们可能永远都找不到他们了，他们的贡献就被历史长河所埋没了。但是呢，正是这千千万万知名的或者不知名的人，让人类的社会就变得非常的美好。

阳光的背面总是有阴影，也有一些科学家或者工程师，在一些地方每天就绞尽脑汁研发的东西，就是想着如何把连接了你我他的互联网再和世界断开。是的，就有一些地方的科学家就干这种事情。

好了，这期节目就到这里。

这期节目是第22期，进入汇报数据的时间。嗯，微信公众号的关注者现在是187个人，平均每篇的阅读量还是50个人，转发数仍然是零到一次。网易云音乐的关注者是475人，B站编程视频的关注人数是67人。好了，这期就到这里，非常感谢大家的收听哦。对了，还有非常感谢上一期给我打赏的那7个人，又让我赚了16块钱，谢谢你们。
