---
title: "自由软件自由谈，自由才是引爆点"
editor: visual
---

。

上次讲到，相比于石器时代的人，希伯来教给予了人类更大的自由。所以，希伯来教也就有了大批的信徒。一方面，生命有了保障；另一方面，说不定还真的能去天堂享受。但是，希伯来教会有个问题，就是这个摩西老先生没有解决好一个问题。摩西光说：“你只要信我这个教，不信其他人的教就可以；如果你信了其他人的教，就通通下地狱。”但是，这个教还是会有个漏洞。

希伯来教说，等到大家都让上帝感觉到满意了，上帝就会派个大天使来接大家一起去天堂，而且是活着去天堂，不是死了去天堂。就靠这个，希伯来教在教徒里竟然信了1000多年，甚至2000来年。大家肯定会想，时间久了，怎么左等大天使就是不来呢？希伯来教对此有解释，说主要还是你们的心不诚，肯定还是有其他的信徒信得不够彻底。其实你想糊弄上帝，心诚则灵，心不诚则不灵。你们肯定要先自己反思，然后再来和我讨论为什么上帝没有派大天使来。这个理由看起来非常的牵强，但是也确实让信徒没话说，毕竟那么多人，总有个把信徒可能素质不行，不适合活着上天堂。

结果搞来搞去，唯一的方法就是信徒要更加虔诚地信教，希望能感动上帝，然后派个大天使来，大家一起接着去天堂。就这个玩法，就搞了2000多年，想想也挺厉害的。

然后呢，耶稣就出来了。耶稣这个人一下子就引爆了基督教。他20来岁的时候，就对他几个哥们儿说：“兄弟，你知道吗？我就是上帝。”我都能想象的到，当时这帮哥们儿肯定是震惊的表情。本来就是嘛，耶稣你别逗我好不好？咱们已经玩了20来年，一起长大，谁不知道谁，结果你突然告诉我你就是上帝。但是耶稣面不改色地说：“是的，我就是上帝；而且呢，我不但是上帝，我还是上帝派下来接大家去天堂的使者。”这大家肯定就更惊讶了。

但是，肯定会有人相信。我们今天想想啊，信息这么发达了，连QQ群里转发多少次抵制日本车，马化腾就送你Q币这种弱智的玩意儿都有人信。所以，当时就真的就有人相信他，就是上帝以及上帝派下来接大家的那个天使合二为一，或者是三位一体——反正可以自行去搜索一下基督教一个叫“三位一体”是什么意思。

反正他总共忽悠住了13个人。呃，就是达芬奇有个名画嘛，叫《最后的晚餐》，就是那13个人。其实想忽悠人，你得有点奇特的地方。耶稣奇特的地方就是他是个私生子，没有人知道他父亲是谁。但他让大家都知道的名字叫玛利亚，就是这个玛利亚，英文名就是Mary。

我年轻的时候，就是90年代的时候嘛，就有一首流行的歌叫《我悄悄地蒙上你的眼睛》，歌词里就有一个“从什么到Mary到什么什么的”，就是这个玛利亚的意思。但是咱们都会说玛丽，这个圣经里比较厉害的是，我们很多的词翻译得不同。其实是玛丽，但是这个就是玛利亚。这个玛利亚呢，她没有结婚，然后呢，她经过一个地方的时候就怀孕了，就是上帝嘛，神在她的肚子里就种了一个种子，生出来就是耶稣。可能大家觉得有点乱，但我个人感觉也有点乱。

这个有个解释呢，就是基督教中有个解释叫三位一体，就是你这个圣父、圣子和圣灵就是三位一体，这3个应该是一个人。但是你说往深了讲我也不懂上帝出生这件事情，毕竟他是神嘛，你也不可能用常理来解释。通俗来讲，我认为就是说上帝往他妈妈的肚子里种了一个种子，然后呢生出了耶稣。这是一个循环，这个解释有可能是错的。

但是对的解释，我曾经上学的时候，曾经跟一个基督教的朋友深入地讨论过这个问题。但他解释了半天，我也没搞清楚为什么是这样。他当时不小心说漏了嘴，就说这个玛利亚是不是偷情了。不可能在2000年前，你经过一个野地就怀孕了是吧？肯定有问题。但是我这个话还没说完，这位基督教的朋友就勃然大怒。从此呢，友情就尽了。申诉了很多，不管怎么说了，反正耶稣外加这13个门徒就引爆了整个基督教。

希伯来教当时就说，哎，大家怎么就等着上帝来接咱们活着去天堂？只要大家好好地信，大天使一来，怎么就全都去了？结果等了2000年，耶稣就进来说：“哎，大家别等了，我就是上帝，我说来吧，跟我去天堂，来一场说走就走的旅行。”你如果说按照《孙子兵法》的话来说，这一招就叫釜底抽薪。

人家希伯来教花了2000年造出来了上帝这么大一个IP，搞得教徒都信以为真了。结果耶稣倒好，上来就说：“我就是你们说的那个上帝，我是来接大家的。”这明显就是断人财路，希伯来教马上就翻脸了。于是希伯来教就要抓耶稣，耶稣也是东躲西藏。他肯定知道这是断人财路的一个非常恶的方式嘛。

然后，这个希伯来教就买通了这13个门徒中一个意志不太坚定的，叫犹大，塞了一些钱。结果呢，这个同学就把耶稣的位置出卖了。吃饭的时候，就是最后的晚餐嘛，当时罗马帝国就派人把这个耶稣抓走了。

如果现在来看呢，耶稣的影响力还是非常小的，就是12个半人嘛——起码犹大只影响了一半，否则的话他也不会去出卖，影响力还是非常小。但这个罪可不是小罪，因为这涉及到砸人饭碗，而且涉及到意识形态，这个都是大罪，在任何时候都是大罪。

罗马帝国当然无所谓嘛，但是罗马帝国怕的是希伯来教的长老。因此，在这些长老的压力下，罗马帝国就直接以可能是煽动颠覆国家安全罪类似的罪名，就把耶稣给钉死了。就是我们知道，耶稣不经常在十字架上那样挂着嘛，就被钉死了。其实是罗马帝国把他钉死的。

再后来的事情，咱们就不说了。有的说耶稣就复活了，坟墓空了；有的就说耶稣实际上逃跑了；还有的更离奇的传闻，就是这个耶稣能跑到印度去，然后又化身为释迦牟尼，然后又创立了一个佛教。还有人说这个老子骑青牛，然后又怎么样，又整个佛教——反正佛教比较倒霉，经常是人家给创的。不管怎么说，这个不重要，我也就不谈了。

再多谈一点点的事情，就是出卖耶稣的这个家伙叫犹大，是个犹太人。耶稣呢，其实死在罗马帝国之手，但是给予压力的是希伯来教的长老。所以呢，实际上是死在希伯来教长老之手。如果是罗马的话，懒得理你，毕竟只影响了十几个人，根本不管你。所以呢，后来基督教一直也就非常仇恨这个希伯来教，希伯来教又是犹太人的精神支柱。所以呢，一直持续了2000年，这个希伯来人就到处流离失所。

而且二战的时候，希特勒把大批的犹太人都杀了，总共杀了600多万。其实最终啊，是有民间基础的。其实最终你可以追溯到，其实大家都比较讨厌整个基督教，实际上是比较讨厌犹太人。大家要相信，如果没有仇恨基础的话，希特勒你再厉害也很难说，你抓过来就杀了。实际上是有这个基础的。

所以，圣经就是这么一个相对来说对我们外人来说是比较诡异的东西。旧约是讲希伯来教，新约是讲基督教。这个基督教和希伯来教之间就打打杀杀了很多年。最后呢，去的是一个天堂。当然了，希伯来教至今也没有去天堂，因为他说的是活着去天堂嘛，大天使还没有来；基督教呢，应该是去了很多了。你只要信仰他，去世之后就可以去天堂。所以现在天堂上都是基督教的人，还没有希伯来教的人。因为希伯来教说，我得活着嘛，不管以后怎么样，万一真的有大天使降临，希伯来教就都去了。

他们实际上是去的一个天堂，但是这么多年的仇恨也不知道他们去了天堂之后还会不会继续干架。为什么说基督教就引爆了呢？我们来谈一下这个问题。就是说，基督教实际上是比希伯来教要自由。对个人来说，更自由一点。

我们以后会联系一下，就是用自由这把锤子继续说说自由软件啊、私有软件之间的关系。反正，这把锤子到处找钉子嘛，所以也不用认为我谈得多么准确，随便谈谈。我其实最主要的是树立我自己的思想，自己忽悠自己。

但实际上，人类的历史，如果你这样仔细看的话，鲁迅说是一部吃人的历史，“吃人”两个字嘛。但是我觉得从另一个方面来说，很大一部分是人追求自由的历史，尤其是西方。其实别说国家情怀这种东西能够阻止人追求自由，实际上你连上帝都挡不住人类热爱自由的心。

你看看希伯来教的上帝，根本就挡不住基督教的上帝——人家可能是一个人。然后希伯来教就当时忽悠大家，就是这个意思嘛，大家稍安勿躁，上帝马上就到，然后忽悠了2000年。然后耶稣就直接出来说：“哎呀，啥稍安勿躁，肯定不用了，上帝已经来了。”

希伯来教呢，就是所有人都得好好的，才能让上帝开心。然后呢，上帝开心了，就会派个大天使过来把我们接走。如果你有一个人是不好的，哎，这个不行，上帝还是不高兴，就是不行，你这个还得继续等，继续信。

基督教说呢，你根本不用所有人都好，你自己好就行。就是呢，你这一辈子好好地来服侍我，就服侍耶稣这个人嘛，服侍这个。然后死了以后，你就可以去天堂，别人多尔多端也好，跟你是没有关系的。你是一个个体嘛，你只要伺候我，你不用管其他人，我就能让你去天堂。

其实这就是引爆点嘛，他就是把整个的群体给打散了。用现在时髦一点的话说，就是扁平化或者去中心化。用中国的古话来说，就是“各人自扫门前雪，莫管他人瓦上霜”。你不用管其他人，你想想这个希伯来教已经2000多年了，很多人就是日思夜想的大天使，根本没来，天堂可能都一直空着，都快长草了。你还不如改行，就信一下其他的基督教得了。起码那基督教是不用担心的，你自己去不了天堂。你只要伺候好这个耶稣，死了以后就能去天堂，这肯定的，百分百确定的结果。

虽然说希伯来教说能活着去天堂，但是毕竟2000年了嘛，你这个日子也会越来越难熬。哎，头发都已经熬白了，你这个活着去的可能性也越来越小。所以呢，还不如死了再去。所以呢，就靠这个相对来说自由一些，并且淳朴一些的思想，也就一下子引爆了基督教所。因此大批的信徒也就接二连三地信仰基督了。

刚开始的时候，信仰的肯定是越底层的民众。因为你这个民众越底层的，就越想上天堂。因为自己的生活很困苦啊，很苦，天天很累，你吃不饱。当然希望上天堂之后，生活能好一些。但如果你去忽悠富人呢，他就相对来说不容易相信天堂。比如说大家有听众可以认识那种大官，比如说认识县长或者市长。你就问他，你想不想上天堂？我想他应该九成就会告诉你，哎，不用上天堂，我现在就是天堂，因为他生活好嘛，他可以为所欲为。基本上生活当然很好，但你穷人的话就不一样。

但是我一个大官都不认识，我认识连科长都不认识，所以我也是瞎猜的。我还认真研究过各种宗教、各种神话里的天堂。说实在的，天堂如果真的存在这么一个地方，其实挺无聊的。就有些这种宗教就把天堂描绘成一个像自助餐厅一样，你不要钱，按需分配。你想喝牛奶就有牛奶，想吃肉就有肉，而且不限量供应，就不停地吃，可能还不长胖。但有的宗教呢，哎，在这个基础之上，在自助餐厅的基础之上又加了一些美女服务员。哎呀，还很多美女服务员是吧？你只要玩得高兴，随意玩，就说更好一些了，比那个自助餐厅更好，就是带美女的自助餐厅。还有一些神话呢，又在这个带美女的自助餐厅基础上又加了一些更多的娱乐。比如说希腊神话里的那种天堂，你不但有美食，还有美女，而且还可以打仗，在上面有嗯随便玩玩，打个仗什么的娱乐活动。

那基督教呢，最后因为这个解放了个人上天堂这个难题。那最后你又到了什么地步？就是说最初就是有创始人耶稣以及这13个门徒，他们主要是战略思想弄得好，战术方面也应该是还行，但显然没有战略好。否则的话，你战术很好的话，你也不可能是一开始打仗，这个创始人耶稣就出师未捷身先死。有人说他没死，不管死没死，起码他再也没有出现过。只是传闻中他不停的出现，出在这里出在那里，或者出在印度建立了佛教，那都是传闻嘛，但实际上它并没有再出现。

所以呢，我还是认为你这个创业就跟基督一样，还是先定好战略。你只要战略好，其实不需要很强的执行力。你这个战略不好的话，执行力再强也不行，最后还是不行。就厉害到什么程度呢？就在公元391年的时候，基督教呢，就是由一个私生子创造的宗教，就一下子就成了罗马帝国的国教。当时罗马帝国非常厉害，就有穷人，慢慢的连皇帝都相信了，也就成了罗马帝国的国教。

类似于中国的孔子啊，孔子也是个私生子，他创造的是什么？就儒家文化。不是儒家那个酒店，是儒家还是儒啊。所以呢，他在汉朝也就成了中国的国教。他把其他的很多教都废了，独尊儒术嘛。但基督教呢，一旦成了国教以后，你就非常好办了。因为当时这个罗马帝国又强大，而现在用时髦的话来说，就是病毒式传播。不但是引爆点，而且是核爆炸，引起了核爆。

因此呢，基督教也就瞬间就把其他的竞争对手逗得根本无还手之力。反正呢，基督我们也都知道，该杀的杀，该烧死的就烧死。你只要不习引（应该是“被”的误识别）烧死，我们在历史书上也都听过这事，他们都干过。即使后来罗马帝国后来被北方的蛮族攻陷了，但这丝毫不影响基督教的发展。因为这些蛮族进来之后，就马上又成了基督教的信徒，其实和中国差不多。

你看看虽然朝代更迭了那么多，但是儒家也有起起伏伏啊。像中国啊，我们也都知道，历经了很多的变迁。但最后呢，在大体上还是信儒家。包括今天一说到经典呢，就说孔子的那一套嘛。而且现在还是国学热，会认汉字就能教国学。

从另一个方面，你也可以看出这个宗教的厉害。就是你朝代更迭没事，这个思想一旦是进入合适的土壤啊，这个你想去除这个思想还是不太好搞的。基督教成了国教以后呢，就属于只手遮天了嘛。开始进入我们历史书上所学的那个臭名昭著的中世纪啊，社会也就慢慢的进入一潭死水。只要不是关于圣经的呢，其实其他的研究就是进展不快，或者说毫无进展。

那时候那人研究什么？就是经常研究一个针尖上可以站几个天使，真的是这样。现在说起来是笑话他们，那时候的外国人、西方人也是研究这种很无聊的东西。一个针尖上站几个天使，这种东西可以写论文的。就这种又无聊又没用的知识。

但是你不可否认的是，基督教的成功相比于希伯来教还是有一些进步。他就是更注意个人的自由，就人的自由度。无论是从精神上还是从身体上，精神上就是说你自己信奉上帝，你就可以上天堂。这个精神上也是也有了一些那种很温暖的地方。人基督教，我们如果看电视的话，经常看到啊一群人坐在一起还要去教堂。你这个人比如说你很寂寞的话，这可能能给你带来一些家庭的温暖。

所以呢，虽然基督教有一些不地道的地方，而且很多时候我们能够找他的缺点，确实能找到很多。他包括各种都随便找，但是呢他也有可取之处。就是说你从无论是精神上还是对身体上，很多人就比以前要强了。因为精神上肯定是能够死了去见上帝、能够去天堂。然后呢身体上就是说你始终在互相帮助嘛，有点像传销是吧？但是呢，我们作为一个程序员呢，也就是经常要思考一些教训嘛。

就是说比如说现在大家经常经常说的一句话，就是谁谁谁垄断了市场，这个市场已经没什么创新了，就一潭死水了，就不行了，已经被人垄断了，再有创新也没用了。其实呢我们如果从抓到历史那里看呢，你想想这家公司的垄断有没有基督教那么厉害？有没有希伯来教那么厉害？你想想，即使像希伯来教那么厉害，不也是让基督教给摧毁了嘛。其实后来基督教那么厉害，进入了黑暗的中世纪，不最后也被摧毁了嘛。

其实我们从中还是可以学到很多东西。我觉得摧毁这些密不透风的宗教，最重要最重要的一点就是，无论是后来者是有意识的还是无意识的，你一定要让这些用户或者让这些信徒感觉到更自由了。这个自由是个好东西，他们肯定是越来越追求自由。

中国不是有句话说嘛，就是叫“墙倒众人推，破鼓万人捶”。很多时候你建立起一个东西来是很困难的，包括你建立一个国家、一个宗教，什么都建立起来都非常的困难。但是呢你摧毁一个东西远远没有那么困难，国家呀、宗教尚且如此，何况我们现在只是说哪一个公司在哪一行业呢？所以呢还是要小心。

所以是不行的呢，呃，就是说你现在处于强势地位的，你还是要小心，万一被人“墙倒众人推，破鼓万人捶”，没几年就挂了。无果，比如说诺基亚是吧？如果你是一个挑战者呢，尤其是我们作为这些程序员，还是始终要抱有希望嘛。无论你在哪一个程序员的行业，面对的是哪一家公司，好了，要有希望吧。嗯，如果没有希望的话，就看一看历史，好吧？下一次再讲故事。

然后其实呢，我讲这个故事没多少人听，我主要的还是总结我自己的思路。

好了，这期到这里，再见。
