---
title: "任天堂往事，精灵宝可梦之父田尻智"
editor: visual
---

戏，可惜我偏偏不喜欢。虽然现在我特别希望我很喜欢这个游戏，但看在我写过好几期任天堂的份上，想必大家知道我很喜欢玩任天堂的游戏。的确是的，我喜欢玩马里奥、塞尔达、传奇，甚至马里奥制造系列，这些小游戏都能让我玩起来忘掉时间。但是我总是对精灵宝可梦和任天狗这两个系列的游戏一点都不感冒。所以，即使现在精灵宝可梦如此的火热，我还是没有写一篇关于它的文章。还是金大侠那句话：“那都是很好很好的，可是我偏不喜欢。”

作为一个游戏里的好几个朋友问我：“精灵宝可梦是什么？”我就告诉他，这个游戏最近改名字了，就是以前的口袋妖怪。对方或者恍然大悟，或者若有所思。这个游戏到底好在哪里呢？我也曾陷入过深深的不解。我痴迷于玩马里奥的游戏，那乐趣又是什么呢？

我现在已经35岁了，有时候我会尝试让儿子玩一玩马里奥，可是他偏偏不喜欢，他喜欢玩的游戏是我的世界和废品机械师。直到有一天，我才恍然大悟，其实我们所有人玩的是游戏，享受的却是友谊，怀念的是童年。我玩马里奥的时候，脑子里回想的都是我的童年：从哪个水管钻出来，找到一颗五角星，从哪个砖块能够顶出一条生命……这难道有意思吗？如果只是自己玩的话，本身是没有什么意思的。一个意大利的大胡子大叔，在那里跳来跳去的，能有多大的意思呢？但是，这可以把我找到的那些隐藏的技巧分享给我的小伙伴们，这个游戏就开始变得有意义了。我儿子玩的是我的世界，他可以和他的小伙伴们分享他建造的城市，因此游戏才有了意义。我想，我玩马里奥，我儿子玩的我的世界，其他人玩的精灵宝可梦，都应该是相同的体验吧。

好的游戏只是一个媒介，这些游戏让我们可以互相陪伴、互相喜欢，能够交流彼此的感情。严格来说，精灵宝可梦和马里奥、塞尔达有所不同。马里奥和塞尔达是任天堂独家的游戏，一直以来这两个游戏只会出现在任天堂的机器上。精灵宝可梦则是三家公司共同拥有的游戏品牌，因此精灵宝可梦更可能走出一条与众不同的路。我们也看到了精灵宝可梦登陆了手机，成为所有手机游戏中最成功的之一。那马里奥会登陆手机吗？目前我觉得有点悬，毕竟马里奥是任天堂独家的游戏。

前文已经说过，精灵宝可梦的版权属于三家公司，但是还是会有很多人认为这个也像马里奥一样，是属于任天堂的。其实不是的，精灵宝可梦更多的贡献来源于一家叫做Game Freak的公司。这家公司的一员大将，名字叫田尻智的游戏制作人，对这款游戏的贡献远远大于任天堂公司。但是这个世界总是特别的搞笑，精灵宝可梦上市以后，任天堂的股价飞涨，搞得任天堂都有点不好意思了。前几天任天堂公司出来澄清，说这个精灵宝可梦只是任天堂只持有一小部分的收益。投资者一看，这才搞清楚状况，原来精灵宝可梦不是任天堂做的，又开始抛售任天堂的股票，结果让任天堂的股票在一天之内跌了18%。

再来说这个田尻智，他小时候喜欢去森林里抓虫子，因为家住在郊区，就是好山好水、好无聊的地方，就去收集各种各样的小动物、小昆虫，是远近闻名的“虫子博士”。和他一起玩的小伙伴，估计爱好也差不多，互相交换稀缺的昆虫。而且这个田尻智非常有商业头脑，从小就开始印刷杂志。他17岁就创办了自己的杂志，名字就是日后公司的名字，也叫Game Freak。写到这里，多说一句，很多牛人都是创办杂志发家的。英国维珍集团的老大布兰森也是在17岁创办的杂志，名字叫《学生》，现在他的身价是50到60亿英镑，经常每年赚的比英国的女王还多。所以如果有听众，恰好今年是17岁，赶紧去办一本杂志，要向这两位牛人学习一下。办杂志，不赚钱不重要，重要的是敢想敢干。

本文的主角田尻智通过他的杂志认识了不少朋友，其中包括增田顺一。这个哥们呢，后来专门给精灵宝可梦配音，成了很出名的电子游戏作曲家。如果玩过口袋妖怪里面的配乐，基本上都是他写的。任天堂还有一位名声更大的电子游戏作曲家，他的名字叫近藤浩志。如果有人玩过马里奥兄弟的话，里面滴滴答答的配乐就是他写的。当年的电子游戏对容量的要求非常的高，不可能像现在这样给一首MP3去做背景音乐。当时的音乐要不停地重复播放，而且要求你重复播放的时候，不能让玩家觉得非常的无聊、非常的刺耳或者非常的单调，这就需要非常高的水平。大家有兴趣的话，可以找口袋妖怪或者马里奥兄弟的背景音乐，循环播放100遍，基本不会听到有什么不适。

在一九八九年的时候，任天堂的第一代掌机Game&Watch销量锐减。毕竟那个时候消费者也不傻，谁会去花钱买一个只能玩一个游戏的掌机呢？任天堂就急需要一个新的掌机。经过任天堂的大将横田军平反复的消减成本，甚至当时还得了重病，得了胃溃疡，他才终于研发出一台在硬件上已经落后于时代的机器。当时的掌机别人都是彩色的，还有背光灯。任天堂一贯的做法就是从来不拼机器的硬件，这台机器啥都不好，如果只按硬件的话，它的屏幕是单色的，没有背景灯，只有两点比较好：一是比较省钱；第二是比较省电。别人的机器安上电池，玩3个小时电池就没电了。任天堂呢，还有个外置的电池包，就像现在咱们手机经常用的那个充电宝一样。任天堂为了更省电呢，还给玩家提供了一个高级的特征，可以插上耳机玩。因为插上耳机以后，这个喇叭也就可以关了，一切都为了省电，而且音质还得到了提升，因为以前的喇叭的音质都非常不好。这台机器呢，可以保持7到24小时不间断地玩游戏。结果就依靠这个比较落后的硬件、比较先进的理念，Game Boy竟然赢得了市场。

Game Boy当时还提供了一个特别好的特征，就是两台机器你只要插上连线就可以传输数据。任天堂后来就建立了自己的王者地位，建立王者地位之后开始干什么？当然是开始赚钱了。虽然我非常喜欢任天堂这家公司的游戏，但是任天堂当年当老大的时候，对游戏厂商那可是一个心狠手辣。只说一点，当时所有的游戏卡带都需要任天堂去制作。制作之前呢，先要付款。比如说有的游戏厂商，你想让游戏在圣诞节上市，想制作10万套游戏卡带在圣诞节的时候卖。这时候任天堂就说：“他也不好意思啊，工厂太忙了，10万套卡带是造不出来了，要不先给你1000套怎么样？”这个时候所有的厂商都是敢怒不敢言，但是仇恨的种子和不满的种子也就在心里种下。以至于索尼后来开发Play Station以后，这些仇恨就来了一次总爆发。你就可以看到，原来是任天堂的小弟叛起当年的老大来，那是一个痛快。

当然，这也不能怪别人背叛，谁让当年任天堂当老大的时候心不软一点呢？当然，任天堂也心知肚明，人心散了，这个队伍就不好带了。为了拉拢游戏厂商，任天堂就有一个团队是出钱给第三方，类似于今天这种创新工厂、创业大赛，就是你出创意，我出钱，赚了钱呢就一起分。这个时候呢，口袋妖怪的创意人田尻智就去参加任天堂的这个选举，类似于创业选拔。当初呢，田尻智的口袋妖怪就落选了，他这个创意落选了。但是在马里奥之父宫本茂的支持下，最终还是入选了。所以说，这个口袋妖怪还是要感谢一下宫本茂，如果没有他的话，口袋妖怪很可能就拿不到任天堂的钱，非常可能，如果你没有拿到钱的话，这个口袋妖怪就有可能就不存在了。

当时任天堂创投基金的老大，那个叫石原恒和，也非常看好这个游戏。这个游戏就是这样的，拿到了任天堂的钱，也就这样不死不活地开发着，Game Freak公司几度也就差一点倒闭。为啥没有倒闭呢？主要得益于两个因素，一个是田尻智。他老爸是个非常有钱的人，有了这个有钱的老爸，没钱了你就去公司找老爸拿一点。所以说有个好爹还是非常重要。第2个呢，就是前面说到了任天堂创投基金的老大石原恒和非常的看好他。他本人也有一个公司，专门给Game Freak输血。这个时候大家也就看出来了，上文所说的这三家公司同时拥有口袋妖怪：一个是任天堂，因为他出钱了嘛，作为创意大赛的获胜者，任天堂投了一部分钱；另一个呢，就是田尻智自己的公司Game Freak，是专门用来做游戏的；还有一家呢，就是石原恒和的公司Creatures。这三家公司呢，任天堂和Creatures负责给钱，Game Freak负责开发。

前面也提到了，田尻智公司要倒闭的时候，他就去他爸爸那里拿点钱花花。所以说呢，他老爸对这个口袋妖怪也算是功不可没。所以呢，他老爸现在也是Game Freak公司的高管，毕竟也情有可原，毕竟他老爸也出了不少钱。一是救公司，主要还是救儿子。

在1996年的2月27日，这款游戏也终于做完了。总共开发了六年，本来可能打算是两年，但销量并不好。并不像电影里的桥段一样，一开始很痛苦，一上市就成功。游戏上市之后，销量还是非常的差。

你说为什么差呢？因为这个游戏，是给Game Boy开发的。Game Boy它也有个生命周期。在一九九六年的时候，Game Boy已经上市很久了。而这个游戏，因为开发进度太慢，等了六年才开发好。本来两年搞定，结果开发完成的时候，整个硬件就已经落后了。任天堂当时又已经着手开发下一代掌机。

后来是怎么火的呢？就是游戏的本身质量肯定是没有问题。任天堂包括这几个主创也是心知肚明，就是时候不对，开发太慢了。一九九六年的时候，Game Boy硬件已经不行，就相当于现在我们给Windows XP开发了一个软件。因为现在大家也都用Windows 10，你给Windows XP开发的软件再好，也已经落后了。

因此，当时的推广只能另辟蹊径，开始在杂志上画口袋妖怪的形象，画漫画，漫画也就慢慢的火了。就类似于美国公司孩之宝，为了卖变形金刚的玩具，就拍摄了一部动画片，就叫《变形金刚》。刚开始的时候动画片就胡编乱造，后来发现这个动画片火了，只好把前面的bug不停的掩盖。你这个动画片越火，玩具肯定就卖的越多，然后相互促进。你这个玩具卖的越多呢，小朋友就越来越喜欢看《变形金刚》的动画片。

在这里也类似于这个情况，为了卖游戏，就搞了一个漫画。你这个漫画越火，游戏肯定是卖的越多；你游戏越多呢，你这个漫画肯定就越火，也是相互促进。所以有的时候啊，你光有好的产品也不行，这个营销也非常的重要。

但这个火了以后，后面的故事大家也就耳熟能详了。就这样，一个传奇也就从此上演。口袋妖怪算是第一个全方位推广的游戏。就是口袋妖怪当时就有游戏、有动画、有漫画、有体验店，还有游乐场，所有能玩的地方肯定有这个口袋妖怪。

对这里说一下，口袋妖怪和精灵宝可梦其实是一个东西。所以有时候我就说混了，这个也没关系。现在手机上也有了，我们也知道现在大家在中国还不能玩，大家都用一个虚假的GPS在那里玩。如果以后手机还会出现奇奇怪怪的各种设备，其他的我是不敢打赌，但这个我肯定是敢跟任何人打赌：只要有下一个热门的设备出来，口袋妖怪肯定会登陆。这一点是毫无疑问的，就是我对口袋妖怪的看法，它非常的先进，并且它是全方位的。它比马里奥或者是塞尔达那些东西最后的经营理念都要先进。他现在是排名销量第二的游戏，还差一点就要超过马里奥了。
